### ISSUE TITLE
Flipped infix Applicative::ap

### ISSUE THREAD

**Issue by toxxmeister** [arrow-kt/arrow#1000]
Current signature of `Applicative`'s `ap` is:
```kotlin
Kind<F, A>.(Kind<F, (A) -> B>): Kind<F, B>
```

By flipping the receiver and parameter signature to:
```kotlin
Kind<F, (A) -> B>.ap(Kind<F, A>): Kind<F, B>
```
and making the function infix, we could achieve pretty nice syntax for working with curried functions:
```kotlin
pure(f.curried()) ap fa ap fb ap fc

// or multiline (parentheses are mandatory):
(pure(f.curried())
        ap complexExpression1
        ap complexExpression2
        ap complexExpression3)
```

Do you think it'd make sense to change the signature of `ap`, or even just include an infix version alongside the existing one?

**Comment by pakoito** [comment]
I'd be happy with a new infix `ap` alongside the existing one, yeah.

**Comment by toxxmeister** [comment]
@pakoito Great!

What would you recommend as a name for the infix version?

There is a platform declaration clash between the original and infix version, and since it's an infix function, we cannot add a dummy parameter to resolve the issue, nor can we add a `@JvmName` annotation since it's an interface method.
This means that we'd either have to drop the original version, which I suppose is not an option, or think of a different name.
Something like `app` or `apply` might work, in my opinion.

**Comment by pakoito** [comment]
`apply` is already a language construct, so let's go with something else. `apPipe` maybe?

**Comment by toxxmeister** [comment]
@pakoito 
I wouldn't consider `apply` a language construct (it's merely a scoping function), and there are no cases I can foresee where there'd be confusion between the two.
I'd definitely be open to `apply` as I think it makes the most sense semantically.

I'm not entirely satisfied with `apPipe` as, in my opinion, piping implies some kind of left-to-right functional composition, while this is functional application in context.
It doesn't entirely make its intent clear.

Another possibility is overloading the `*` operator due to similarity to Haskell's `<*>` operator:

```kotlin
operator fun <A, B> Kind<F, (A) -> B>.times(fa: Kind<F, A>): Kind<F, B>
```

This'd in turn allow for even more elegant syntax:

```kotlin
pure(f.curried()) * fa * fb * fc

// or multiline (parentheses are mandatory):
(pure(f.curried())
        * complexExpression1
        * complexExpression2
        * complexExpression3)
```

Furthermore, there shouldn't be any conflicts or ambiguity as effect datatypes usually wouldn't have the operator already overloaded.
The only question is how open the project is for utilizing operator overloading and where do we draw the line for "operator abuse".

**Comment by pakoito** [comment]
We decided not to cross the operator abuse line a while ago, even if we had multiple chances to do it in the past :D I'm open to more name suggestions, apPipe was just what came to my mind.

**Comment by raulraja** [comment]
I think we are still in time to flip the receiver and args in `ap` as suggested by @toxxmeister and have the single infix in `Applicative`. There are no strong reasons AFAIK why the current layout of receiver and params can't be switched besides the obvious bin. Compat issues of people having to migrate if they are using ap explicitly today.

**Comment by toxxmeister** [comment]
@raulraja 
Shouldn't the next release (0.8.0) have some breaking changes either way? If so, it'd be a good opportunity to include the new `ap`.
Also, I doubt the current implementation was used too much, mostly due to its clunkiness which this new approach tries to solve.

**Comment by raulraja** [comment]
@toxxmeister yeah, we can just flip it and leave it infix as single `ap` function in `Applicative`. @pakoito any concerns about that?

**Comment by toxxmeister** [comment]
@pakoito If you agree with @raulraja , I could start with the implementation and docs.

**Comment by pakoito** [comment]
After experimenting on the sandbox I'd rather we created a new function instead. I believe that the most common use case will still be `a ap f ap g ap h`. It's just a case for a name, and given how we've handled this before `ap_` or `ap1` would work.

**Comment by toxxmeister** [comment]
After talking to @pakoito , we've reached the following conclusion:
Current `ap` combinator would be renamed to `apPipe` and would provide the actual implementation.
Infix `ap` combinator would base its implementation on `apPipe`.

@raulraja Do you agree with this approach?

**Comment by raulraja** [comment]
@toxxmeister agreed
