### ISSUE TITLE
Arithmetic extension functions for Options

### ISSUE THREAD

**Issue by fabriciorissetto** [arrow-kt/arrow#1002]
Hi guys, I'm really noob in FP and just have started to use some Arrow features (currently I'm using `Options`, `Try` and Modad Comprehensions).

In my current project we ended up creating some helper functions like the ones I'll show below, but I'm concerned if we have created it based on our ignorance about some other possible solutions. So I would like to know if you think it makes sense and, if the answer is YES, if there is room in arrow for we to implement this kind of functions.

## Funcions we have created:
```
fun <T> List<T>.sumOptions(selector: (T) -> Option<BigDecimal>): Option<BigDecimal> {
    return this.map(selector).fold(Option(BigDecimal(0))) { acc, option -> sumOptions(acc, option) }
}

fun sumOptions(firstOption: Option<BigDecimal>, secondOption: Option<BigDecimal>): Option<BigDecimal> {
    return firstOption.map(secondOption) { firstContent, secondContent -> firstContent.add(secondContent) }
}

fun divideOptions(firstOption: Option<BigDecimal>, secondOption: Option<BigDecimal>): Option<BigDecimal> {
    return firstOption.map(secondOption) { firstContent, secondContent ->
        Try { firstContent.divide(secondContent) }.toOption()
    }.flatMap { it }
}
```

## Usage:
```
val totalIncome = persons.sumOptions { it.montlyIncome } //where montlyIncome is an Option<BigDecimal>

val divisionResult = divideOptions(firstOption, secondOption)
```

We created it because I thought it would be easier for other people to read our code with this functions than:

## Without it
```
val totalIncome = persons.map(selector).fold(Option(BigDecimal(0))) { acc, option ->
    acc.map(option) { firstContent, secondContent -> firstContent.add(secondContent) }
}

val divisionResult = firstOption.map(secondOption) { firstContent, secondContent ->
    Try { firstContent.divide(secondContent) }.toOption()
}.flatMap { it }
```

**Comment by raulraja** [comment]
@fabriciorissetto Arrow supports already the notion of combination through `Semigroup` and the notion of generically mapping over values that are wrapped by a type constructor such as `Option`.
Additionally Arrow [supports polymorphic definitions](https://arrow-kt.io/docs/patterns/polymorphic_programs/) that allows you to write the code that performs the kind of wrapped sum you are doing over Option for all data types that provide an [`Applicative`](https://arrow-kt.io/docs/typeclasses/applicative/) instance including `Option`. See the program below for an instance of `Semigroup<BigDecimal>` and a functions that generalizes the operation for all type constructors:
```kotlin
object BigDecimalSemigroup : Semigroup<BigDecimal> {
  override fun BigDecimal.combine(b: BigDecimal): BigDecimal = this + b
}
  
fun <F, A> Applicative<F>.sum(SA: Semigroup<A>, fa: Kind<F, A>, fb: Kind<F, A>): Kind<F, A> =
  map(fa, fb) { (a, b) -> SA.run { a + b } }
  
val resultOption: Option<BigDecimal> = 
  Option.applicative().sum(BigDecimalSemigroup, Option(BigDecimal(1)), Option(BigDecimal(1))).fix()

val resultTry: Try<BigDecimal> =
  Try.applicative().sum(BigDecimalSemigroup, Try { BigDecimal(1) }, Try { BigDecimal(1) }).fix()
```
[`Applicative#map`](https://arrow-kt.io/docs/typeclasses/applicative/#kindf-amap2) allows you to compute over the results of independent operations that can be evaluated individually. `map` also preserves type information regardless of arity so you could map over distinct values like `Option<Int>` and `Option<String>` and then use it's result to produce a transformation that is returned in the same type constructor that you used in the arguments.

**Comment by fabriciorissetto** [comment]
Thanks @raulraja, I learned a lot from your answer. I've improved my extension functions but I am still needing them: 

### Sum that works for any applicative instance:

```
fun <F> Applicative<F>.sum(vararg kinds: Kind<F, BigDecimal>): Kind<F, BigDecimal> {
    return kinds.reduce { kindA, kindB ->
        map(kindA, kindB) { (a, b) -> a.add(b) }
    }
}
``` 

### Operators overrided for the types `Option<BigDecimal>` (`+` and `/`):

```
operator fun Option<BigDecimal>.plus(otherOption: Option<BigDecimal>): Option<BigDecimal> {
    return Option.applicative().sum(this, otherOption).fix()
}

operator fun Option<BigDecimal>.div(otherOption: Option<BigDecimal>): Option<BigDecimal> {
    return this.map(otherOption) { firstContent, secondContent ->
        Try { firstContent.divide(secondContent, 20, RoundingMode.HALF_EVEN).stripTrailingZeros() }.toOption()
    }.flatMap { it }
}
```

Do you think it makes sense to add functions like these in Arrow? If so I can dedicate some time to create an pull request with some of these functions for the other numeric types and other operators (`-`, `*`, `%`, ..)

**Comment by raulraja** [comment]
@fabriciorissetto Not specifically for `Option`. 

what happens in the generic definition if you pass no arguments or one argument? That function with varargs is unsafe because empty lists may not be reduced unless you want mack an Option See `Foldable#reduceLeftToOption`. I think that may blow up and you need a non empty list as a argument or use the `Monoid<BigDecimal>` to return an empty value in the case the list is empty and manually check for it.

In whatever case there is no need to be concrete because what you want to achieve will be automatically added for all extension functions defined in the type classes. 

That means that you can submit a PR to add inside `Applicative` the following definition:
```
operator fun Kind<F, BigDecimal>.plus(other: Kind<F, BigDecimal>): Kind<F, BigDecimal> =
    map(this, other) { (a, b) -> a + b }
```
And the same for all the different numeric data types and arithmetic for which the Kotlin standard library provides `plus`, `minus` etc...

In Arrow 0.8.0 having those methods there will generate extension functions for Option and other concrete data types that provide an Applicative instances so you don't have to write them by hand yourself.

**Comment by pakoito** [comment]
If the definition could be `map(this, other, ::plus)` it'd be great :)

**Comment by fabriciorissetto** [comment]
Sorry about the delay guys.

@pakoito thanks for the tip, but `map(this, other, ::plus)` didn't worked because the function `::plus` defined inside BigDecimal   receives just 1 parameter (it sums the current BigDecimal instance (`this`) with the supplied parameter).

@raulraja you were right. That `varargs` would produce runtime exception for empty lists.

About the extension functions inside `Applicative`, I tried to create them but find out that they conflict  due to the type erasure. For example, this compiles successfully:

```kotlin
//BigDecimal
operator fun Kind<F, BigDecimal>.plus(other: Kind<F, BigDecimal>): Kind<F, BigDecimal> =
    map(this, other) { (a, b) -> a.add(b) }

operator fun Kind<F, BigDecimal>.minus(other: Kind<F, BigDecimal>): Kind<F, BigDecimal> =
    map(this, other) { (a, b) -> a.minus(b) }

operator fun Kind<F, BigDecimal>.times(other: Kind<F, BigDecimal>): Kind<F, BigDecimal> =
    map(this, other) { (a, b) -> a.multiply(b) }

operator fun Kind<F, BigDecimal>.div(other: Kind<F, BigDecimal>): Kind<F, BigDecimal> =
    map(this, other) { (a, b) -> a.div(b) }

operator fun Kind<F, BigDecimal>.rem(other: Kind<F, BigDecimal>): Kind<F, BigDecimal> =
    map(this, other) { (a, b) -> a.remainder(b) }
```

But when I add the same definitions for other numeric types like this:

```kotlin
//Double
operator fun Kind<F, Double>.plus(other: Kind<F, Double>): Kind<F, Double> =
  map(this, other) { (a, b) -> a + b }

operator fun Kind<F, Double>.minus(other: Kind<F, Double>): Kind<F, Double> =
  map(this, other) { (a, b) -> a - b }

operator fun Kind<F, Double>.times(other: Kind<F, Double>): Kind<F, Double> =
  map(this, other) { (a, b) -> a * b }

operator fun Kind<F, Double>.div(other: Kind<F, Double>): Kind<F, Double> =
  map(this, other) { (a, b) -> a / b }

operator fun Kind<F, Double>.rem(other: Kind<F, Double>): Kind<F, Double> =
  map(this, other) { (a, b) -> a % b }
```

It conflicts.

![image](https://user-images.githubusercontent.com/1520059/45978340-a0e89280-c03b-11e8-83e7-02924ca0dc05.png)

The decompiled code of the BigDecimals extension funcions (my first code snippet):

![image](https://user-images.githubusercontent.com/1520059/45978652-659a9380-c03c-11e8-8348-e06daa153f2c.png)

Do you have another ideas?

**Comment by matheusca** [comment]
@fabriciorissetto what do you think to turn your `Kind` more generic?

you could use:

```
operator fun <T : Number> Kind<F, T>.plus...
```

You could use as I 've shown, because the types are `Number` too.

So, I don't know if it's work, but you could try. Let me know about.

**Comment by fabriciorissetto** [comment]
Great idea @matheusca . I think something like this should work (`plus` example):

```kotlin
operator fun <T : Number> Kind<F, T>.plus(other: Kind<F, T>): Kind<F, T> =
    map(this, other) { (a, b) ->
      when {
        a is BigDecimal && b is BigDecimal -> a.add(b)
        a is Long && b is Long -> a + b
        a is Int && b is Int -> a + b
        a is Short && b is Short -> a + b
        a is Byte && b is Byte -> a + b
        a is Double && b is Double -> a + b
        a is Float && b is Float -> a + b
        else -> throw RuntimeException("Unknown numeric type")
      } as T
    }
```

**Comment by raulraja** [comment]
Closing this old issue as Arrow no longer supports kinds and provides instead effect handlers to bind the value and apply the natural operators unboxed. Feel free to open a new issue for new interesting operators over the existing types in 0.13.x and onward. Thanks!
