### ISSUE TITLE
Kotlin JS / multi-platform support

### ISSUE THREAD

**Issue by wadejensen** [arrow-kt/arrow#1007]
I went to use Arrow for a frontend application transpiled from Kotlin to JavaScript and realised that it Arrow doesn't support the JS platform due to explicit Java dependencies.
It would be awesome to see Arrow migrate to being a multiplatform library.

**Comment by raulraja** [comment]
@wadejensen I think this is everyone's desire as well but nobody currently pushing the lib has that use case. If you want to give it a shot the first thing we have to do is compile a shopping list of what needs to change currently in the code base to support Kotlin JS/Native and we can take it from there recommending approaches to tackle each one of the parts.

**Comment by wadejensen** [comment]
Thanks for the response @raulraja. My use case is very casual at the moment, so I don't have bandwidth to dedicate to this, but if that changes I will give it a red hot go.

**Comment by pakoito** [comment]
@AregevDev took a look for the Native port, and we're currently blocked on `kapt` and KindedJ.

**Comment by pakoito** [comment]
No, and no plans for it either.

**Comment by AregevDev** [comment]
Maybe try to generate the code and then call the compiler that will include the generated classes?

**Comment by AregevDev** [comment]
They are only generating a `class` and two `typealiases`...

**Comment by janvladimirmostert** [comment]
what is kapt used for, only for the `@optic` annotations ?

**Comment by pakoito** [comment]
@higherkind is the blocker for arrow-core, @extends for arrow-typeclasses

**Comment by JorgeCastilloPrz** [comment]
I also assume kapt (specifically annotation processors) will not be a thing for JavaScript either. We'd probably need to look for alternatives on code derivation for both platforms that can have a common API but implemented differently.

**Comment by 1Jajen1** [comment]
How do projects like kotlinx.serialization etc work? Are they providing their own compiler plugin? Maybe that is a way to go, may be a lot of work tho.

**Comment by viluon** [comment]
Regarding compiler plugins, [this](https://resources.jetbrains.com/storage/products/kotlinconf2018/slides/5_Writing%20Your%20First%20Kotlin%20Compiler%20Plugin.pdf) is a valuable resource.

**Comment by MattX** [comment]
(I don't know much about JVM annotation processors, so maybe this is very dumb)

My understanding is that Kapt, like other annotation processors, will generate extra .kt files, which are then included in the regular compilation process. Would it be possible to run Kapt in a JVM environment to generate these files, and then compile everything with the Kotlin/JS compiler? I'm curious to know why not if not.

**Comment by kierans** [comment]
My use case is that I'm writing a library that I want to be able to use on iOS as well as JVM targets (including Android). It would be super awesome if Arrow could do this.

**Comment by nomisRev** [comment]
Hey @kierans, (and everyone following this thread)
These efforts are currently in  progress. You can follow the progress in the PRs.

Here is a link to the PR working on JS support (almost finished for Arrow Core), Native is up next :) https://github.com/arrow-kt/arrow/pull/2409
Native for Arrow Fx Coroutines might be a little delayed compared to other libraries, since the underlying library KotlinX Coroutines support for native is still experimental and not officially released under the stable releases AFAIK.

As soon as this is merged you can try it on th SNAPSHOT release, the first MILESTONE for Arrow 1.0.0 is expected this summer.

**Comment by kierans** [comment]
@raulraja Can you say why you closed this please? It seems a bit arbitrary.

**Comment by viluon** [comment]
I see that #2409 got merged, but I'd say proper support also requires documentation on setting up a multiplatform project with Arrow (and perhaps which Arrow libraries work with JS and which ones don't).

**Comment by raulraja** [comment]
@kierans @viluon Arrow is now MPP in main, and all tests are passing. The site also is being published next week with instructions to include Arrow MPP in any project as soon as we can add the native tests, which we are waiting for support for Kotest. I closed this because the work is done but reopening now until it's all available to the public.

**Comment by kierans** [comment]
Thanks for the update @raulraja.

**Comment by nomisRev** [comment]
For those wanting to try Arrow on JS.
https://github.com/arrow-kt/Arrow-JS-Template

**Comment by nomisRev** [comment]
This ticket can finally be closed 🥳 Arrow 1.0 comes with JS support!
If you have any feedback be sure to create an issue here, or chat in #arrow on Kotlin Slack.

**Comment by kierans** [comment]
@nomisRev Given this ticket was also about "multi platform support", does this also mean that Arrow 1.0 can be used in native code eg: iOS?

**Comment by pakoito** [comment]
> 
> 
> @nomisRev Given this ticket was also about "multi platform support", does this also mean that Arrow 1.0 can be used in native code eg: iOS?

Yes!!

**Comment by mysticfall** [comment]
I believe we still lack compiler support for Optics on non-JVM platforms? If so, is there an ongoing effort or existing issue about it?

If there's none, I'd like to open a feature request so that I could keep track of updates.

**Comment by nomisRev** [comment]
Hey @mysticfall,

This is already in progress on the [Arrow Meta](https://github.com/arrow-kt/arrow-meta) repo, and we're currently testing it before releasing it. There is a ticket here, https://github.com/arrow-kt/arrow-meta/issues/771.

**Comment by mysticfall** [comment]
@nomisRev Thanks much for the info! I'll subscribe to the issue then. Can't wait to test it myself :)
