### ISSUE TITLE
Provide static instances for simple datatypes

### ISSUE THREAD

**Issue by toxxmeister** [arrow-kt/arrow#1010]
Instances for "simple" datatypes (simple as in the instances do not depend on other instances), could be statically created and cast to their appropriate types when needed.

The simpler case are datatypes with a single type parameter, such as `Option`:

```kotlin
object OptionMonadInstance : Monad<ForOption> { /*...*/ }
inline fun Option.Companion.monad() = OptionMonadInstance
```

Datatypes with more than one type parameter require some `Nothing` magic and casting:

```kotlin
class EitherMonadInstance<A> : Monad<EitherPartialOf<A>> { /*...*/ }
val eitherMonadInstance = EitherMonadInstance<Nothing>()
inline fun <A> Either.Companion.monad() = eitherMonadInstance as EitherMonadInstance<A>
```

We can't really use this for transformer instances, but for simple datatypes this could prove to be a worthwhile optimization.

**Comment by raulraja** [comment]
@toxxmeister this can be a great optimization. This would have to be implemented in the codegen section of `@instance` but I'm currently in the middle of a major refactor to introduce `arrow-meta` on 0.8.0 which includes a functional api and AST for annotation processing. https://github.com/arrow-kt/arrow/compare/rr-instance-syntax-extensions#diff-a96b46623a98f74340557dc3db4062c1

Once we have this in master if you are interested you can contribute this to the Processor in charge of the codegen so we can get these optimizations in.

**Comment by toxxmeister** [comment]
@raulraja Yes, I'd love to. Let me know once the refactor is done and I'll proceed.

**Comment by pakoito** [comment]
@raulraja don't forget to at least add @autofold to the sealed classes without optics :D

**Comment by raulraja** [comment]
Closing outdated issue as the `extension` processor is no longer part of Arrow. thanks, @toxxmeister @pakoito
