### ISSUE TITLE
Array-backed generic tuples

### ISSUE THREAD

**Issue by toxxmeister** [arrow-kt/arrow#1015]
This is an attempt at implementing performant array-backed type-safe generic tuples.
It's very similar to `HList` on type-level, which due to its nature is not very performant.
Furthermore, convenience typealiases are introduced to make them more flexible than current `HList`s.

Do you find this useful? Could the API be improved/expanded?

## Implementation and API

Let's start by introducing `TupN` which serves as our size and type marker:

```kotlin
sealed class TupN

class TupCons<out H, out T : TupN> private constructor() : TupN()

@Suppress("CanSealedSubClassBeObject")
class TupNil private constructor() : TupN()
```

The actual tuple is just a simple array tagged with the specified `N : TupN`:

```kotlin
class Tup<out N : TupN>
  internal constructor(internal vararg val data: Any?)
```

### Structure preserving types

`Tup{N}Cons<A1, ..., AN, TS>` allows us to only focus on the relevant part of the tuple (`A1, ..., AN`), while capturing the rest of the tuple through `TS`.

```kotlin
typealias Tup0Cons<TS> = Tup<TS>
typealias Tup1Cons<A, TS> = Tup0Cons<TupCons<A, TS>>
typealias Tup2Cons<A, B, TS> = Tup1Cons<A, TupCons<B, TS>>
```

### Exact size types

Exact size tuples are defined through `Tup{N}` types:

```kotlin
typealias Tup0 = Tup0Cons<TupNil>
typealias Tup1<A> = Tup1Cons<A, TupNil>
typealias Tup2<A, B> = Tup2Cons<A, B, TupNil>
```

### Lower bound size types

We can define lower bound on tuple size without necessarily caring about the rest of the tuple outside of that size:

```kotlin
typealias Tup0Plus = Tup0Cons<*>
typealias Tup1Plus<A> = Tup1Cons<A, *>
typealias Tup2Plus<A, B> = Tup2Cons<A, B, *>
```

### Structure preserving copy

Copy functions which preserve the rest of the structure are defined:

```kotlin
fun <A, B, TS : TupN> Tup2Cons<A, B, TS>.copy(
  a: A = data[0] as A,
  b: B = data[1] as B
): Tup2Cons<A, B, TS> =
  Tup(a, b, *data.copyOfRange(2, data.size))
```

### Focused copy

If we don't want to carry potential additional data, we can `focusN` instead of `copy`:

```kotlin
fun <A, B> Tup2Plus<A, B>.focus2(
  a: A = data[0] as A,
  b: B = data[1] as B
): Tup2<A, B> =
  Tup(a, b)
```

### Accessing values

The user can never directly access the array, only through our defined accessors and component functions:

```kotlin
val <A> Tup1Plus<A>._1: A get() = data[0] as A
operator fun <A> Tup1Plus<A>.component1(): A = data[0] as A

val <A> Tup2Plus<*, A>._2: A get() = data[1] as A
operator fun <A> Tup2Plus<*, A>.component2(): A = data[1] as A

val <A> Tup3Plus<*, *, A>._3: A get() = data[2] as A
operator fun <A> Tup3Plus<*, *, A>.component3(): A = data[2] as A
```

Accessor functions follow Scala-like naming (`_n`), although, it could easily be switched to `a`, `b`, `c`, etc.

### Mapping functions

```kotlin
fun <A, B, C, C1, TS : TupN>
  Tup3Cons<A, B, C, TS>.map3(f: (C) -> C1): Tup3Cons<A, B, C1, TS> =
  Tup(*data.copyOfRange(0, 2),
      f(data[2] as C),
      *data.copyOfRange(3, data.size))
```

### Regular constructors

```kotlin
fun tupOf(): Tup0 = Tup()
fun <A> tupOf(a: A): Tup1<A> = Tup(a)
fun <A, B> tupOf(a: A, b: B): Tup2<A, B> = Tup(a, b)
```

### Appending constructors

```kotlin
infix fun <A, B> A.with(b: B): Tup2<A, B> = Tup(this, b)

@JvmName("tup0With")
infix fun <A> Tup0.with(a: A): Tup1<A> = Tup(a)

@JvmName("tup1With")
infix fun <A, B> Tup1<A>.with(b: B): Tup2<A, B> = Tup(data[0], b)

@JvmName("tup2With")
infix fun <A, B, C> Tup2<A, B>.with(c: C): Tup3<A, B, C> =
  Tup(*data.copyOfRange(0, 2), c)
```

## Examples

Example of using `TupNCons` to preserve the rest of the structure:

```kotlin
fun <A, B, TS : TupN> swapFirstTwo(t: Tup2Cons<A, B, TS>): Tup2Cons<B, A, TS> =
  t.map1 { t._2 }.map2 { t._1 }

val t1: Tup3<Int, String, Double> = 1 with "2" with 3.0
val t2: Tup3<String, Int, Double> = t1.swapFirstTwo()

val t3: Tup2Plus<String, Int> = t2
val t4: Tup1Plus<String> = t3
val t5: Tup0Plus = t4
```

**Comment by pakoito** [comment]
![](https://i.imgur.com/mp6PNWI.png)

**Comment by toxxmeister** [comment]
@pakoito The linked PR includes the currently defined API.
I think it definitely needs some work before it's ready, so I'm open for discussion.

**Comment by JorgeCastilloPrz** [comment]
In an effort to clean the issue list we got to this one. It's been on standby since more than a year ago. Generic tuples are based on type proofs and already in the arrow-meta prelude, so we're closing this issue for now.
