### ISSUE TITLE
Question about Blocking thread jumps In Android

### ISSUE THREAD

**Issue by maruiz81** [arrow-kt/arrow#1018]
Hi, I am trying to do a code to perform an operation (in this case in an request to server) in background and the result in UI thread:

            IO.monadDefer().bindingCatch {
                val resultData = bindIn(CommonPool) { request }
                bindIn(UI) { resultData }.bind()
            }.fix()

The problem I am having is all the code is running in the UI thread, so I am getting an Android Exception. Do you have any idea why this is happening?

**Comment by pakoito** [comment]
I'd need a longer example of what request and resultData do to assess this. The second `bindIn(UI) { resultData }.bind()` shouldn't need a call to `bind()` either.

I'd suggest going with the non-blocking version if at all possible. It's better designed and tested, and the blocking one will probably be deprecated.
