### ISSUE TITLE
Migrate to kotlinx.coroutines 0.26.0-eap13

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1021]
Re-design with CoroutineScope in mind: https://github.com/Kotlin/kotlinx.coroutines/releases/tag/0.26.0

I'd rather we rolled this out on 0.8.0 alongside the breaking change to Kotlin 1.3, and the new typeclass gen.

**Comment by Octogonapus** [comment]
Surely this should be closed?

**Comment by pakoito** [comment]
Yes!
