### ISSUE TITLE
Day convolution for comonadic UIs

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1026]
https://blog.functorial.com/posts/2016-08-08-Comonad-And-Day-Convolution.html

https://functorial.com/the-future-is-comonadic/main.pdf

**Comment by Cotel** [comment]
I was planning to add it to #1020. Maybe I forgot to tag it as a Work in Progress 😅

**Comment by pakoito** [comment]
Gotcha, closing this then!
