### ISSUE TITLE
Comonadic UI: next steps

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1027]
As per this tweet: https://twitter.com/arthurxavierx/status/1040209220593954816

Some existing exploration around composing UIs and parent-child communication: https://arthurxavierx.github.io/RealWorldAppComonadicUI.pdf

**Comment by raulraja** [comment]
I believe this was added to Arrow but removed before 0.13 due to lack of docs and interest, as those data types did not get much use. I'm closing outdated issue, Thanks @Cotel @pakoito
