### ISSUE TITLE
Master is broken

### ISSUE THREAD

**Issue by JLLeitschuh** [arrow-kt/arrow#1033]
Running `./gradlew` against `master` currently throws the following exception:
```
./gradlew
Starting a Gradle Daemon, 1 busy and 2 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'arrow'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve io.arrow-kt:ank-gradle-plugin:0.7.1.
     Required by:
         project :
      > Could not resolve io.arrow-kt:ank-gradle-plugin:0.7.1.
         > Could not get resource 'https://jcenter.bintray.com/io/arrow-kt/ank-gradle-plugin/0.7.1/ank-gradle-plugin-0.7.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/io/arrow-kt/ank-gradle-plugin/0.7.1/ank-gradle-plugin-0.7.1.pom'.
               > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s

```

**Comment by JLLeitschuh** [comment]
Looking at the bintray repository, this looks accurate. There isn't a version 0.7.1 published:
https://jcenter.bintray.com/io/arrow-kt/ank-gradle-plugin/

**Comment by pakoito** [comment]
Are you in a branch maybe?

<img width="1075" alt="screen shot 2018-10-02 at 10 05 39 pm" src="https://user-images.githubusercontent.com/514871/46376963-55636380-c68f-11e8-9ba5-f74d04b15c36.png">

**Comment by pakoito** [comment]
> Looking at the bintray repository, this looks accurate. There isn't a version 0.7.1 published:
> https://jcenter.bintray.com/io/arrow-kt/ank-gradle-plugin/

Weird, I can't find it either. @Guardiola31337 do you know ??

**Comment by JLLeitschuh** [comment]
Just pulled master and tried to build. This seems to have been resolved.
