### ISSUE TITLE
Enforce Kotlin and Coroutine release version when releasing Arrow

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow#1085]
Ensure Kotlin version and coroutines version only point to released versions as part of the Arrow release. In 0.8.0 we released depending on RC builds and that should never happen.

**Comment by alissonfpmorais** [comment]
I want to take this one!

**Comment by pakoito** [comment]
What's the plan? I don't know how to enforce it!

**Comment by raulraja** [comment]
I think as a rule of thumb Arrow has to go with the standard lib kotlin version release, so it should be enough to get the latest version value in maven central releases and ensure we are not behind. This is mostly a CI task to make sure we are not releasing without updating to the latest stable std lib version.

**Comment by alissonfpmorais** [comment]
My plan is create a Gradle task using same plugin already used by arrow, gradle-versions-plugin from ben-manes and call this task on travis whenever a new release is deployed. If dependency version is correct then build pass, otherwise fails. What do you think?
