### ISSUE TITLE
Concurrent

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#1090]
`Concurrent` is a Type class for `Async` data types that are cancelable and can be started concurrently.

Concurrent extends `Async`, so any `Concurrent` instance must inherit from the `Async` one for the each data type.

[This is the cats implementation](https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/Concurrent.scala#L207) for reference.

 One diagram for context:

![typeclass_diagram](https://user-images.githubusercontent.com/6547526/48195431-ee9d2e00-e34f-11e8-8a5b-56395b14a9fc.jpg)

**Comment by nomisRev** [comment]
Closed by #1132
