### ISSUE TITLE
Promise (cats Deferred)

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#1092]
Requires #1090 

**Disclaimer: This has nothing to do with the already present `DeferredK` which works over the coroutines Deferred data type.**

[There is a `Deferred` type that works over any `F` in cats-effect](https://github.com/typelevel/cats-effect/blob/84696fb35ec8464d277f221991a64882c79363a0/core/shared/src/main/scala/cats/effect/concurrent/Deferred.scala#L48) which is basically a Future or in other words, a Promise of a value that works over any data type `F`. 

We need to create this `Deferred<F>` for continuing our work over the streams library. We should probably call it `Promise<F>` or something similar, instead of `Deferred`,  to avoid confusion with Kotlin coroutines `Deferred`.

[Here you have the cats docs](https://github.com/typelevel/cats-effect/blob/master/site/src/main/tut/concurrency/deferred.md) for better context on understanding the concept.

**Comment by nomisRev** [comment]
Here is a working version for `Async` https://github.com/arrow-kt/arrow/blob/simon-concurrent/modules/effects/arrow-effects/src/main/kotlin/arrow/effects/internal/Promise.kt
