### ISSUE TITLE
Semaphore

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#1093]
Requires #1090 

A `Semaphore<F>`. Basically the semaphore functionality but for functional programming, so it works over any `F`. 

`Semaphore<F>` is also required for arrow streams.

* [Here you have the cats data type](https://github.com/typelevel/cats-effect/blob/84696fb35ec8464d277f221991a64882c79363a0/core/shared/src/main/scala/cats/effect/concurrent/Semaphore.scala#L37).
* [Here you have cats Semaphore docs for more context](https://github.com/typelevel/cats-effect/blob/master/site/src/main/tut/concurrency/semaphore.md)

**Comment by nomisRev** [comment]
Closed by #1151
