### ISSUE TITLE
Arrow-refinement module

### ISSUE THREAD

**Issue by Cotel** [arrow-kt/arrow#1099]
We should define what things we want to include in this API and choose the best encoding from there.

The main purpose of this module is offering a set of refined types over primitives like `PositiveInt`, `RegexString`, `NonEmptyString`, etc. And a DSL for easily define new refined types.

We could also include a compiler plugin for checking literals and prevent situations like `-1.positive()` at compile time. 

Some of the possible encodings are:

**Class with private constructor and `invoke` operator in its companion object to check the refinement**

```kotlin
object RefinedPredicateException : IllegalArgumentException("Value does not fulfill predicate")

class NonZeroInt private constructor(val value: Int) {
  companion object {

    private val predicate = { x: Int -> x != 0 }

    operator fun invoke(x: Int): Validated<RefinedPredicateException, NonZeroInt> = 
      if (predicate(x)) NonZeroInt(x).valid() else RefinedPredicateException.invalid()

    operator fun <F> invoke(x: Int, AE: ApplicativeError<F, RefinedPredicateException>): Kind<F, NonZeroInt> = AE.run {
      if (predicate(x)) just(NonZeroInt(x)) else raiseError(RefinedPredicateException)
    }
  }
}

// Usage
val validResult = NonZeroInt(12) // Valid(NonZeroInt(12))
val invalidResult = NonZeroInt(0) // Invalid(e=RefinedPredicateException)

val rightResult = NonZeroInt(12, Either.applicativeError()) // Right(NonZeroInt(12))
```

**Creating a Refined typeclass and then extending the typeclass for every new refined type**

This approach deviates less from the Arrow conventions.

```kotlin
interface Refinement<F, A> {

  fun applicativeError(): ApplicativeError<F, Nel<RefinedPredicateException>>

  fun A.refinement(): Boolean

  fun refine(value: A): Kind<F, A> = applicativeError().run {
    value.refinement()
      .maybe { just(value) }
      .getOrElse { raiseError(Nel.of(RefinedPredicateException)) }
}

interface PositiveInt<F> : Refinement<F, Int> {
  override fun Int.refinement(): Boolean = this >= 0

  fun Int.positive(): Kind<F, Int> = refine(this)
} 

// Usage

val validResult = 0.positive() // Valid(0)
val invalidResult = (-1).positive() //Invalid(e=NonEmptyList(all=RefinedPredicateException))
```

**Comment by Cotel** [comment]
@raulraja @pakoito

**Comment by raulraja** [comment]
I think the type class approach will end up giving us less boilerplate and we already have a strategy to mix in operators for numeric types etc... They are not incompatible together either. We can have both. Generic behaviors and extensions to be projected in type classes. Special new types that we want to wrap go as inline classes.
```
class PositiveInt private constructor(val value: Int) { ... }
interface PositiveIntRefinement<F> : Refinement<F, PositiveInt> 
```

**Comment by pakoito** [comment]
`PositiveInt` was added in 1.3, it's called UInt.

**Comment by Cotel** [comment]
The only con I see in that approach is that you need to be inside the scope of `PositiveIntRefinement` for creating `1.positiveInt()` isn't it?

**Comment by raulraja** [comment]
@Cotel Nope, since Arrow 0.8.0 we export all type class functions and project them automatically downcasting as package functions over the data type as receiver.

**Comment by raulraja** [comment]
The validation and refinement libraries can go on the same module. One is more oriented to new typing and the other for data validation in general but I foresee being able to use refinement predicates as validation rules that can run through the Applicative Error

**Comment by Cotel** [comment]
Perfect then 👌, could we also offer a `positiveInt(1)` top function as well or something like that for the types we provide?

**Comment by Cotel** [comment]
> Yes whatever you want to add in the type class will get exported adapted
> 
> ```kotlin
> interface PositiveInt<F> : Refinement<F, Int> {
>   override fun Int.refinement(): Boolean = this >= 0
> 
>   fun Int.positive(): Kind<F, Int> = refine(this)
> 
>   fun positive(n:Int): Kind<F, Int> = n.positive()
> } 
> 
> positive(1) == 1.positive()
> ```

It tells me that both definitions has the same JVM signature and they clash.

Also, I have a basic `NonZero` implementation but I've been checking types provided by Scala's `refined` and I would want to implement `Less` for example. I have defined NonZero like `NonZero<F, A : Number> : Refinement<F, A>`. For the `Less` refinement I will need `A` to have comparison operations. Would it be okay if I request a `Order<A>` in the interface?

```kotlin
interface Less<F, A : Number> : Refinement<F, A> {
  
  fun ORD(): Order<A>
  fun max(): A

  override A.refinement() : Boolean = ORD().run { lt(max()) }

  // I don't really like this name because it depends on the instance to define the "less than x"
  // I can't give any hint with the name of the function.
  fun A.less(): Kind<F, A> = refine(this)

}
```

**Comment by raulraja** [comment]
I think it's time you put it up in a PR and we can all work of a branch as we shape it's original design. I can reply to both of your comments below but would be easier just to jump and fix it.
1. Which is the clash?, the class name or the positive method names?
2. Yes, each type class can depend in other type classes it needs to operate. The concretion can provide the order instance accordingly.
