### ISSUE TITLE
Clean Typeclass reassignations for instances

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#1104]
On #1043 I needed to add an instance to the Kleisli hierarchy and found out that we were reassigning typeclass constraints at each one of the instance hierarchy levels, adding more boilerplate over and over. Looking at typelevel/cats, instances just override the parent constraint and loose it a bit reducing it's constraints to the new level. So you'd have:

```kotlin
@extension
interface KleisliFunctorInstance<F, D> : Functor<KleisliPartialOf<F, D>> {

  fun FFF(): Functor<F>

  /.../
}


@extension
interface KleisliApplicativeInstance<F, D> : Applicative<KleisliPartialOf<F, D>>, KleisliFunctorInstance<F, D> {

  override fun FFF(): Applicative<F>
  /.../
}

@extension
interface KleisliMonadInstance<F, D> : Monad<KleisliPartialOf<F, D>>, KleisliApplicativeInstance<F, D> {

  override fun FFF(): Monad<F>

  /.../
}

```
So on each level you override the constraint from parent and constraint it to a more accurate typeclass. That makes the code cleaner and easier to reason about.

The only problem on doing that is that there was some collision somewhere in the generated code that wasn't liking the `FF()` name, so I moved it to be `FFF()` and then everything started working good. I'd probably move on this direction rather than doing the reassignation we're doing in other places. The idea would be to go through the whole codebase applying this approach where it's not being used.

**Comment by raulraja** [comment]
This approach won't work with the `@extension`processor since in some cases it can't walk up the hierarchy. The `@extension` requires each instance that can be made concrete to declare as abstract functions whatever dependencies it needs to be injected in the constructor of factories and static methods that are projected as part of the data types syntax. It could be reworked to work like this but I think it would require substantial changes to the way the code gen happens and how things are inspected with the reflection and metadata api's.

**Comment by JorgeCastilloPrz** [comment]
🤔How is it working good for Kleisli with a bunch of hierarchy levels of inheritance?

**Comment by raulraja** [comment]
@JorgeCastilloPrz by providing a new name for the new constrain and satisfying the parent unfulfilled constraints delegating to the new more powerful one like in the Kleisli instances below:
```kotlin
@extension
interface KleisliFunctorInstance<F, D> : Functor<KleisliPartialOf<F, D>> {

  fun FF(): Functor<F>

  override fun <A, B> Kind<KleisliPartialOf<F, D>, A>.map(f: (A) -> B): Kleisli<F, D, B> = fix().map(FF(), f)
}

@extension
interface KleisliContravariant<F, D> : Contravariant<Conested<Kind<ForKleisli, F>, D>> {
  override fun <A, B> Kind<Conested<Kind<ForKleisli, F>, D>, A>.contramap(f: (B) -> A): Kind<Conested<Kind<ForKleisli, F>, D>, B> =
    counnest().fix().local(f).conest()

  fun <A, B> KleisliOf<F, A, D>.contramapC(f: (B) -> A): KleisliOf<F, B, D> =
    conest().contramap(f).counnest()
}

@extension
interface KleisliApplicativeInstance<F, D> : Applicative<KleisliPartialOf<F, D>>, KleisliFunctorInstance<F, D> {

  fun AF(): Applicative<F>

  override fun FF(): Functor<F> = AF()

  override fun <A> just(a: A): Kleisli<F, D, A> = Kleisli { AF().just(a) }

  override fun <A, B> Kind<KleisliPartialOf<F, D>, A>.map(f: (A) -> B): Kleisli<F, D, B> =
    fix().map(AF(), f)

  override fun <A, B> Kind<KleisliPartialOf<F, D>, A>.ap(ff: Kind<KleisliPartialOf<F, D>, (A) -> B>): Kleisli<F, D, B> =
    fix().ap(AF(), ff)

  override fun <A, B> Kind<KleisliPartialOf<F, D>, A>.product(fb: Kind<KleisliPartialOf<F, D>, B>): Kleisli<F, D, Tuple2<A, B>> =
    Kleisli({ AF().run { fix().run(it).product(fb.fix().run(it)) } })
}

@extension
interface KleisliMonadInstance<F, D> : Monad<KleisliPartialOf<F, D>>, KleisliApplicativeInstance<F, D> {

  fun MF(): Monad<F>

  override fun AF(): Applicative<F> = MF()

  override fun <A, B> Kind<KleisliPartialOf<F, D>, A>.map(f: (A) -> B): Kleisli<F, D, B> =
    fix().map(MF(), f)

  override fun <A, B> Kind<KleisliPartialOf<F, D>, A>.flatMap(f: (A) -> Kind<KleisliPartialOf<F, D>, B>): Kleisli<F, D, B> =
    fix().flatMap(MF(), f.andThen { it.fix() })

  override fun <A, B> Kind<KleisliPartialOf<F, D>, A>.ap(ff: Kind<KleisliPartialOf<F, D>, (A) -> B>): Kleisli<F, D, B> =
    fix().ap(MF(), ff)

  override fun <A, B> tailRecM(a: A, f: (A) -> KleisliOf<F, D, Either<A, B>>): Kleisli<F, D, B> =
    Kleisli.tailRecM(MF(), a, f)

}

@extension
interface KleisliApplicativeErrorInstance<F, D, E> : ApplicativeError<KleisliPartialOf<F, D>, E>, KleisliApplicativeInstance<F, D> {

  fun AE(): ApplicativeError<F, E>

  override fun AF(): Applicative<F> = AE()

  override fun <A> Kind<KleisliPartialOf<F, D>, A>.handleErrorWith(f: (E) -> Kind<KleisliPartialOf<F, D>, A>): Kleisli<F, D, A> =
    fix().handleErrorWith(AE(), f)

  override fun <A> raiseError(e: E): Kleisli<F, D, A> =
    Kleisli.raiseError(AE(), e)

}

@extension
interface KleisliMonadErrorInstance<F, D, E> : MonadError<KleisliPartialOf<F, D>, E>, KleisliApplicativeErrorInstance<F, D, E>, KleisliMonadInstance<F, D> {

  fun ME(): MonadError<F, E>

  override fun MF(): Monad<F> = ME()

  override fun AE(): ApplicativeError<F, E> = ME()

  override fun AF(): Applicative<F> = ME()

}
```

**Comment by JorgeCastilloPrz** [comment]
Sorry, I think I didn't explain myself properly. I wanted to mean I used "my approach" on the Kleisli in Bracket PR already, and it's working good. The only caveat was the need to rename FF() to FFF() due to a conflict found in generated code.

**Comment by raulraja** [comment]
Closing this outdated issue as we no longer have this processor, thanks @JorgeCastilloPrz!
