### ISSUE TITLE
How to get rid of the ExtensionsDSLDeprecated warning in Arrow 0.8.0?

### ISSUE THREAD

**Issue by juxeii** [arrow-kt/arrow#1107]
Hi, 
I get an `ExtensionsDSLDeprecated` warning on this code with Arrow 0.8.0:
```
private fun subscribeNextHandler(orderEvents: Observable<OrderEvent>) =
    ForState<Queue<OrderEventHandlerData>>() extensions {
        binding {
            removeCurrentHandler().bind()
            val b = subscribeTopOfQueueHandler(orderEvents).bind()
            b
        }.fix()
    }
```
What is the correct way to get rid of this warning?
I tried
```
private fun subscribeNextHandler2(orderEvents: Observable<OrderEvent>) =
    State.monad<Queue<OrderEventHandlerData>> {
        removeCurrentHandler().bind()
        val b = subscribeTopOfQueueHandler(orderEvents).bind()
        b
    }
but this does not compile.
I am an absolute beginner with Arrow and the deprecation information does not tell me much.
Thx for help.
```

**Comment by pakoito** [comment]
In 0.8.0, you do `State.monad<Queue<OrderEventHandlerData>>().binding {`. In 0.8.1 it should just be `binding` and importing the function from the right package.

**Comment by pakoito** [comment]
Yes, your solution sounds correct.

**Comment by juxeii** [comment]
So, is StateApi preferrable to your solution? How do I get rid of the compiler errors?

**Comment by pakoito** [comment]
`StateApi` is an intermediate helper where to put these instances. I forgot that we had to do it because we describe State as a specialization of StateT.
