### ISSUE TITLE
Enable Playgrounds on all docs code snippets

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow#1121]
For playgrounds to work most snippets in the site need to be modified to conform with the playgrounds format.
In places where before we had:
```
` ` `kotlin:ank
Option(1).query {
    select { this * 10 }
}.value() 
` ` `
```
Now we need to provide explicit imports supporting the code inside `main` and the comments as ilustrated in the example below.
```
{: data-executable='true'}
` ` `kotlin:ank
import arrow.core.Option
import arrow.aql.instances.option.select.*

fun main(args: Array<String>) {
//sampleStart
val result: Option<Int> =
  Option(1).query {
    select { this * 10 }
  }.value()
//sampleEnd
println(result)
}
` ` `
```
This needs to be done and tested for all the different code snippets.
There may be places like in the Error Handling tutorial where the docs are not showing api's but an actual tutorial style that grows in complexity from top to bottom. In those cases, not all code snippets and declarations need to be runnable.

**Comment by calvellido** [comment]
In case of docs in that _tutorial_ style of accumulating code through different snippets, the Arrow Playground offer a mode called `incremental` that can be used in case it fits.

`{: data-executable='incremental'}`

This will make the current snippet code to be added to the code of the previous snippets, extracting imports and placing them at the top. Additionally this mode will wrap the executable code in a custom main function, printing the result of that complete snippet. Something like this:

```js
// All fetched imports from current and previous snippets

fun main(args: Array<String>) {println({
  /*
  All previous snippets code
  */
  /*
  Current snippet code
  */
}())}
```

**Comment by calvellido** [comment]
Hi, does this still makes sense even if we are targeting to generate most of the docs through Dokka?

**Comment by raulraja** [comment]
We have a new ank directive to make them executable that does not require kramdown directives
