### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#1149]
We've had a couple of questions like "what's a Kind?", "What's a witness type"?, "What's a type constructor"? that made me think about the idea of having a super simple glossary with terms and meanings in the docs. Would it make sense? [This is the one available in cats](https://typelevel.org/cats/nomenclature.html).

**Comment by JorgeCastilloPrz** [comment]
thoughts @raulraja @pakoito @truizlop @nomisRev ?

**Comment by truizlop** [comment]
I am totally up for that. I think we can start with a simple list of questions / terms and get them answered. Probably, since we have new members / users coming with questions, those can be used for such list.

**Comment by pakoito** [comment]
Updating this one then? https://arrow-kt.io/docs/patterns/glossary/

**Comment by JorgeCastilloPrz** [comment]
Aaaalright that happens when you don't take a look first before creating the issues :D. I guess than one should work, we should probably just include the terms still not there.

**Comment by raulraja** [comment]
Closing as this was removed from the Arrow docs a while back
