### ISSUE TITLE
DeferredK memoizes its result

### ISSUE THREAD

**Issue by 1Jajen1** [arrow-kt/arrow#1156]
DeferredK implements the MonadDefer which has a law stating its results should not be memoized. Kotlinx coroutines Deferred (which most of DeferredK delegates to) however does not follow this.

See #1150 for some discussion and I think @pakoito had some ideas as well on how to solve this.

Please also re-enable the law once done :)

**Comment by pakoito** [comment]
I've given Jorge and Simon the context and the prototype for the new Deferred architecture :D

**Comment by JorgeCastilloPrz** [comment]
Thanks for the issue. We'll take a look at this, not sure if it can happen before Q1 though, we really wanna finish the other effects blockers first.

**Comment by pakoito** [comment]
Note that we can fix this #1131 in one go too :D

**Comment by 1Jajen1** [comment]
Closed by #1157
