### ISSUE TITLE
Using binding as in docs generates deprecation warning

### ISSUE THREAD

**Issue by dhoepelman** [arrow-kt/arrow#1167]
[The docs for using `Try`](https://arrow-kt.io/docs/patterns/error_handling/#try) give the following example:

```
        ForTry extensions {
            binding{
                val nuke = arm().bind()
                val target = aim().bind()
                val impact = launch(target, nuke).bind()
                impact
            }.fix()
        }
```

`extensions` gives a deprecation warning here:
```
Since Arrow 0.8.0 ForX extensions {...} is deprecated in favor of direct extensions access via type class projections.
Import the syntax functions directly that have been projected for your data type instances
```

As someone who doesn't know arrow the deprecation message is not useful because it doesn't help me fix the warning. Can the deprecation warning be augmented to point to the docs that show how importing projected syntax functions can be done?

What is the correct way to write this in 0.8.0+? Can I help fix the docs?

**Comment by raulraja** [comment]
@dhoepelman yes, binding is a top level function now in most data types that support Monad.
That same code without the `ForTry extensions` part can be accomplished by importing `import arrow.instances.try.monad.binding`. Feel free to send a PR to fix the docs and ping me for review.

**Comment by dobrowins** [comment]
@raulraja As I see it's already resolved (at least in Try portion of docs), wonder if this issue could be closed not to span attention from those really needing work on.

**Comment by pakoito** [comment]
Agreed! Thanks :D
