### ISSUE TITLE
Question: how to save a state monad for later use

### ISSUE THREAD

**Issue by juxeii** [arrow-kt/arrow#1168]
Hi,

I'm gradually porting a project to a more functional style using arrow.
Gradually since I'm a beginner and want to grasp the concepts one by one.
Now I'm at the state monad and I don't know what is the canonical way to save the state between subsequent functions calls.
Suppose I have a function
`fun <S,T> someFunc():State<S,T>`
and this gets called from a 3rd party library repeadately. The functions alters some state and returns the new state.
But how can I save the new state for the next call to  `someFunc`.
I thought of some variable which holds the state and then saves the new state like this(pseudocode):
```
var someState: State<S,T>
someState = someFunc().run(someState)
```
The place where this assignment occurres is obviously not side-effect free.
Is this a good approach? What are the alternatives?
I don't see how to get around the problem of saving the state between the function calls.

**Comment by pakoito** [comment]
@raulraja StateT, WriterT and the rest weren't generated in the API docs. Do we need to include everything inside data?

**Comment by raulraja** [comment]
@pakoito they are generated, they seem to be missing an entry in the menu though https://arrow-kt.io/docs/apidocs/arrow-data/alltypes/index.html

**Comment by pakoito** [comment]
Done!
