### ISSUE TITLE
Allow Either to have a filter function that allows for the value to be used in the 'default' case

### ISSUE THREAD

**Issue by mikezx6r** [arrow-kt/arrow#1179]
This is very helpful if the Either and `filterOrElse` is being used for validation like processing.

Currently, one needs to do this

```
val someValue = getTheProperty()
someValue.right()
.filterOrElse( {it.length == 12},{MyError("some message with context: ${someValue.length}") })
```

The proposal (after discussion on Slack) is to introduce a new function as below:

```
inline fun <A, B> EitherOf<A, B>.filterOrOther(predicate: (B) -> Boolean, default: (B) -> A): Either<A, B> =
  flatMap { if (predicate(it)) Right(it) else Left(default(it)) }
```

This will allow for the example at top to be rewritten as

```
someValue.right()
.filterOrOther({it.length == 12}, {Error("some message with context: ${it.length}")})
```

I will be creating a PR for this later today.

**Comment by pakoito** [comment]
I believe this has been merged already? Closing!
