### ISSUE TITLE
Optics invalid code generation

### ISSUE THREAD

**Issue by Octogonapus** [arrow-kt/arrow#1211]
I have this code:
```kotlin
@optics
data class Gist(
    val gitUrl: String,
    val description: String
) {
    companion object
}

@optics
data class GistFile(
    val gist: Gist,
    val filename: String
) {
    constructor(gitUrl: String, filename: String) : this(Gist(gitUrl, ""), filename)
    companion object
}
```

Optics generates this code for `GistFile`: https://pastebin.com/ht7wNJFm
The compiler error I get is, "Error:(16, 21) Kotlin: Cannot find a parameter with this name: `gitUrl`". It seems like Arrow is generating code one level deeper than `GistFile` (it's generating `GistFile.gitUrl`).

I am using Arrow version `0.8.1`, Kotlin version `1.3.11`, and JDK version `1.8.0_181`.

**Comment by pakoito** [comment]
Silly question, can you please try moving the classes to separate packages, and report what happens?

**Comment by nomisRev** [comment]
This is a bug in the annotation processor. It's using the secondary constructor instead of the primary constructor to generate the Optics.

Thanks for reporting :+1:

**Comment by Octogonapus** [comment]
Thanks, @nomisRev, you are right. I moved the secondary constructor to a method in the companion object and the generated code is correct.
