### ISSUE TITLE
Links to Datatypes in documentation are broken

### ISSUE THREAD

**Issue by plastic-karma** [arrow-kt/arrow#1216]
Links in datatype section lead to a 404 page. Examples: 

- https://arrow-kt.io/docs/optics/each/ and click on Either, Option or Try in "Data Types" section
- https://arrow-kt.io/docs/arrow/data/nonemptylist/ and click Count, From, GroupBy, OrderBy, Select, Sum, Union or Where in "Supported type classes" section

Looks like this was introduced here: https://github.com/arrow-kt/arrow/commit/65e429ed69a5bfc9f545448878d73d0b109802cf#diff-ac1055e539fc7416bcb38e06d25eb530R51

**Comment by pakoito** [comment]
They're all broken lol It looks like a config issue, they should be back soon :)

**Comment by pakoito** [comment]
Thank you for the contribution! They seem to be working again 💛
