### ISSUE TITLE
Configure Google Analytics in the docs site

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1218]
We've currently lost all signals for traffic and referrals on Analytics. I check them regularly to see who's talking about us, and provide support where needed :D

See #482 for the original configuration.

**Comment by jorgegalindocruces** [comment]
Hi there folks,

@calvellido here you have the code for adding to the head with the tracker

`
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-18433785-18"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-18433785-18');
</script>
`

Cheers!
