### ISSUE TITLE
Formatting issue on data type generated docs

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#1228]
On data type docs the extension functions section is completely unreadable at the moment. [Example](https://arrow-kt.io/docs/apidocs/arrow-core/arrow.core/-either/index.html#extension-functions)

Can we do something to fix this @israelperezglez?

**Comment by AdrianRaFo** [comment]
There was some `*` on the Either and Try doc causing a bad format because was interpreted as a list

**Comment by pakoito** [comment]
There's some extra padding around links that hinder readability, at least in my machine.
