### ISSUE TITLE
Update Ank docs

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#1236]
Looks like the executable code snippets are now enabled with `ank:playground` instead of `{: data-executable='true'}` followed by `kotlin:ank`, so we should update Ank docs to reflect that. Actually, looks like we've never added details about runnable snippets there, so it's a good time to do so.

Also add docs there for how to use `:extension` and the `instatiation_factory` to project executable snippets into the data types providing an instance of a required typeclass. More information on how to do it on #1237 and specially [this comment](https://github.com/arrow-kt/arrow/pull/1237#issuecomment-455172773) from @nomisRev .

Ank docs can be found [here](https://github.com/arrow-kt/arrow/blob/master/modules/ank/README.md).

**Comment by kostya05983** [comment]
@raulraja, @JorgeCastilloPrz  I have a question about documented runnable snippets, if I make an example of snippet and how it will look on site(picture), is it enough for user to understand? How do you think?

**Comment by raulraja** [comment]
@kostya05983 the bulk of this task is going over all the docs module replacing ocurrences of `{: data-executable='true'}` for `kotlin:ank:playground`. There is more after that but this is what we need for this issue.

**Comment by kostya05983** [comment]
@raulraja  Can you give me a guide, How I can make a changes, I try to create a new branch to make a pull request, but I don't have a permissions.

**Comment by kartoffelsup** [comment]
@kostya05983 you have to fork this repository first by clicking on `Fork` on the top right, and then you can create a new branch in your fork.

**Comment by kostya05983** [comment]
Thank you
