### ISSUE TITLE
["Request"] Sugar for switching context back after Concurrent#parMapN

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#1269]
### What version are you currently using?

0.9.0-SNAPSHOT

### What would you like to see?

Right now, something like this switches to the passed in context, never switches back for the `callback` results:
```kotlin
IO.concurrent().parMapN(
            Dispatchers.IO,
            useCase1.run(params1),
            useCase2.run(params2),
            useCase3.run(params3)
        ) { a, b, c ->
            callback(a, b, c)
        }.fix().unsafeRunAsync {}
```

That's good for bindings, since you can ensure the context after the call is the one you explicitly passed in, and you can keep stacking computations in the thread / context. Then you can manually switch the context back to `Main` or the one you're interested in to process the final results:

```
IO.concurrent().run {
            binding {
                val (a, b) = parMapN(
                    backgroundContext,
                    useCase1.run(params1),
                    useCase2.run(params2),
                    ::Tuple2
                ).bind()
                delay(mainContext) { callback(a, b) }.bind()
            }.fix().unsafeRunAsync {}
        }
```

That makes the API quite explicit, so sounds good. But for cases where you're not interested on stacking any computations, but just launch 3 comps and get results back on your current thread, it's a bit too verbose (IMHO).

My concern is that it's a **really** usual scenario that you want your results in the thread you were right before the call (android is a good example). 

### My suggestion

I was mostly thinking about adding a new `parMapN` overload that allows to **explicitly** pass in both the computation and the result contexts:

```kotlin
parMapN(
     computationCtx = Dispatchers.IO,
     resultCtx = Dispatchers.Main,
     fa = useCase1.run(params1),
     fb = useCase2.run(params2),
     f = ::callback)

//or

val (a, b) = parMapN(
     computationCtx = Dispatchers.IO,
     resultCtx = Dispatchers.Main,
     fa = useCase1.run(params1),
     fb = useCase2.run(params2),
     f = ::Tuple2)
```

This is something I've been discussing with @nomisRev a bit today. He's more in the line of keeping everything cleaner since `Concurrent` public API is a bit bloated already. I definitely understand that, I'm more in the opinion that we would do good providing some sugar alternatives to to the end user. It's more a matter of good namings for the params, and it should be pretty straightforward.

Thoughts?

**Comment by pakoito** [comment]
You can write the sugar function for your client code that does the packing and unpacking of the tuple to change contexts. I'm not sure this one is for the core library.

**Comment by JorgeCastilloPrz** [comment]
No problem at all on opening a PR, once it's discussed and in case there's an agreement.

As described in the issue, yes, you can jump context manually from within a binding. This is not a limitation but a suggestion for a very usual case in real world apps.

I'm not sure what you mean by relying on EmptyCoroutineContext. Both dispatchers are passed in explicitly in the call site, so you just do the context switch to those inside Arrow where corresponds: parMapN(ioCtx, myCurrentCtx, ...)

I assume we can call continuation on the right context on completion

**Comment by pakoito** [comment]
The problem is that kx.coroutines doesn't have a concept of "this thread", and you cannot even reuse the current context sometimes. So all you can do is jump from a background thread to a main thread and viceversa, because they have named dispatchers.

Now, your assumption is that 

```
parMapN(
            Dispatchers.IO,
            useCase1.run(params1),
            useCase2.run(params2),
            useCase3.run(params3)
```

Runs useCase1-3 in a background thread and then you'll have to come back to a main thread. The thing to understand is that they do because they're set to not have a CoroutineContext, that is, they default to an EmptyCoroutineContext which means they're run on whichever context starts them.

What you're trying to achieve is more correctly done by starting each use case on a background dispatcher and then using Dispatchers.Main as the one you pass.

Because we're not aiming for the correct approach but rather the easiest one to write, we have two options. On one hand we rewrite `parMap` to have an optional `resultCtx` parameter that defaults to staying on the same thread:

```
parMap(computationCtx, resultCtx= EmptyCoroutineContext, fa, fb, f) =
  parMap(computationCtx, fa, fb, ::Tuple2).continueOn(resultCtx).map { (a, b) -> f(a, b) }  
```

which on the callsite looks like

```
parMap(Dispatchers.IO, fa = case1, fb = case2, f = { ... })
```

and because of named parameters with defaults we lose the syntactic sugar for functions, plus the extra verbosity.

So instead the other option is to have a new function alias

```
parMap(computationCtx, resultCtx, fa, fb, f) =
  parMap(computationCtx, fa, fb, ::Tuple2).continueOn(resultCtx).map { (a, b) -> f(a, b) }
```

or even

```
parMap(computationCtx, resultCtx, fa, fb, f) =
  parMap(resultCx, delay(computationCtx) { fa }, delay(computationCtx) { fb }, { (a, b) -> f(a, b) })
```

that has to be written for all arities. Even if it's common *on android apps* it feels more like a pattern than a core combinator, which can live in an app codebase.

**Comment by JorgeCastilloPrz** [comment]
Wait, what? I thought each passed in computation started on its own thread for paralellization (a different thread inside the ctx pool). I know this is opinionated, but I'd not want to mix use cases with threading, I see that as a smell. To me, they should not know anything about that but just contain strict business logic. Then we've an Invoker taking care of running them paralelly, sequentially, or whatever we need. And that's where I call parMapN. 

Summarizing, my use cases are just IO{} deferred but sync and blocking computations. (i.e: `IO { service.fetchFromNetwork().flatMap { /* someBusinessLogic */ }}`)

Isnt it correct that parMapN runs all the tasks in the Context passed but **not** on the same thread all of them? The ctx is a pool. Isn't it paralleling on different threads by default, or are we explicitly awaiting for the result of each one to start the next one?

About this:
"The problem is that kx.coroutines doesn't have a concept of "this thread", and you cannot even reuse the current context sometimes. So all you can do is jump from a background thread to a main thread and viceversa, because they have named dispatchers".

This is precisely why I suggested to pass the result context explicitly. Since you're running the tasks in the passed in ctx, I assume you can explicitly jump back to the result ctx also passed in afterwards, instead of automatically detecting the current thread or anything.

**Comment by pakoito** [comment]
@nomisRev on your example, which thread is Tuple2 called in? I'd imagine that in the one for the last IO that finishes, right?

**Comment by nomisRev** [comment]
@pakoito yup, that's right

**Comment by pakoito** [comment]
>I assume you can explicitly jump back to the result ctx also passed in afterwards

There is no "this thread I'm currently on" context in kx.coroutines, the way that Schedulers.trampoline() or the old Schedulers.immediate() existed in rx. Getting the context from the scope may lead you to context reuse when starting multiple coroutines, which isn't allowed.

It is not intuitive for us either, we've built the knowledge via experimentation lol

**Comment by JorgeCastilloPrz** [comment]
Mmm but If I explicitly pass the context to you from the call site, let's say `Main` (because I'm the dev and I know I'm on Main and do want my results on Main), can't you just jump to it whenever you have your results ready ? I'm sorry I'm asking so much about this, but not understanding the real point of the "current thread thing". I know that's not possible, but it's not what I'm looking for (I think). I'd not like arrow to detect contexts for me under the hood, but be explicit about those by myself (the same way we already are for the context we currently require to be passed in). Why would you need the "current thread" concept, if I'm explicitly passing the context I want you to jump to?

**Comment by pakoito** [comment]
If you are that's okay, just do 

```
binding {
                val (a, b) = parMapN(
                    backgroundContext,
                    useCase1.run(params1),
                    useCase2.run(params2),
                    ::Tuple2
                ).bind()
                continueOn(Main)
                ...
```

**Comment by JorgeCastilloPrz** [comment]
I know there are ways to do this, I also added some working alternatives to the issue description in the beginning. All of them seem to require a binding though, which is less than ideal. 

Anyways, we'll keep the extension in our codebase for now.
