### ISSUE TITLE
IO.asyncFiber

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1292]
Rename `asyncF`

https://github.com/arrow-kt/arrow/blob/master/modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/IO.kt#L47

**Comment by JorgeCastilloPrz** [comment]
Some description pls?

**Comment by pakoito** [comment]
Oh, just literally renaming startF to startFiber, as I know Raul was doing it through the codebase.

**Comment by JorgeCastilloPrz** [comment]
Yup Imagined something like that but, reasons for the change? Better reasoning on issue descriptions is always helpful.

**Comment by pakoito** [comment]
Completed!
