### ISSUE TITLE
Docs version selector

### ISSUE THREAD

**Issue by calvellido** [arrow-kt/arrow#1309]
We need to implement a version selector between different published Arrow versions to consult on the website:

https://0-8-2.arrow-kt.io
https://arrow-kt.io
(...)
https://next.arrow-kt.io

**Comment by AntonioMateoGomez** [comment]
For this issue we have thought about incorporating in the home section three buttons to choose wich doc version we need to consult, so we will see the `STABLE`, `NEXT` and `PREVIOUS` version. 
It would may looks like this:

![captura de pantalla 2019-02-25 a las 12 22 01](https://user-images.githubusercontent.com/25897490/53334205-63dd4080-38f8-11e9-828e-4283164c22a9.png)

We will also incorporate a button selector in the doc section placed in the sidebar area.
Besides we think It would be a good idea adding an indicator or alert that tells the user when it isn´t in the stable version.

@israelperezglez will be reviewing the design so we make sure that the style will be on the same arrow line.

**Comment by raulraja** [comment]
The `Learn More` should go away. The buttons should not just say that but also include the version number. There needs to be visual clues to differentiate the three versions being in order of prominence:
- stable

**Comment by pakoito** [comment]
I'd rather we had version number in or below the buttons too.
