### ISSUE TITLE
Android Proguard warning on StateT when updating from 0.8.0 to 0.8.2

### ISSUE THREAD

**Issue by kylannjohnson** [arrow-kt/arrow#1317]
I updated tge arrow version from 0.8.0 to 0.8.2 on our Android app and proguard gave this warning about StateT.kt

```
Warning: arrow.data.StateT$Companion$modify$1$1$1: can't find referenced class arrow.data.StateT$Companion$modify$1$1
Warning: arrow.data.StateT$Companion$modify$1$1$1: can't find referenced class arrow.data.StateT$Companion$modify$1$1
Warning: arrow.data.StateT$Companion$tailRecM$1$1$1$1: can't find referenced class arrow.data.StateT$Companion$tailRecM$1$1$1
Warning: arrow.data.StateT$Companion$tailRecM$1$1$1$1: can't find referenced class arrow.data.StateT$Companion$tailRecM$1$1
Warning: arrow.data.StateT$Companion$tailRecM$1$1$1$1: can't find referenced class arrow.data.StateT$Companion$tailRecM$1$1$1
```

We do not use the State type at all so I was surprised to see any change here.  We ignored the warning for now, but would love to see if we could configure proguard to not require suppressing the warnings.

We are running: Kotlin 1.3.21, min sdk 23, JRE 1.8.0_162

**Comment by pakoito** [comment]
This seems like a build issue in Kotlin, we're seeing it pop up on arbitrary classes from time to time :/

**Comment by pakoito** [comment]
Try again in 0.9.0, see if it still persists

**Comment by aballano** [comment]
@kylannjohnson Please feel free to comment or re-open the issue if you still face that problem again.

**Comment by JorgeCastilloPrz** [comment]
Thanks
