### ISSUE TITLE
handleErrorWith for Either

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1324]
Add it to Either.kt as a member function. It's currently defined inline in the instance so it's a case of copypasting it :D

https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-core-extensions/src/main/kotlin/arrow/core/extensions/either.kt#L92-L98

**Comment by kioba** [comment]
I am happy to take it, I will set up the project and finish on the weekend

**Comment by pakoito** [comment]
Thanks @kioba for the fixxxx

**Comment by kioba** [comment]
Thank you for letting me contribute! :)
