### ISSUE TITLE
Artifact audit

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#1333]
# What's needed

We're approaching release `0.9.0`, it's time to ensure all artifact names match the new approach ( `****-data` + `****-extensions`). We must also double check that artifacts mentioned in README + "Quick start" docs section also match with those names. Also review which ones are missing, if there are any.

## Audit results

The name on the left is the artifact name we're using in both README and Quick Start docs section. There's a ✅ in case both match with the name the artifact has in arrow codebase.

`arrow-core-data` :white_check_mark:
`arrow-core-extensions` :white_check_mark:
`arrow-syntax` :white_check_mark:
`arrow-typeclasses` :white_check_mark:
`arrow-extras` :boom: (should be `arrow-extras-data` ?)
`arrow-extras-extensions` :white_check_mark:
`arrow-meta` :white_check_mark:
`arrow-free`  -> :boom: it’s called `arrow-free-data`, should be updated in README and docs
`arrow-free-extensions` -> :white_check_mark:
`arrow-mtl` -> :white_check_mark:
`arrow-effects-data` -> :white_check_mark:
`arrow-effects-extensions` -> :white_check_mark:
`arrow-effects-io-extensions` -> :white_check_mark:
`arrow-effects-rx2-data` -> :white_check_mark:
`arrow-effects-rx2-extensions` -> :white_check_mark:
`arrow-effects-reactor-data` -> :white_check_mark:
`arrow-effects-reactor-extensions` -> :white_check_mark:
`arrow-effects-kotlinx-coroutines-data` -> :boom: where is the code?¿ remove leftovers in case we’re removing DeferredK and DeferredK extensions from Arrow
`arrow-effects-kotlinx-coroutines-extensions` -> :boom: where is the code?¿ remove leftovers in case we’re removing DeferredK and DeferredK extensions from Arrow
`arrow-optics` -> :white_check_mark:
`arrow-generic` -> :white_check_mark:
`arrow-recursion` -> :boom: it’s called `arrow-recursion-data`, we must rename it in both README and “Quick start” docs section.
`arrow-recursion-extensions` -> :white_check_mark:
`arrow-integration-retrofit-adapter` -> :white_check_mark:

## artifacts never mentioned in either README or docs Quick Start section

`arrow-query-language`
`arrow-kindedj`
`arrow-dagger`
`arrow-dagger-effects`
`arrow-dagger-effects-rx2`
`arrow-annotations`
`arrow-reflect`
`arrow-shadow`
`arrow-streams`
`arrow-validation`

Is it intended for all of them? should we mention any?

**Comment by pakoito** [comment]
>arrow-extras ✅ (should be arrow-extras-data ?)

yes

**Comment by pakoito** [comment]
So, in the end, we wanted a `-data` without the extensions and an `-extensions` with them, and no suffix for an artifact with both. Right now in some places instead of `-data` we have the no suffix, for example.

**Comment by pakoito** [comment]
I believe at some point we realised that `-extensions` and the no suffix one would be the same artifact, and that's why some of them are renamed or not.

I don't care whether we have 2 or 3 artifacts as long as it's consistent.
