### ISSUE TITLE
Add countdown-based `retry` for ApplicativeError

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1347]
Something like

```
fun <E, A> Kind<F, A>.retry(AE: ApplicativeError<F, E>, count: Int): Kind<F, A> = AE.run {
  handleErrorWith { withRetry(it, AE, count) }
}

fun <E, A> Kind<F, A>.withRetry(err: E, AE: ApplicativeError<F, E>, retries: Int): Kind<F, A> =
  if (retries == 0) AE.raiseError(err)
  else AE. run { this.handleErrorWith { withRetry(it,AE, retries - 1) } }
```

It needs to be tested in ApplicativeErrorLaws for stackoverflow. If it SOs, then we can move it to MonadError and do another version based off `tailRecM`

**Comment by RivuChk** [comment]
I'd like to pick this up, will add the functions, perform the tests and if required will do the fixes as suggested.

**Comment by pakoito** [comment]
It may be part of MonadSuspend actually, because non-suspended functions are deterministic.

**Comment by 1Jajen1** [comment]
This can be closed as with schedules one can do any retry/repeat policy, including count based. Schedule only works on either `Concurrent` or `MonadError` + `Timer`, but as @pakoito noted above, only `MonadDefer` and above make sense. That measn one only needs a `Timer` for anything that is not `Concurrent` and implementing a timer (with or without delay) is rather trivial.
