### ISSUE TITLE
Missing uppper bound in the Option class and toOption extension method

### ISSUE THREAD

**Issue by alphaho** [arrow-kt/arrow#1358]
While Option means having something or nothing, it seems we should specify a `Any` upper bound to `Option` class and the `toOption` extension method.

At the moment, the type parameters are with no upper bounds:

```kotlin
fun <T> T?.toOption(): Option<T> = this?.let { Some(it) } ?: None
```

```kotlin
sealed class Option<out A> : OptionOf<A>
```

I think they should be:

```kotlin
fun <T: Any> T?.toOption(): Option<T> = this?.let { Some(it) } ?: None
```

```kotlin
sealed class Option<out A: Any> : OptionOf<A>
```

If that should be the case, I'm happy to raise a pull request to fix this

**Comment by pakoito** [comment]
We decided very early in the lib that we don't really care about the contents of our datatypes. That means that if people want to put nullables inside Option they're entitled to. Even if that means that

```
val a: Option<Int?> = 1.toOption()
```

will _technically_ be the same as `Some<Int>`.

**Comment by knordbo** [comment]
It also means that we can do things like:
```
data class Foo(val bar: Any?)

val foo = Foo(null)
val bar = Option.just(foo).map { it.bar }
// bar is now Option with a null
```

yields Option of `value` null, whilst `isEmpty` states false. Is this desired?

**Comment by MarioAriasC** [comment]
Talking about Arrow's prehistory, (i.e., funKTionale) for a while we implemented an upper bound for `Option`, and it made it very, very difficult to use.

And `Option<Int?>` can have a null value inside 'cause the type `Int?` allows null values

**Comment by 1Jajen1** [comment]
Without an upper bound you decide based on your actions what should be in Option-Context, not the value inside. I think that is preferable because it makes Option much more flexible. The same goes for all HK-Types. They don't restrict the Type inside and they should not, because it limits functions trying to combine them. A function like `Either<L, R> -> Option<R>` (throwing away the error) becomes impossible because there is no bound on R (and there should never be).

**Comment by alphaho** [comment]
Sounds pretty reasonable. 
But would it make sense to provide an upper bound for the `toOption` function or the `fromNullable` function? Especially the `fromNullable` function, it feels like it would properly handle the nullable type as it has the `nullable` in the name, but getting something like an `Option<Int?>` seems to be counter-intuitive.

**Comment by pakoito** [comment]
`fromNullable` already does that unless you hint you want a non-nullable, right?

**Comment by alphaho** [comment]
yes, it would be nice if I can get an `Option<String>` when I call 

```kotlin
val blah: String? = null
Option.fromNullable(blah)
```

**Comment by pakoito** [comment]
you can!

<img width="439" alt="Screen Shot 2019-04-05 at 9 37 08 AM" src="https://user-images.githubusercontent.com/514871/55615081-69933500-5786-11e9-9356-9316ec2633d2.png">

**Comment by alphaho** [comment]
Aha! Thanks very much! That's exactly what I wanted in the first place! 
I wasn't aware that it can be used like this.
