### ISSUE TITLE
Docs with .MD extension (caps) fail to be edited

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1363]
Repro: 

Go to https://arrow-kt.io/docs/optics/index/
Click Edit on the top right
BROKEN LINK
Edit url from `.md` to `.MD`
Fixed!

Fix:
Rename all `.MD` files to `.md`

https://github.com/arrow-kt/arrow/blob/master/modules/docs/arrow-docs/docs/docs/effects/promise/README.MD
https://github.com/arrow-kt/arrow/blob/master/modules/docs/arrow-docs/docs/docs/optics/filterindex/README.MD
https://github.com/arrow-kt/arrow/blob/master/modules/docs/arrow-docs/docs/docs/effects/fiber/README.MD
https://github.com/arrow-kt/arrow/blob/master/modules/docs/arrow-docs/docs/docs/optics/index/README.MD
https://github.com/arrow-kt/arrow/blob/master/modules/docs/arrow-docs/docs/docs/optics/snoc/README.MD
https://github.com/arrow-kt/arrow/blob/master/modules/docs/arrow-docs/docs/docs/optics/cons/README.MD
https://github.com/arrow-kt/arrow/blob/master/modules/docs/arrow-docs/docs/docs/effects/ref/README.MD

**Comment by pedrovgs** [comment]
I'm fixing this one @pakoito 😃

**Comment by pakoito** [comment]
🎉
