### ISSUE TITLE
Unit return types

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#1386]
When you're writing code in an FP manner, you want to keep all effects under control. **Functions that return `Unit` are effectful by definition**, since otherwise they'd do nothing. On their bodies, they always access the external world, as in printing, logging, network queries, database reads / writes, modifying the value of class properties... etc. 

### Action points 
  
* [x] The redundant Unit return type is an IntellIJ IDEA Inspection. Unit return types are never redundant from an FP perspective, since they make function "referentially transparent". The function states what's it doing by looking at it's input and output types, so best thing we can do is to give feedback to Arrow users about how to disable it in README and "Quick start" docs section as also suggested for #1385. [Also include a link to the official intention action docs](https://www.jetbrains.com/help/idea/intention-actions.html). 

![Screenshot 2019-03-28 at 12 07 22](https://user-images.githubusercontent.com/6547526/55162811-e4e25e80-5168-11e9-8ed9-91fc6bc42f83.png)

* [ ] ~Apart from the IntellIJ IDEA Inspection, Ktlint also complaints about Unit return types regardless of where they're used. That's also something we could suggest users how to disable on their ktlint configurations, since from an FP perspective it's always important to declare return types regardless of what they are, so it's explicit that the function has side effects inside.~

**Comment by pakoito** [comment]
I'd suggest reaching out to twitter to see if someone is interested in owning this space.

**Comment by JorgeCastilloPrz** [comment]
@tylos will tackle this during next quarter.

**Comment by Tylos** [comment]
Opening PR to document how to disable the check for IDEA

Ktlint is still pending until certain rules can be disabled. It is currently in PR - https://github.com/pinterest/ktlint/pull/503

**Comment by JorgeCastilloPrz** [comment]
Yep it'd be nice if we can add an issue for it then create a Marlow goal. As soon as support for disabling global rules in ktlint it'll be an easy one to tackle.
