### ISSUE TITLE
Add community contributions guidance on the blog site

### ISSUE THREAD

**Issue by calvellido** [arrow-kt/arrow#1399]
In the [Arrow blog section](https://arrow-kt.io/blog/) we could add a small text advisory pointing to the ways anyone could contribute to that section.

Roughly, we could refer to the following two links:

_Do you want to add your contribution to this blog?  You can [directly do it yourself](https://github.com/arrow-kt/arrow/tree/master/modules/docs/arrow-docs#blog-section-contribution), or propose it in the [repo issues](https://github.com/arrow-kt/arrow/issues/new?assignees=MaureenElsberry&labels=Media+Resource&template=add-community-resource.md&title=[Add+Media]) and we will be adding it._

**Comment by raulraja** [comment]
tagging @MaureenElsberry for help with the message

**Comment by calvellido** [comment]
Completed in https://github.com/arrow-kt/arrow-media/pull/10 and available at https://github.com/arrow-kt/arrow-media
