### ISSUE TITLE
Move io-extensions from effects-extensions to io-effects-extensions

### ISSUE THREAD

**Issue by 1Jajen1** [arrow-kt/arrow#1401]
Right now the io-extensions (all its typeclass instances) are in `arrow-effects-extensions` and by the name i'd expect them in `arrow-io-effects-extensions`. Should those be moved? If so I can do that in a quick pr...

**Comment by raulraja** [comment]
Yes, we need to move them in a way that we can easily add the mpp support with expect and actual afterwards. Also ideally the final arrow-fx artifact includes also all the IO instances

**Comment by JorgeCastilloPrz** [comment]
Wait a minute. I've been using some instances from arrow-io-extensions already in 0.9.0 :thinking:. Are they split atm?

**Comment by 1Jajen1** [comment]
IO's instances are all in arrow-effects-extensions. That is the reason I created #1402 : `arrow-effects-io-extensions` has a dependency with `compile` on `arrow-effects-extensions`, so you are likely transiently depending on it. `arrow-effects-io-extensions` only has the `Dispatchers<ForIO>`, `Environment<ForIO>` and `Fx<ForIO>` instances. The rest are in `arrow-effects-extensions` afaik

**Comment by JorgeCastilloPrz** [comment]
Makes sense. Didn't notice that, thanks for the clarification!

**Comment by pakoito** [comment]
Those are separate because the dispatcher is JVM-only and we're eyeing multiplatform already.
