### ISSUE TITLE
Organize dependencies for modules

### ISSUE THREAD

**Issue by 1Jajen1** [arrow-kt/arrow#1402]
Currently all project dependencies are a bit of a mess, they either depend on too many other modules from arrow (more than needed) or transiently depend on modules rather than explicitly. That has two downsides: It somewhat destroys arrows modularity if a modules is overloaded with dependencies that are then "leaked" to the one using it by using `compile` over `implementation` and second it makes it annoying to depend on a library that uses arrow (like what is going to happen if the repo gets split, if that is still planned). This happens partially already with kotlintest: sometimes in writing tests IntelliJ fails to provide type-inference because it cannot choose between methods from kotlintest or arrow (it luckily still compiles, but it is really annoying).

What needs to be done:
- Redo all dependencies in each module
- replace the deprecated `compile` with either `api` (if we want to expose the dependency) or `implementation` if we want to hide it

This is basically a few hours of fighting the compiler, easiest solution is probably to start at `arrow-annotations` (for kinds) and move up starting with the project with the least dependencies (core -> extras -> ...)

If this is still open or still wanted in a few weeks I'll take it, I just don't have the time to do it now

**Comment by raulraja** [comment]
Closing this old issue, thanks @1Jajen1
