### ISSUE TITLE
Add functions alt, some and many to Alternative type class

### ISSUE THREAD

**Issue by juliankotrba** [arrow-kt/arrow#1410]
**Useful links**
* http://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Applicative.html#g:2
* https://blog.jle.im/entry/free-alternative-regexp.html

**Comment by juliankotrba** [comment]
I will try to create a PR in the next few days.

**Comment by Cotel** [comment]
Is this issue completed?

**Comment by juliankotrba** [comment]
Yes, still open I guess! Otherwise there should be a reference to someone's (draft) PR like yours 🙂
