### ISSUE TITLE
"Inject" docs lead to 404 page

### ISSUE THREAD

**Issue by jereksel** [arrow-kt/arrow#1412]
https://arrow-kt.io/docs/

Select "Type classes" -> "Inject"

**Comment by i-walker** [comment]
This is a known Issue. There are more Dead links like that. 
If you want you can make an PR for a markdown file and dokka will generate a html file. Eventually this link will lead to the generated html file.

Here is the file 
https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Inject.kt

But you should rather consider the response from @raulraja.

**Comment by raulraja** [comment]
`Inject` needs to be documented at the KDOC level in the same way `Functor` is documented today. https://arrow-kt.io/docs/apidocs/arrow-typeclasses/arrow.typeclasses/-functor/index.html
When Inject has a good description and code examples  the dokka and ank build steps will generate this page https://arrow-kt.io/docs/apidocs/arrow-typeclasses/arrow.typeclasses/-inject/index.html . 
A fix in the meantime is just editing the menu and having `Inject` point to that page for now or removing Inject all together from the docs for now until we have some decent docs.

**Comment by calvellido** [comment]
This has been fixed through #1836
