### ISSUE TITLE
parTraverse isn't always executing in parallel

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1414]
In this line https://github.com/arrow-kt/arrow/blob/ce539f2c807683eb937190dfcdb76ddd2db75cad/modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/typeclasses/suspended/FxSyntax.kt#L35 the `fa.map(f)` happens eagerly if the Kind isn't suspended.

**Comment by pakoito** [comment]
I've checked, it turns out NonBlocking uses the same thread for small payloads and it may look sequential

```
arrow.effects.IOTest > bla STANDARD_OUT
    ForkJoinPool-1-worker-1
    ForkJoinPool-1-worker-1
    ForkJoinPool-1-worker-1
    ForkJoinPool-1-worker-1
    ForkJoinPool-1-worker-2
    ForkJoinPool-1-worker-3
    ForkJoinPool-1-worker-3
    ForkJoinPool-1-worker-1
    ForkJoinPool-1-worker-1
    ForkJoinPool-1-worker-1
    ForkJoinPool-1-worker-3
    ForkJoinPool-1-worker-4
    ForkJoinPool-1-worker-4
```

**Comment by alexd6631** [comment]
Hello @pakoito,

I have made some tests with Arrow-Fx and tried to run some workload in parallel with parSequence/parTraverse but, in my case, it does not seem to run in parallel. 
The sample workload is implemented using coroutine delay, as I think it is representative of an non-blocking HTTP call. Same behavior is observed by switching to regular blocking Thread.sleep() calls.

In the code below, I also made a quick implementation of parSequence which starts a set of fibers and  join the results, achieving parallelism (~1sec to execute them all). However, Arrow parSequence seems to execute the tasks in a sequential, taking ~5secs to execute them all.

BTW, thank you for the great work on Arrow and Fx, it is great to have a principled effect system while having a lightweight and naturak Kotlin syntax.

```
package org.alexd.testfx

import arrow.effects.IO
import arrow.effects.extensions.io.fx.fx
import arrow.effects.fix
import kotlinx.coroutines.delay
import kotlin.coroutines.CoroutineContext

suspend fun putStrLn(s: String) { println(s) }

suspend fun getTime() = System.currentTimeMillis()

suspend fun work(name: String): String {
    println("Starting $name from ${Thread.currentThread()}")
    delay(1000)
    println("Done $name")
    return name
}

fun <A> CoroutineContext.myParSequence(tasks: List<IO<A>>): IO<List<A>> = fx {
    val fibers = tasks.map { !startFiber(it) }
    fibers.map { !it.join() }
}

fun <T> benchWork(name: String, f: () -> IO<T>) = fx {
    !effect { putStrLn("$name started") }
    val startTime = !effect { getTime() }
    val (res) = f()
    val duration = !effect { getTime() } - startTime
    !effect { putStrLn("$name ended ($duration ms)") }
    res
}

fun performWorkInParallel() = fx {
    val tasks = (0 until 5).map {
        effect { work("Task $it") }.fix()
    }

    !benchWork("myParSequence") {
        NonBlocking.myParSequence(tasks)
    }

    !benchWork("parSequence") {
        NonBlocking.parSequence(tasks).fix()
    }
}

fun main() {
    performWorkInParallel().unsafeRunSync()
}
```
