### ISSUE TITLE
Algolia is not indexing API Docs

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow#1415]
The current API docs are not searchable despite being deployed in the site. Algolia seems to not be indexing those and users are unable to find info about the api reference in our site.

**Comment by raulraja** [comment]
Originally reported in https://kotlinlang.slack.com/archives/C5UPMM0A0/p1555599684115900 //cc @lucmazon

**Comment by calvellido** [comment]
An Algolia maintainer explicitly removed the API docs results from the crawling a couple of months ago:

https://github.com/algolia/docsearch-configs/commit/e38b0dbb5f9993ed12e29d680f3329a4447e9b69

I'm assuming the reason should be that the API docs are too heavy to be crawled for free by them?  I'm not sure, I'll try to ask them.

**Comment by raulraja** [comment]
In that case we should consider a different option, we spent months on the docs and users are unable to find them with Algolia.

**Comment by calvellido** [comment]
It's been tackled in here: https://github.com/algolia/docsearch-configs/issues/824

@raulraja could you have a look at the current behaviour to see if that's desirable?

**Comment by calvellido** [comment]
This has been now fixed with the awesome support of the Algolia team:

https://github.com/algolia/docsearch-configs/blob/7eee192dbcc19f791989c48839421cf1512e30b6/configs/arrow.json

:raised_hands: :raised_hands:
