### ISSUE TITLE
Playgrounds are broken

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow#1416]
https://arrow-kt.io/docs/effects/fx/

Seems like several version related issues in the server or not sure what's going on. Is the server automatically updating with each master build? 

We need a solid automated process especially now that advertised playgrounds and people may use them in their presentations and blog posts. Gotta get all these issues fixed ASAP.

**Comment by calvellido** [comment]
Should those snippets work with Arrow 0.9.0?

They work with the snapshot version, as it can be seen at https://next.arrow-kt.io/docs/effects/fx/

**Comment by calvellido** [comment]
Not relevant anymore
