### ISSUE TITLE
Unable to generate objects for both @higherkind and @extension

### ISSUE THREAD

**Issue by neshkeev** [arrow-kt/arrow#1417]
I define two objects:

1. `data class ParserK` annotated with `@higherkind`
2. `interface ParserKFunctor` annotated with `@extension`

Here is the code:

    @higherkind
    data class ParserK<A>(val f: (String) -> Option<A>): ParserKOf<A> {
        companion object
    }
    
    @extension
    interface ParserKFunctor : Functor<ForParserK> {
        override fun <A, B> Kind<ForParserK, A>.map(f: (A) -> B): Kind<ForParserK, B> {
            ...
        }
    }

When I execute `./gradlew :app:kaptKotlin` I get:

    error: "Arrow's annotations can only be used on Kotlin classes". Not valid for error.NonExistentClass
    
    > Task :app:kaptGenerateStubsKotlin
    
    > Task :app:kaptKotlin FAILED
    e: error: Arrow's annotations can only be used on Kotlin classes. Not valid for error.NonExistentClass                                           
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':app:kaptKotlin'.
    > Compilation error. See log for more details

Here is what I discovered:

1. If I remove the functor definition then the goal completes successfully and I can see the generated code.
2. If I remove `@higherkind` from the data class `ParserK` and copy the generated sources into the same file where `ParserK` is defined then I can see the generated code for the functor.

It seems like a bug for me, correct me if I am wrong, please

Here is the link to the repository with my code: [repository](https://github.com/neshkeev/kotlin-arrow-demo)

PS: it is a crosspost from [stackoverflow](https://stackoverflow.com/q/55786870/3686755)

**Comment by pakoito** [comment]
Betcha it's an ordering problem where the extension annotation is processed after the higherkind annotation. Try putting the extension on a separate file.

**Comment by neshkeev** [comment]
@pakoito Thank you for your response, but moving the extension on a separate file (and package) did not help. I updated the repository, please review.

**Comment by pakoito** [comment]
I've tinkered with it a bit. I cannot find the cause without debugging the processor, which requires more setup. Deferring to @raulraja that knows better how it works.

**Comment by nomisRev** [comment]
@neshkeev sorry for the late response. This is indeed related to the ordering of the processors.

If we try to generate both the higher kind and then the extensions on top of the kind in the same module APT goes nuts

For this reason all data types and instances had to be seperated in different modules. Could you try moving the extensions in a seperated module? That should fix this problem.

**Comment by nomisRev** [comment]
@neshkeev any luck with the proposed solution?

**Comment by neshkeev** [comment]
@nomisRev Thank you for your suggestions, it did work out, I updated the [repository](https://github.com/neshkeev/kotlin-arrow-demo) for references.

Feel free to close the ticket, please

**Comment by nomisRev** [comment]
Thanks for the response and reference @neshkeev!

**Comment by Quurz** [comment]
Hello Guys

I've to thank you also. Just ran into the very same problem.

Best regards

Alex
