### ISSUE TITLE
Can't find arrow-core 0.9.0 on maven-central

### ISSUE THREAD

**Issue by Petikoch** [arrow-kt/arrow#1420]
Hi, 

according https://github.com/arrow-kt/arrow/releases Version `0.9.0` was released in march 2019.

I'm looking for `arrow-core` (because I'm only interested in the `Either` type at the moment) but can't find `0.9.0` on https://search.maven.org/search?q=g:io.arrow-kt%20AND%20a:arrow-core&core=gav 
There is `0.8.2` as latest version, but no  `0.9.0` version.

Accoring to `Basic Setup` on https://github.com/arrow-kt/arrow/blob/master/README.md I should use JCenter. If i look in JCenter https://bintray.com/bintray/jcenter/io.arrow-kt%3Aarrow-core I can even only find version `0.7.1`.

What's wrong?

Thanks for your help and for ArrowKt!

Peti

**Comment by pakoito** [comment]
In release 0.9.0 we started moving the package names for consistency. The plan was to have a `-data` package with datatypes, and `-extensions` package with typeclass instances, and then a top level package with both. By 0.9.0 release we didn't have the last one, so what you want is to pull the `-extensions` one, as described here: https://github.com/arrow-kt/arrow/blob/0.9.0/README.md#next-development-version-090

**Comment by raulraja** [comment]
Hi, that is now in arrow-core-data https://arrow-kt.io/docs/#dependency-breakdown-starting-in-arrow-091

**Comment by raulraja** [comment]
Arrow core will be back in 0.9.1 but it will bundle data and extensions, it's the full pack for core but you can still get them a la carte

**Comment by Petikoch** [comment]
PS: The current docs (https://arrow-kt.io/docs/) still point to `0.8.2` as "current release".

![Unbenannt](https://user-images.githubusercontent.com/9936866/56733399-4eea2580-6760-11e9-80d2-e110b483af3c.PNG)

**Comment by pakoito** [comment]
Yeah, we have started "fixing" the version of the docs so that one is currently stable. Starting 0.9.1 we'll have them properly versioned with a dropdown and all.
