### ISSUE TITLE
Make Foldable#iterateRight more Kotlin-y

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1428]
This function looks lifted from a Haskell codebase, with currying and all. Let's make it more like a Kotlin function, maybe an extension function on `Iterable`.

https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Foldable.kt#L202-L208

The function also shouldn't live in Foldable, but be Eval.kt

**Comment by plastic-karma** [comment]
I can take a look at that. @pakoito, do you have any other "make it more like a Kotlin function" things in mind except making it an extension function?

**Comment by nomisRev** [comment]
I'd start with something like `fun <A, B> Iterator<A>.iterateRight(lb: Eval<B>, f: (Eval<B>, Eval<B>) -> Eval<B>): Eval<B>` this, this makes it similar to the signature of `foldRight`.

**Comment by pakoito** [comment]
@plastic-karma like @nomisRev said, it's just pulling the function into another file, and changing the signature. It's a good starter ticket to setup the project :)

**Comment by plastic-karma** [comment]
Sounds good, I’ll make the change.

**Comment by plastic-karma** [comment]
@pakoito, is it okay though to move the function from ``arrow-typeclasses`` to ``arrow-core-data``?

**Comment by pakoito** [comment]
Yep!

**Comment by raulraja** [comment]
Fixed in #1434
