### ISSUE TITLE
Make @extension codegen put constructors in the datatype's companion

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1431]
In today's @extension implementation, constructor functions are exposed as top-level functions. This causes the IDE to show all instances when asking for a hint of which one to get, and you're forced to desambiguate on imports. Because many things are an applicative, this list is long and not UX-happy.

Instead, we should make constructor functions as extensions on the datatype's companion.

```
interface Example<F>: Applicative<F> {
  fun make(): Kind<F, Unit> = just(Unit)
} 
```

Today:

```
fun make(): Kind<ForMyDatatype, Unit> = MyDatatype.just(Unit)
```

After fix:

```
fun MyDatatype.Companion.make(): Kind<ForMyDatatype, Unit> = MyDatatype.just(Unit)
```

**Comment by nomisRev** [comment]
What should we do for functions like

```
interface Async<F> : MonadDefer<F> {
   fun CoroutineContext.shift(): Kind<F, Unit>
}
```

Today:
```
fun CoroutineContext.shift(): Kind<ForIO, Unit> = IO.async().run { this@shift().shift() }
```

After fix:
```
fun IO.Companion.shift(ctx: CoroutineContext): IO<Unit> = IO.async().shift(ctx)
```

I'd also like to see the instances cached in this PR.

Today:
```
fun Companion.async(): IOAsync = object : arrow.effects.extensions.IOAsync {  }
```

After fix:
```
private object AsyncInstance = object : arrow.effects.extensions.IOAsync {  }
inline Companion.async(): Async<ForIO> = AsyncInstance
```

**Comment by raulraja** [comment]
👋
