### ISSUE TITLE
[Arrow effects] Queue

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow#1438]
Currently there is no Queue yet in Arrow-effects. It'd be great to have one.

Two interesting Scala implementations: [FS2](https://github.com/functional-streams-for-scala/fs2/blob/series/1.0/core/shared/src/main/scala/fs2/concurrent/Queue.scala), [ZIO](https://github.com/scalaz/scalaz-zio/blob/master/core/shared/src/main/scala/scalaz/zio/Queue.scala)

**Comment by richard-gibson** [comment]
Happy to take this, started working on something similar to an earlier ZIO implementation so not to have to create a ring buffer to start off

**Comment by Cotel** [comment]
Is anyone working on this? Is this still relevant or is there any issue which has more priority?
