### ISSUE TITLE
["Request"] Either constructor expectation

### ISSUE THREAD

**Issue by mkobit** [arrow-kt/arrow#1445]
### What version are you currently using?

* `0.9.0`

### What would you like to see?

As somebody still new to Arrow and a lot of the functional paradigms provided with it, navigating the library itself can be daunting and tough to figure out at times.

The documentation is solid, but when trying to play around and learn some of the components, it can become pretty difficult to figure out what to do when not following the examples exactly.

For example, when trying to figure out some of the operations of `Either` and what types of operations I would use if I altered existing code to use something like `Either<SomeError, Option<SomeValue>>` I was having trouble just trying to construct the right parameterized type.

I thought construction would follow similar patterns in the Kotlin stdlib:

```kotlin
val explicitList = listOf<Int>()
val inferredList = listOf(1)
val inferredFrom: List<Int> = listOf()
```

Attempting to follow a similar pattern with `Either`

```kotlin
// fails compilation
val right = Either.Right<String, Int>(5) // only one type argument needed
```

Ok let's try and supply the left type since right could be inferred from the constructor argument

```kotlin
// fails compilation, does not conform to type string
val right = Either.Right<String>(5)
```

Ok, that seems a little bit odd to me. `String` is provided explicitly for the left, and the `5` should infer that the left, but this fails, too.

```kotlin
val right = Either.Right(5)
```

Fully omitting the type results in `Either<Nothing, Int>`, which maybe people want by default? At least for me, it seems like the most common use case would be to provide the left type.

So, it seems like the only way to get it is to type the variable itself:

```kotlin
val right: Either<String, Int> = Either.Right(5)
```

I also was seeing compiler errors in my first attempts since I was trying to call the `internal constructor` when the factory method from the `companion object` is used, which makes it a little tough to grok.

There are also the functions:

```kotlin
fun <L> Left(left: L): Either<L, Nothing> = Either.left(left)

fun <R> Right(right: R): Either<Nothing, R> = Either.right(right)

// ...
@higherkind
sealed class Either<out A, out B> : EitherOf<A, B> {
 // ...
  companion object {

    fun <L> left(left: L): Either<L, Nothing> = Left(left)

    fun <R> right(right: R): Either<Nothing, R> = Right(right)

// ...

fun <A> A.left(): Either<A, Nothing> = Either.Left(this)

fun <A> A.right(): Either<Nothing, A> = Either.Right(this)

```

Which duplicate the exact constructors from above, which make it a little bit confusing which path is the right path to take. There are 4 different ways to create an `Either.Left`. There isn't KDoc on some of these either which increases the friction a little bit. The `A.right()` is also a bit confusing at first glance, as you might think returns the `right` value (maybe missing the property) but it actually boxes up the value into an `Either`. I don't think adding extension methods for `Any` type simplify things.

This is just some of my experience when trying to use this library more, and it has also been difficult on some teammates with the large API surface and not knowing what to use and when.

I think it would be useful to simplify some of the usage areas and reduce API surface area so it is simpler, easier, and more straightforward for those who are not intimately familiar with the tools to be able to slowly integrate different components without being overwhelmed.

**Comment by raulraja** [comment]
@mkobit thanks for reporting the issue with such detail.
All data types in Arrow by convention follow the following conventions:
- ADT nodes such as `Left` and `Right` are public because they get used in `when` statements by users which would rather use `when` vs `fold`.
- All constructors have syntactic variations as extensions functions for all `A` that can lift an `A` value into the datatype.
- Data types which have more than one type argument and represent a sum type like in this case `Either` favor the use of `Nothing` as bottom type so that the compiler can infer naturally all arguments of any expression. Ascribing types manually like your case where you specify the left and right types is the less common case as Either is used frequently in explicit return types of functions as well as expressions where the compiler can infer the types faster if ascribed in the receiving value since resolution happens left to right and the RHS maybe to complex. 

I believe at some point we had in Either 2 type arguments in Left and Right but multiple users reported issues when using Either in when expressions due to having to type the values in the constructor because of the compiler limitations when checking instances in `when`.

Feel free to submit a PR to add any clarification you think that they may be missing directly on the Kdocs of the Either data type or those extension functions at https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-core-data/src/main/kotlin/arrow/core/Either.kt These docs will be exported before 1.0 as the single source of truth for arrow docs and whatever we add there will show up in the documentation.

thanks!

**Comment by mkobit** [comment]
Thanks @raulraja for quick response, and sorry if the original issue came off as heated.
I was frustrated with after a couple hours not having anything meaningful complete, and was writing my experience in the hopes that it could either be used as some constructive review going forward or help me form a better understanding.
I'd like to start using some of the datatypes and aspects of this library`, but I have been finding it way more difficult than expected, and I'm not sure it will be worth it for my team and I to begin using it at this stage.

> *ADT nodes such as Left and Right are public because they get used in when statements by users which would rather use when vs fold.

The types being `public` makes sense for the `when` use case, the `internal constructor` I found a bit odd.

`Option.Some`, `Try.Success`, `Try.Failure`, `Validated.Valid`, `Validated.Invalid`, and most likely others all have public constructors with also some factory methods for them

Below goes into detail a bit more about the asymmetric nature of the types, and a proposal (which should probably be it's own issue) to drastically reduce the amount of variations to box objects

> * All constructors have syntactic variations as extensions functions for all A that can lift an A value into the datatype.

I think having these many extensions heavily pollutes the API surface and makes discovery when using an IDE more difficult, especially for somebody new to the library.
I might be in the minority of `arrow` users (especially those with much more experience using these paradigms and longer term users), but I think that this could be a separate issue entirely.
I think for these cases "less is more", and being opinionated in the library would be helpful - if you want an `Either`, `Option`, or `Try`, why not just construct it?
Or, alignment on factory methods for each type and reducing visibility on constructors is another option.
All of the overloads seem superfluous, and seem to just introduce more complexity to consumers of the library.

Taking a deeper look at `Option`.

```kotlin
@higherkind
sealed class Option<out A> : OptionOf<A> {
  companion object {
    fun <A> just(a: A): Option<A> = Some(a)
    operator fun <A> invoke(a: A): Option<A> = Some(a)
    fun <A> empty(): Option<A> = None
    fun <A> fromNullable(a: A?): Option<A> = if (a != null) Some(a) else None
  }
}

object None : Option<Nothing>()

data class Some<out T>(val t: T) : Option<T>()

fun <T> T?.toOption(): Option<T> = this?.let { Some(it) } ?: None

fun <A> Boolean.maybe(f: () -> A): Option<A> =
  if (this) {
    Some(f())
  } else {
    None
  }

fun <A> A.some(): Option<A> = Some(this)

fun <A> none(): Option<A> = None
```

This gives us the following ways to create/get an `Option`:

1. `Option.Some(value)` - `Option.Some`
1. `Option.just(value)` - `Option.Some`
1. `Option(value)` - `Option.Some`
1. `value.some()` - `Option.Some`
1. `none()` - `Option.None`
1. `value.toOption()` - `Option`
1. `Option.fromNullable` - `Option`
1. `Option.empty()` - `Option.None`
1. `None` - `Option.None`
1. `Boolean.maybe { value }` - `Option`

That is all the ways I can find for constructing an `Option`:

* 4 explicit, different ways of creating an `Option.Some`.
* 3 explicit, different ways to retrieve the `Option.None`
* I think, 3 extensions to `Any`
* 2 different ways for boxing a nullable type
* a `Boolean` extension method (?)

Compared the JDK built-in [`Optional`](https://docs.oracle.com/javase/11/docs/api/java/util/Optional.html):

* `Optional.empty`
* `Optional.of`
* `Optional.ofNullable`

In my opinion, I think reducing the amount of variations here would make it easier to onboard and reduce the amount of decisions a consumer has to make.
All of these just make it more difficult for somebody new to know which one to use.

* `Option.Some(value)` or `Option.just(value)` - if the types like `Option.Some` are desired to be kept public for `when` statements and other compiler safety, then I think presenting only 1 entrypoint is the best way to simplify.
* `Option.None` - `empty()` is an overload that seems superfluous as `None` is going to be a `public` type anyways
* `Option.fromNullable` - covers the `Some` or `None` use case

I think applying boundaries and reducing the API surface to all types would be useful in the same way that I hopefully demonstrated above.

> * Data types which have more than one type argument and represent a sum type like in this case Either favor the use of Nothing as bottom type so that the compiler can infer naturally all arguments of any expression

This makes sense.
However, it being different than established patterns in the `stdlib` makes this more difficult to grasp and start using.

I think this issue itself can be closed since it doesn't have a specific feature request and I don't know if anything else will come out of it.
I would be in favor of a separate issue for "reducing variants for boxing objects" for each data type unless you guys feel strongly that those overloads are needed.

**Comment by raulraja** [comment]
@mkobit I'm in favor of reducing api surface and using in the data types the same names as in the type classes. That also reduces the barrier to polymorphism. I think we will all be happy hearing about a proposal that is sound over all concrete data types. Feel free to open another issue or submit directly a PR but if you are interested in pursuing this I'll be happy to help wherever I can.
