### ISSUE TITLE
["Request"] Consider trimming down public APIs to create data types

### ISSUE THREAD

**Issue by mkobit** [arrow-kt/arrow#1455]
## What version are you currently using?

* `0.9.0`

## What would you like to see?

I would like to see a reduction in the amount of public APIs to construct a data type from  a value. There might be some other places in `arrow-kt` where I think this pattern could also apply, but this issue is specifically for reducing the APIs to put a value into one of the datatypes at https://arrow-kt.io/docs/datatypes/intro/.

**NOTE**: This is a follow-up from the discussion in https://github.com/arrow-kt/arrow/issues/1445 , specifically the middle reply at https://github.com/arrow-kt/arrow/issues/1445#issuecomment-494057183

Here is the relevant text from that issue:

> > * All constructors have syntactic variations as extensions functions for all A that can lift an A value into the datatype.
>
> I think having these many extensions heavily pollutes the API surface and makes discovery when using an IDE more difficult, especially for somebody new to the library. I might be in the minority of `arrow` users (especially those with much more experience using these paradigms and longer term users), but I think that this could be a separate issue entirely. I think for these cases "less is more", and being opinionated in the library would be helpful - if you want an `Either`, `Option`, or `Try`, why not just construct it? Or, alignment on factory methods for each type and reducing visibility on constructors is another option. All of the overloads seem superfluous, and seem to just introduce more complexity to consumers of the library.
>
> Taking a deeper look at `Option`.
>
> ```kotlin
> @higherkind
> sealed class Option<out A> : OptionOf<A> {
>   companion object {
>     fun <A> just(a: A): Option<A> = Some(a)
>     operator fun <A> invoke(a: A): Option<A> = Some(a)
>     fun <A> empty(): Option<A> = None
>     fun <A> fromNullable(a: A?): Option<A> = if (a != null) Some(a) else None
>   }
> }
>
> object None : Option<Nothing>()
>
> data class Some<out T>(val t: T) : Option<T>()
>
> fun <T> T?.toOption(): Option<T> = this?.let { Some(it) } ?: None
>
> fun <A> Boolean.maybe(f: () -> A): Option<A> =
>   if (this) {
>     Some(f())
>   } else {
>     None
>   }
>
> fun <A> A.some(): Option<A> = Some(this)
>
> fun <A> none(): Option<A> = None
> ```
>
> This gives us the following ways to create/get an `Option`:
>
> 1. `Option.Some(value)` - `Option.Some`
> 2. `Option.just(value)` - `Option.Some`
> 3. `Option(value)` - `Option.Some`
> 4. `value.some()` - `Option.Some`
> 5. `none()` - `Option.None`
> 6. `value.toOption()` - `Option`
> 7. `Option.fromNullable` - `Option`
> 8. `Option.empty()` - `Option.None`
> 9. `None` - `Option.None`
> 10. `Boolean.maybe { value }` - `Option`
>
> That is all the ways I can find for constructing an `Option`:
>
> * 4 explicit, different ways of creating an `Option.Some`.
> * 3 explicit, different ways to retrieve the `Option.None`
> * I think, 3 extensions to `Any`
> * 2 different ways for boxing a nullable type
> * a `Boolean` extension method (?)
>
> Compared the JDK built-in [`Optional`](https://docs.oracle.com/javase/11/docs/api/java/util/Optional.html):
>
> * `Optional.empty`
> * `Optional.of`
> * `Optional.ofNullable`
>
> In my opinion, I think reducing the amount of variations here would make it easier to onboard and reduce the amount of decisions a consumer has to make. All of these just make it more difficult for somebody new to know which one to use.
>
> * `Option.Some(value)` or `Option.just(value)` - if the types like `Option.Some` are desired to be kept public for `when` statements and other compiler safety, then I think presenting only 1 entrypoint is the best way to simplify.
> * `Option.None` - `empty()` is an overload that seems superfluous as `None` is going to be a `public` type anyways
> * `Option.fromNullable` - covers the `Some` or `None` use case
>
> I think applying boundaries and reducing the API surface to all types would be useful in the same way that I hopefully demonstrated above.

------

My proposal is for each datatype, to reduce the amount of public APIs. `Option` is shown above, but I would like to see something similar for all datatypes (if this is accepted).

* [ ] - `Option`
* [ ] - `Either`
* [ ] - `Try`
* [ ] - `Validated`
* [ ] - `NonEmptyList`
* [ ] - `ListK`
* [ ] - `SequenceK`
* [ ] - `SetK`
* [ ] - `MapK`
* [ ] - `SortedMapK`
* [ ] - `Ior`
* [ ] - `Id`
* [ ] - `Reader`
* [ ] - `Kleisli`
* [ ] - `State`
* [ ] - `StateT`
* [ ] - `Store`
* [ ] - `Moore`
* [ ] - `Sum`
* [ ] - `Day`
* [ ] - `WriterT`
* [ ] - `Trampoline`
* [ ] - `Coproduct`
* [ ] - `Eval`
* [ ] - `OptionT`
* [ ] - `EitherT`
* [ ] - `Function0`
* [ ] - `Function1`
* [ ] - `Const`

## Open Questions

* Deprecation cycle before removal?

**Comment by pakoito** [comment]
I'm for reducing the surface of constructors if we end up in a consistent state. For example, Try has an invoke constructor, all of them have a just constructor with a different name, and some have a raiseError one. We're so familiar with the library it's better if someone who's primarily a user tell us which ones could be trimmed.

**Comment by mkobit** [comment]
Sounds good @pakoito - maybe a good approach here is to have a separate MR per type ?

**Comment by pakoito** [comment]
I'm okay with keeping the discussion here.

**Comment by raulraja** [comment]
@mkobit closing this as I believe most of the concerns around these sugar constructors you mention have been addressed in the latest versions of Arrow. Feel free to create any new issues if there are still confusing extensions in 0.13.x or the latest main snapshot. Thanks for reporting!

**Comment by mkobit** [comment]
@raulraja I would definitely agree that this has been resolved. Thanks!
