### ISSUE TITLE
Unable to simply get the value of an Option

### ISSUE THREAD

**Issue by proteus-aholt** [arrow-kt/arrow#1469]
What version are you currently using?
0.7.3
What would you like to see?
When dealing with an Option (or other data types for that matter, such as Try or Either) there doesn't appear to be a straightforward way to get the underlying value.

**Comment by pakoito** [comment]
Is `getOrElse` or `getOrDefault` an option?

**Comment by raulraja** [comment]
@proteus-aholt you can only get the value wrapped in `Option` if you deal with the absence. Here is a few ways to extract the value out of an Option.
```kotlin
val n: Int = Option(1).getOrElse { 0 }
val z: Int = Option(1).fold({ 0 }, { it })
val y: Int? = Option(1).toNullable()
```
Arrow does not favor unsafe APIs. Users are responsible to provide an alternative value in case of absence. Option does not model the same semantics as in Scala or Java where you have `Option.get` and if the value is absent it blows up with an exception. Nothing in Arrow blows up with exceptions and Option is a safe data type.

**Comment by proteus-aholt** [comment]
My situation was due to using Arrow on a project that already had APIs built in a non-functional way.  I was _actually_ using a Try, but got it to the point where I ended up having an Option<Throwable>, and I wanted to throw the exception because the code calling mine was written to handle it.  I've been using Arrow pretty extensively for a while now, so I knew about most of the methods suggested: `getOrElse`, `getOrDefault` `orNull` and so on.

I ended up coming up with a solution by utilizing `Mockito` to create a 'default value':

```
/**
 * If this Try is a Success, returns the underlying successful value.
 * Otherwise, throws the underlying throwable.
 *
 * @return the success value
 */
inline fun <reified T : Any> Try<T>.unnest(): T =
    // The Mock will never be used, but due to arrow API, we need to supply a 'default value' even though we KNOW there is one.
    if (isSuccess()) toOption().getOrElse { Mockito.mock(T::class.java) }
    // The RuntimeException will never be thrown, but due to arrow API, we need to supply a 'default value' even though we KNOW
    // there is a throwable.
    else throw toEither().swap().toOption().getOrElse { RuntimeException("Try failure. Somehow without a throwable???") }
```

which worked perfectly for my situation.
I know that Arrow does not favor unsafe APIs, so I know this was an unusual situation.  I'm mostly leaving this here in case anyone else has a similar issue to mine, I'll close this now.  

Thanks!

**Comment by nomisRev** [comment]
Hi @proteus-aholt you can use `fold` here instead, you can provide functions/values for all cases (Failure/Success in this case).

```
val try: Try<T> = ...
val value = try.fold({ error -> throw error }, { value -> value })
```

Which would be the equivalent of using `when`.

```
val try: Try<T> = ...
when(try) {
  is Try.Success -> try.value
  is Try.Failure -> throw try.error
}
```

As you can see here, because we "match" on `Try.Success` Kotlin can smart cast. In the case of `isSuccess()` the compiler cannot, we could fix this with [contracts](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.contracts/index.html) maybe but I think we should remove those methods in favor of `fold` and `when`.

As you already mentioned we don't favor unsafe APIs, but you can always very easily build them yourself using the Arrow API if you want to.

**Comment by proteus-aholt** [comment]
o.0 using a when (or fold) had completely slipped my mind.

```
/**
 * If this Try is a Success, returns the underlying successful value.
 * Otherwise, throws the underlying throwable.
 *
 * @return the success value
 */
fun <T : Any> Try<T>.unnest(): T =
    when (this) {
        is Try.Success -> value
        is Try.Failure -> throw exception
    }
```

much cleaner, imo.
