### ISSUE TITLE
Implement Bitraverse

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1471]
Implement the Bitraverse interface in the arrow-core-typeclasses package as follows:

```
interface Bitraverse<F>: Bifoldable<F> {
  fun <G, A, B, C, D>  Kind<Kind<F<Kind<G, A>>, Kind<G, A>>>.bitraverse(AP: Applicative<G>, f: (A) -> Kind<G, C>, g: (B) -> Kind<G, D>): Kind<G, Kind<Kind<F, C>, D>>>

  fun <G, A, B> Kind<Kind<F<Kind<G, A>>, Kind<G, B>>>.bisequence(AP: Applicative<G>): Kind<G, Kind<Kind<F, A>, B>>> =
    bitraverse(::identity, ::identity)

 ...other necessary functions
}
```

See [Bitraverse.scala](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/Bitraverse.scala) for reference, and [this tweet](https://twitter.com/impurepics/status/1002995295758749699/photo/1) to see a visual use case.

The only law is Identity:

```
def <A, V> bitraverseIdentity(fab: Kind<Kind<F, A>, B>, ...) =
    fab.bitraverse(::identity, ::identity).equalsUnderTheLaw(fab, EQ)
```

Steps:
- [ ] Define Interface
- [ ] Add inline documentation to interface
- [ ] Define Law
- [ ] Add implementation for all instances of Bifoldable such as Tuple and Either
- [ ] Make all the new instances be tested by BitraverseLaws
- [ ] Add Bitraverse to [Intro of Typeclasses](https://arrow-kt.io/docs/typeclasses/intro/) below Bifoldable
- [ ] Add Bitraverse page to the docs as a folder [here](https://github.com/arrow-kt/arrow/tree/master/modules/docs/arrow-docs/docs/docs/arrow/typeclasses). Use bifoldable as the baseline and modify it accordingly

**Comment by maruiz81** [comment]
Hi everyone, I am working on this issue, I have some of the points already and I am trying to have my first full implementation ready this week.
Regards

**Comment by pakoito** [comment]
Brilliant! I'd suggest sending a PR as early as possible so you can have some feedback just in case :D

**Comment by maruiz81** [comment]
sure, all the feedback I will have is welcome. I will send the PR as soon as I feel a little confident about it.

**Comment by maruiz81** [comment]
Guys I have implemented this in https://github.com/arrow-kt/arrow/pull/1487. Please review it and let me know of stuff you miss, errors or improvements.

**Comment by kioba** [comment]
@maruiz81 @pakoito #1487 got merged.
Is there something else to add or should we close this ticket?

**Comment by maruiz81** [comment]
yes, if you don't have any complaint I think we can close it.

**Comment by pakoito** [comment]
Closing!
