### ISSUE TITLE
Async#mapEffect

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1484]
```
fun <A, B> Kind<F, A>.mapEffect(f: suspend (A) -> B): Kind<F, B> =
  flatMap { a -> effect { f(a) } }
```

* [ ] Add function to Async.kt
* [ ] Add dokka on top of the function (see other functions on the file)
* [ ] Add examples below https://arrow-kt.io/docs/effects/async/#continueon

**Comment by FireZenk** [comment]
Let me do this one
