### ISSUE TITLE
[Request] A handle to turn off `inline` modifier in generated `optic|product`s.

### ISSUE THREAD

**Issue by soberich** [arrow-kt/arrow#1494]
What version are you currently using?
`0.9.1-SNAPSHOT`
What would you like to see?
A handle to turn off `inline` modifier in generated `optic|product`s.
Use case:
Mapping via copy method between projections to reduce boilerplate.
Achieved via inheritance by delegation. Similar as described here.
https://tp21.se/blog/2017/12/07/dto-mapping-in-kotlin/
to not to expose `delegate` to outside world at lease `internal` modifier is desirable.
Resulting
```console
Public-API inline function cannot access non-public-API 'internal final val delegate: Record defined in com.example.marvel.domain.model.api.record.RecordDto'
```
Should we make a handle to turn `inline` off?

**Comment by raulraja** [comment]
I'm not sure there is a strong reason why we are inlining those and can probably be turned off for all codegen stuff. //cc @nomisRev

**Comment by pakoito** [comment]
This is fixed by annotating with `@PublishedApi`, doesn't it? It tries to inline a private and warns about it.

**Comment by soberich** [comment]
@pakoito it worked.
But now I have a different error with `@product`
```console
/marvel-github/business/build/generated/source/kaptKotlin/main/product.com.example.marvel.domain.model.api.employee.employeeCreateCommand.kt: (62, 133):
 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Long?
e: /marvel-github/business/build/generated/source/kaptKotlin/main/product.com.example.marvel.domain.model.api.employee.employeeCreateCommand.kt: (62, 142):
 Type mismatch: inferred type is Long? but Long was expected

```

You can go clone this -> https://github.com/soberich/marvel and execute `./gradlew kaptKotlin` to see the errors.
The project is a mess - it's a playground.
And yes, there are some nullable/non-nullable suboptimal decisions made due to other libraries and general attempt to combine them. So, there are nullable types for `id` because one of projections is expected to get a `null` (no-value) for id (`...UpdateCommand`).

**Comment by pakoito** [comment]
Just for th sake of testing id from `Long?` to `Option<Long>`

**Comment by soberich** [comment]
@pakoito changing the data time is not an option (sorry for the pun). This issue is about `inline`. Guys (@raulraja, @pakoito), if there is any move if there is any move in direction of removing `inline` this will make sense IMO. And anyway feel free to close whether you apply proposed change/fix or not.

**Comment by pakoito** [comment]
Yes, look into the processor for optics:

https://github.com/arrow-kt/arrow/blob/master/modules/meta/arrow-meta/src/main/java/arrow/optics/LensesFileGenerator.kt#L16

https://github.com/arrow-kt/arrow/blob/master/modules/meta/arrow-meta/src/main/java/arrow/optics/IsosFileGenerator.kt#L33

https://github.com/arrow-kt/arrow/blob/master/modules/meta/arrow-meta/src/main/java/arrow/optics/OptionalFileGenerator.kt#L24

https://github.com/arrow-kt/arrow/blob/master/modules/meta/arrow-meta/src/main/java/arrow/optics/PrismsFileGenerator.kt#L14

Send a PR removing them and tag @nomisRev
