### ISSUE TITLE
Add FunctorFilter/MonadFilter instances for Rx and Reactor

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1501]
https://twitter.com/sla_shalafi/status/1145988260004585472

**Comment by plattysoft** [comment]
What we did was:

```
fun <T> Observable<Option<T>>.flatten(): Observable<T> {
    return flatMap {
        it.map {
            Observable.just<T>(it)
        }.getOrElse {
            Observable.empty<T>()
        }
    }
}
```

I'm happy to send a PR with it if you are happy with it.

**Comment by pakoito** [comment]
What we'd need is for `filterMap` to be implemented, and flattenOption can be derived from there.

One thing I'd suggest is using `fold` instead of `map` then `getOrElse`. Same results, one fewer intermediate object created.

**Comment by pakoito** [comment]
If you do a PR, make sure to add it to Flowable, Maybe and Flux too, as all of them are capable of having this pattern.

**Comment by plattysoft** [comment]
fold sounds better indeed, cleaner, more concise.

I'll probably send a PR later this week.

**Comment by lenguyenthanh** [comment]
Is anyone working on this issue? If the answer is no, I'm happy to try. I have free time this weekend.

**Comment by raulraja** [comment]
`aql` could also have the rx and reactor integration modules since these instances will enable most of the AQL operators.

**Comment by plattysoft** [comment]
Oh, I completely forgot about this... I might have some time tomorrow, otherwise take it.

**Comment by plattysoft** [comment]
I didn't do it exactly as you intentded @pakoito , this is what made sense in my head, but I'm happy to iterate and discuss it: https://github.com/arrow-kt/arrow/pull/1550

**Comment by pakoito** [comment]
Flatten is already taken as an extension function. Let's break it down:

```
fun <T, A, B> Flowable<A>.mapFilter(f: (A) -> Option<B>) =
  flatMap { a ->
    f(a).fold({ Flowable.empty() }, { b -> Flowable.just(b) })
  }
```

So now we have a function that works for every filter function, and also maps all in one go. Great. Let's specialize it!

```
fun <T, A> Flowable<Option<A>>.filterNone() =
  mapFilter { it } // mapFilter(::identity) to prevent an additional allocation
```

It turned out to be super easy to implement, and we've gotten functionality that's generic, allowing us to implement the FunctorFilter typeclass on the way. 2x1!

**Comment by lenguyenthanh** [comment]
@Cotel I think this issue still need to be opened. We need to add FunctorFilter for Reactor. I will do it today or tomorrow.

**Comment by Cotel** [comment]
Oh sry, I saw the merged PR and thought it was finished 🙏
