### ISSUE TITLE
Rename mapFilter to filterMap

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1504]
All operations that do something then map are called xxxMap except for `mapFilter`. We should use the chance that we're moving FilterFunctor to core to rename the old one.

**Comment by i-walker** [comment]
should we handle this here https://github.com/arrow-kt/arrow/pull/1511

**Comment by pakoito** [comment]
It's already merged so maybe in #1513

**Comment by pakoito** [comment]
Also, those stackoverflows on the previous diff weren't fixed https://github.com/arrow-kt/arrow/pull/1511/files#diff-37b50abf0377adef1820033a662d42c7R196

**Comment by raulraja** [comment]
Thought the test were in @i-walker told.me it was ready to merge over slack. Sorry.

**Comment by i-walker** [comment]
It was we handle this in another issue. Everything is alright :)

**Comment by i-walker** [comment]
closed by https://github.com/arrow-kt/arrow/pull/1513
