### ISSUE TITLE
Optics missing from current 0.9.1-SNAPSHOT

### ISSUE THREAD

**Issue by brezinajn** [arrow-kt/arrow#1510]
All code from `arrow/modules/optics/arrow-optics/src/main/kotlin/arrow/optics/` is missing from current snapshot.

**Comment by nomisRev** [comment]
@brezinajn this should be fixed after master finishes building :)

**Comment by i-walker** [comment]
@brezinajn can you confirm that it works again?
I checked deployment and `arrow-optics-mtl` is live. And hopefully the artifactory updated the old binaries.

**Comment by brezinajn** [comment]
@i-walker Confirmed. Everything is where it should be :)
