### ISSUE TITLE
Upgrade ktlint and disable no-unit-return rule

### ISSUE THREAD

**Issue by Tylos** [arrow-kt/arrow#1525]
### References

Related to #1502 

### Description

Upgrade ktlint plugin in build.gradle or set ktlint version manually to 0.34.0 or above. This will allow to globally disable no unit returns errors in arrow, allowing to add explicit unit return types

**Comment by Tylos** [comment]
Seems like version  `0.34.0` has some regression bugs, I am keeping an eye to see when there is a stable version we could include

**Comment by raulraja** [comment]
Closing as this is no longer relevant and looks like we are now in 0.39.0 for KtLint. Thanks, @Tylos !
