### ISSUE TITLE
How to manager state in functional way

### ISSUE THREAD

**Issue by Fover23** [arrow-kt/arrow#1528]
Hi, I am android developer, I read some articles known functional programming. 
In some functional rules , the function need to be pure function.But in the real world , I need to change state in the android application runtime.
I konw the mutable state may cause some bug that not easy to find, I went to avoid in functional way, how to deal with it in functional way with arrow libs.

Thanks.

**Comment by pakoito** [comment]
I'd start by looking into MVI, Redux, and other architectural patterns where state is always passed around. Failing that, wrap your interactions with the environment with `IO` or `suspend` function so at least they're easily identifiable as effects.

**Comment by Fover23** [comment]
> 
> 
> I'd start by looking into MVI, Redux, and other architectural patterns where state is always passed around. Failing that, wrap your interactions with the environment with `IO` or `suspend` function so at least they're easily identifiable as effects.

Thanks for your suggestion.
