### ISSUE TITLE
`Polymorphic Programs` docs: broken links + typo

### ISSUE THREAD

**Issue by rcd27** [arrow-kt/arrow#1529]
All links to @JorgeCastilloPrz 's articles on Medium are broken.
Moreover, there is typo: "there is noT silver bullets"

**Comment by rcd27** [comment]
'Edit' button does not work as well, otherwise I'd try to fix that.

**Comment by pakoito** [comment]
We've moved the docs around, so that may be the problem with Editing master today. Try doing it on https://next.arrow-kt.io/docs/

**Comment by i-walker** [comment]
@rcd27 You can branch from release/0.9.0 and create a PR with the changes, this will then be the updated on arrow-kt.io. 
But don't do any commits in that branch. We're still working on locking this branch

**Comment by raulraja** [comment]
Closing this old issue. New docs in Arrow are being stored for previous versions and may be accessible in this URL https://arrow-kt.io/docs/0.9/patterns/polymorphic_programs/. Thanks, @rcd27
