### ISSUE TITLE
Allow `NonFatal` control over exceptions for MonadError and Monadic comprehensions

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow#153]
Currently comprehending over Try in an stack unsafe way returns a `Failures(SOE)` we should never capture fatal exceptions. See for reference http://www.scala-lang.org/api/2.12.0/scala/util/control/NonFatal$.html

**Comment by pakoito** [comment]
RxJava does it using a set of types for which exceptions are always propagated: SO, OOM... we should look into them.

**Comment by kartoffelsup** [comment]
Is this what you are referring to @pakoito? https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/exceptions/Exceptions.java#L66

**Comment by raulraja** [comment]
yep, those are a subset of the Fatal errors we need to contemplate.
