### ISSUE TITLE
NonBlocking.parTraverse behaves sequentially

### ISSUE THREAD

**Issue by AlbertoSH** [arrow-kt/arrow#1539]
Hi

Inside an `IO.fx`, looks like `NonBlocking.parTraverse` computes each element in a synchronous/sequential way. This is
```
  fx {
    !NonBlocking.parMap(
      effect { delay(1000) },
      effect { delay(1000) },
      effect { delay(1000) }
    ) { _, _, _ -> Unit }
  }
```
takes 1 seconds to be executed, while
```
  fx {
    !NonBlocking.parTraverse(listOf(
      effect { delay(1000) },
      effect { delay(1000) },
      effect { delay(1000) }
    )) {}
  }
```
takes 3 seconds to be executed

Affected Arrow Version
- 0.9.0
- 0.10.0-SNAPSHOT

A minimum project reproducing the issue can be found here: https://github.com/AlbertoSH/arrow-nonblocking-issue

**Comment by nomisRev** [comment]
Hi @AlbertoSH,

Thanks for reporting this, you're correct! This is left over from before, thanks for catching this before the release 🙏 The functions from `FxSyntax` should be removed, and you should be using `Concurrent` only from `0.10.0-SNAPSHOT`. The new syntax is demonstrated below, it takes the container as a receiver, and you can pass an optional `CoroutineContext` to the first param of `parTraverse` to override the `NonBlocking` behavior.

```
IO.fx {
  listOf(
    effect { delay(1000) },
    effect { delay(1000) },
    effect { delay(1000) }
  ).k().parTraverse { IO.unit }
}
```

cc\ @raulraja I think we can remove `FxSyntax` all together. Using `effect` you can achieve the same syntax. We can expose a seperate direct syntax DSL that uses `IO` underneath.

**Comment by AlbertoSH** [comment]
Hi @nomisRev 

Great! I just checked with your snippet and it works like a charm! :)
For anyone reading this, beware that the `parSequence()` method returns a `Kind<F, List<A>>` so you'll have to apply the effect with `!` or `bind()`

Is it worthy to update [the docs](https://arrow-kt.io/docs/effects/fx/async/#partraverse) or since it will be changed in the next version will it be done in the next release?

**Comment by nomisRev** [comment]
This is addressed already.
