### ISSUE TITLE
Make home code runable

### ISSUE THREAD

**Issue by AntonioMateoGomez** [arrow-kt/arrow#1566]
We need to make home code animation runnable with Try arrow and editable in place for people to play with the very first time they land in this page.

- [x] Implementation

- [x] Proper code snippet for each library

- [x] Adds browser stile #1576 

- [x] Control responsive mode and readjust the top position of the `fadeInDown` in the code block div.

**Comment by franciscodr** [comment]
@raulraja Who could provide the code snippets for the different libraries?

**Comment by raulraja** [comment]
For the time being you can just import each lib and make the code compile with a simple import of the library package then hand over to me. I'll talk individually with authors of each lib or come up with the examples myself

**Comment by AntonioMateoGomez** [comment]
This has been solved through this commit 
https://github.com/arrow-kt/arrow/commit/78d3cd52a6061e89e24941609b2bf0e37382ed5d
