### ISSUE TITLE
Build error importing Arrow in Gradle: Could not find io.arrow-kt:arrow-ank-gradle:0.7.1

### ISSUE THREAD

**Issue by donkii** [arrow-kt/arrow#1599]
I am trying to import arrow into my project after following dependencies steps i am getting the following error: 

> Could not find io.arrow-kt:arrow-ank-gradle:0.7.1.
> Searched in the following locations:
>   - https://dl.google.com/dl/android/maven2/io/arrow-kt/arrow-ank-gradle/0.7.1/arrow-ank-gradle-0.7.1.pom
>   - https://dl.google.com/dl/android/maven2/io/arrow-kt/arrow-ank-gradle/0.7.1/arrow-ank-gradle-0.7.1.jar
>   - https://jcenter.bintray.com/io/arrow-kt/arrow-ank-gradle/0.7.1/arrow-ank-gradle-0.7.1.pom
>   - https://jcenter.bintray.com/io/arrow-kt/arrow-ank-gradle/0.7.1/arrow-ank-gradle-0.7.1.jar
>   - https://plugins.gradle.org/m2/io/arrow-kt/arrow-ank-gradle/0.7.1/arrow-ank-gradle-0.7.1.pom

**Comment by raulraja** [comment]
@donkii, what version of arrow are you using? You should be able to get those automatically in 0.10.0 and 0.9.0. since we relocated Ank to arrow and its release cycle. Can you post a link or code you are using in your build.gradle to bring arrow?

**Comment by donkii** [comment]
android build.gradle
`
dependencies {
        classpath 'io.arrow-kt:arrow-ank-gradle:0.10.0'
}`

module build.gradle
```
apply plugin: 'ank-gradle-plugin'
dependencies {
    implementation 'io.arrow-kt:arrow-ank:0.10.0'
}

ank {
    source = file("src/main/docs")
    target = file("build/site")
    classpath = sourceSets.main.runtimeClasspath
}
```

**Comment by raulraja** [comment]
0.10.0 is not yet announced and still syncing to maven central. It's currently available in bintray

**Comment by donkii** [comment]
@raulraja After switching to 0.9.0 I am getting this error: 

> Could not get unknown property 'main' for SourceSet container of type org.gradle.api.internal.tasks.DefaultSourceSetContainer.

**Comment by raulraja** [comment]
Can you provide a minimal reproducible example project that we can use to test on our side?, thanks.

**Comment by JorgeCastilloPrz** [comment]
Is it an Android project @donkii?

**Comment by aballano** [comment]
@donkii Please try with the latest version and feel free to comment or re-open the issue if you still have problems.
