### ISSUE TITLE
New Docs for FunctorFilter instances for Rx

### ISSUE THREAD

**Issue by lenguyenthanh** [arrow-kt/arrow#1605]
We need to write new docs for #1603

**Comment by lenguyenthanh** [comment]
Hey @pakoito, I'm wondering which docs should I write for #1603. 

As far as I understand, all relationships between `FunctorFilter` and Rx instances will be generated. So I don't think We need to write more docs because of #1603.

Maybe we need to write more docs for `FunctorFilter` though.

**Comment by pakoito** [comment]
>Maybe we need to write more docs for FunctorFilter though.

Yes, this is what I meant.

**Comment by i-walker** [comment]
This issue is the same as https://github.com/arrow-kt/arrow/issues/330
If you agree @lenguyenthanh, please close this one.

**Comment by lenguyenthanh** [comment]
👍
