### ISSUE TITLE
Make ObservableK and the family covariant

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1609]
We found that when working with Observable and Either, mapping into `Either.left` would cause an error because the other side can't be hinted and Observable is invariant, so you need to create a local variable to give the correct type to Nothing.

We can fix this in ObservableK and suppress the variance issues.

cc @Laimiux @lenguyenthanh

**Comment by lenguyenthanh** [comment]
I'll work on this this weekend.

**Comment by pakoito** [comment]
Note that it'll complain that `flatMap` and other methods have generics in input positions. The fix is to make those extension functions.

**Comment by lenguyenthanh** [comment]
Ok, I'll take care of those things ;)
