### ISSUE TITLE
Links in Library Quickstart ToC are broken

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1614]
https://github.com/arrow-kt/arrow/blob/master/modules/docs/arrow-docs/docs/docs/quickstart/libraries/README.md#table-of-content

They need to be relative links, i.e. `({{ '/docs/patterns/glossary/#instances-and-extensions-interfaces' | relative_url }})`

**Comment by i-walker** [comment]
I got this. Thanks, @pakoito for reporting.
