### ISSUE TITLE
Monad transformer threading issue

### ISSUE THREAD

**Issue by ps-feng** [arrow-kt/arrow#1617]
Hi there,

I'm not sure if I did something wrong, but it seems monad transformers (at least `EitherT`) are not respecting the specified `CoroutineContext`. This is a simplified version of a larger piece of code where I found the error:
```kotlin
fun eitherTIOMonad(): EitherTMonad<ForIO, String> = EitherT.monad(IO.monad())

...

val eitherTIOM: IO<Either<String, String>> = eitherTIOMonad().fx.monad {
    println("Hi") // <-- runs on main thread, why?
    "Hola"
}.value().fix()

IO.fx {
    continueOn(Dispatchers.IO)
    eitherTIOM.bind() // <-- this line gets executed on IO thread
}.unsafeRunAsync { ... }
```
What I was playing with was basically just encapsulating some IO mixed with `Either` within an `EitherT` and I noticed that the first instruction within the `EitherT` monad was always executed on the caller thread. This code is simplified but with further `EitherT`s bound inside, the rest do get executed on IO worker threads.

Is this a bug or I did something wrong?

Cheers.

PS. I can work around this by doing `continueOn` within the `EitherT` but it doesn't seem like the correct thing to do as we're pushing threading contexts within that Monad, which should ideally be agnostic.
```kotlin
fun <A, B> MonadSyntax<EitherTPartialOf<ForIO, A>>.liftIO(fa: Kind<ForIO, B>): EitherT<ForIO, A, B> {
    return run { EitherT.liftF(IO.functor(), fa) }
}

val eitherTIOM: IO<Either<String, String>> = eitherTIOMonad().fx.monad {
    liftIO(IO.unit.continueOn(Dispatchers.IO)).bind()
    println("Hi") // <-- now runs on a worker thread
    "Hola"
}.value().fix()
```

**Comment by pakoito** [comment]
can you please do `!effect { println("Hi") }` and see what happens?

**Comment by ps-feng** [comment]
I unable to do that because I'm inside an `EitherT`.

**Comment by pakoito** [comment]
printing to screen is a side-effect. Inlining a side-effect in an `fx` block or a `map` block or somewhere like that is allowed by the language but you're bound to find edge cases like these.

Wrapping side-effects assures correct behavior.

**Comment by pakoito** [comment]
The good news is that @raulraja is working on a purity checker that'd flag these :)

**Comment by ps-feng** [comment]
Yeah, not the best example I guess. 

In the original code it wasn't a side effect but some pure CPU computation which I was expecting would be run on another thread. I guess I'd have to wrap it into some monad (`Eval`?) to defer the evaluation?

**Comment by pakoito** [comment]
It looms like a bug, I just can't point out why. Can you try to make `val eitherTIOM` into a function instead?

**Comment by raulraja** [comment]
You should be able to use IO.effect and wrap that with eitherT then use the EitherT bind to flatMap across the IO Either value. You can lift to Either with IO.attempt. sorry on phone now or I'd provide code examples.

**Comment by ps-feng** [comment]
@pakoito 

> It looms like a bug/edge case, I just can't point out why. Can you try to make `val eitherTIOM` into a function instead?

Interesting... after wrapping it into a function it does work as I'd expect. Why is that?

**Comment by pakoito** [comment]
Yeah, this is a Coroutine edge case, it looks to me. The first time `val` is created, the CC is already bound to current thread or something of the sorts, so anything in the block will run there. When called/created inside the block, it'll take the CC at that point in the block.

Damn.

@nomisRev can we default the CC to trampoline or something?

**Comment by ps-feng** [comment]
> so anything in the block (up to the first suspension point? can you test that?) will run there

Tested and it's indeed the case.

**Comment by pakoito** [comment]
Can you please do a version that uses `IO.defer { IO.concurrent().fx.concurrent(c) }` and see what happens?

**Comment by ps-feng** [comment]
> Can you please do a version that uses `IO.defer { IO.concurrent().fx.concurrent(c) }` and see what happens?

That worked!

The code used:
```kotlin
fun <A> IO.Companion.deferredFx(c: suspend ConcurrentSyntax<ForIO>.() -> A): IO<A> =
    defer { IO.concurrent().fx.concurrent(c).fix() }

...

val someIO = IO.deferredFx{
    println(Thread.currentThread().name) // <-- runs on worker thread
}

IO.fx {
    continueOn(Dispatchers.IO)
    someIO.bind() //
}.unsafeRunAsync { }
```

**Comment by pakoito** [comment]
I remember deleting something like this, not sure if this one in particular.

So...could you please PR a fix and a test for it? :D

**Comment by ps-feng** [comment]
Hehe, sure, I can prepare it in the next couple of days as I need to get familiar with how the tests are structured.

**Comment by pakoito** [comment]
Sure, if you need more responsive help ping us on the kotlinlang slack or the gitter channel.

**Comment by aballano** [comment]
I guess this issue can be then closed, otherwise please reopen :) Thank you @ps-feng!!

**Comment by ps-feng** [comment]
Hey @aballano, this issue is actually not fixed! Please check https://github.com/arrow-kt/arrow/pull/1624#issuecomment-535258589

**Comment by aballano** [comment]
Indeed 👍 We can leave this open then unless someone disagrees, although this issue should be fixed when the compiler plugin is out according to https://github.com/arrow-kt/arrow/pull/1624#issuecomment-535511134

**Comment by aballano** [comment]
Closing in favour of #1976 for https://github.com/arrow-kt/arrow/pull/1624#issuecomment-535511134 and #1977 as the same issue is happening for all Async and Concurrent fx blocks.

**Comment by aballano** [comment]
Thank you for reporting and all the work @ps-feng!! ❤️
