### ISSUE TITLE
What should List<A>.firstOption { A -> Boolean } return?

### ISSUE THREAD

**Issue by aparmet-toast** [arrow-kt/arrow#1621]
I have a list and I called firstOption on it, and was getting `None` when I thought I shouldn't be. I'd expect a function called firstOption that takes a predicate and is called on a Foldable to iterate through the foldable and return the first item matching the predicate or None if no items match, but instead I see [here](https://github.com/arrow-kt/arrow/blob/8fb38b0174c4bc7f20b22e64d4084ebb7cb06e8e/modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Foldable.kt#L213-L214) that it only checks the first element of the foldable.

Is this intended? If so, what's the usual use case?

Thanks!

**Comment by ps-feng** [comment]
> I'd expect a function called firstOption that takes a predicate and is called on a Foldable to iterate through the foldable and return the first item matching the predicate or None if no items match

I wouldn't expect that because I think it matches the standard library's `Iterable<T>.firstOrNull()`. See [here](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/first-or-null.html).

**Comment by aparmet-toast** [comment]
I think that's exactly what the standard library does:
> Returns the first element matching the given predicate, or null if element was not found.

This is how I have it implemented right now, with a `toOption()` call tacked on the end.

**Comment by pakoito** [comment]
Just in case, what you want is called `find`.

**Comment by aparmet-toast** [comment]
Is it documented? Click-through from the IDE didn't work at all, as I ended up in a recursive cycle in a file called `ListKFoldable.kt` (`package arrow.core.extensions.list.foldable`, which does not seem to appear on GitHub anymore), here:
```kotlin
@JvmName("firstOption")
@Suppress(
        "UNCHECKED_CAST",
        "USELESS_CAST",
        "EXTENSION_SHADOWED_BY_MEMBER",
        "UNUSED_PARAMETER"
)
fun <A> List<A>.firstOption(): Option<A> = arrow.core.extensions.list.foldable.List.foldable().run {
  arrow.core.ListK(this@firstOption).firstOption<A>() as arrow.core.Option<A>
}

@JvmName("firstOption")
@Suppress(
        "UNCHECKED_CAST",
        "USELESS_CAST",
        "EXTENSION_SHADOWED_BY_MEMBER",
        "UNUSED_PARAMETER"
)
fun <A> List<A>.firstOption(arg1: Function1<A, Boolean>): Option<A> =
        arrow.core.extensions.list.foldable.List.foldable().run {
  arrow.core.ListK(this@firstOption).firstOption<A>(arg1) as arrow.core.Option<A>
}
```

So this behavior as encountered was completely unexpected. I had to debug by printing a stack trace from the invoked closure.

**Comment by pakoito** [comment]
You're right. The docs aren't copied into code generated by kapt, so that's lost. Here's the original function: https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Foldable.kt#L210-L214

**Comment by lenguyenthanh** [comment]
Also `ListKFoldable.kt` was generated, so it is never on github.

**Comment by 1Jajen1** [comment]
I opened https://github.com/arrow-kt/arrow-core/issues/22 a few days ago (forgot to check existing issues), imo changing to the behaviour of the stdlib is the best move.

**Comment by 1Jajen1** [comment]
https://github.com/arrow-kt/arrow-core/pull/32 clarified this. `firstOption` behaves now like the standard lib `firstOrNull`. It is also deprecated and renamed to `firstOrNone` and it's an alias for `find`.
