### ISSUE TITLE
Media section integration

### ISSUE THREAD

**Issue by AntonioMateoGomez** [arrow-kt/arrow#1649]
We have to allocate the `Media` section in a diferent module apart from the arrow site so it won´t be affected by the different arrow doc versions.
Apart of that we need to solve:

- [x] Set the definitive site and then modify config.yml, head.html metatags, error.html metatags

- [x] Set tags for every post (core, fx, optics, meta, or incubator)

- [x] Text description for Books section

- [x] Style links in the post descriptions

- [x] error.html for this site

- [x] navbar logo link pointing to https://arrow-kt.io/

Media section will be finally located in https://github.com/arrow-kt/arrow-media and its url https://media.arrow-kt.io

**Comment by calvellido** [comment]
Completed in #1836 and available at https://github.com/arrow-kt/arrow-media
