### ISSUE TITLE
[Docs] Monad Comprehensions Patterns - Mistake

### ISSUE THREAD

**Issue by bbasinsk** [arrow-kt/arrow#1659]
This section shows two examples. The first is a "a somewhat common mistake". The second is "automatic wrapping of unexpected exceptions". The code in the examples are identical.

https://github.com/arrow-kt/arrow/blob/master/modules/docs/arrow-docs/docs/docs/patterns/monadcomprehensions/README.md#error-propagation-in-comprehensions

**Comment by pakoito** [comment]
Ye, I see it. We used to have `binding` and `bindingCatch`. That isn't the case anymore. I'll try to do a quick fix with a similar approach.
