### ISSUE TITLE
Master commit status

### ISSUE THREAD

**Issue by i-walker** [arrow-kt/arrow#1678]
We need to notify Maintainers and the respective Authors of unsuccessful PR pushes to master.

Current state of art:
An approved and green PR doesn't imply a healthy commit to master, neither hard pushes to master.

Proposal:
In order to move towards faster release cycles, we need to anticipate the aforementioned issues. Adding a Github action for an email to the respective parties should do it for now.

Feel free to add comments and suggestions.

**Comment by rachelcarmena** [comment]
Draft pull request in progress: #1694

**Comment by rachelcarmena** [comment]
BTW, GitHub Actions has amazing features like:
* Greeting users who are first time contributors to a repository 
* Labeling pull requests based on the files changed
etc.

**Comment by rachelcarmena** [comment]
NOTE: To configure notifications for GitHub Actions:

https://github.com/settings/notifications

![Screenshot from 2019-10-10 19-50-56](https://user-images.githubusercontent.com/22792183/66593529-79f1f580-eb97-11e9-8271-08e80e43ae6e.png)

**Comment by rachelcarmena** [comment]
Hi @i-walker! 

I found this note in [Travis CI notifications documentation](https://docs.travis-ci.com/user/notifications/):

> The email address is determined based on the email address in the commit, but only if it matches one of the email addresses in our database. 

and your email address is:

 ```
46971368+i-walker@users.noreply.github.com
``` 

That can be the reason why you don't receive notifications:

> The most common cause for not receiving build notifications, beyond not having a user account on Travis CI, is the use of an email address that’s not registered and verified on GitHub.

However, I also have an anonymous email for my commits and I receive GitHub Actions notifications in the [default notifications email](https://github.com/settings/notifications). So having an anonymous email for commits won't be a problem if we migrate to GitHub Actions.

**Comment by rachelcarmena** [comment]
This issue can be closed. We're already receiving emails from `notifications@github.com` when a build fails.

**Comment by pakoito** [comment]
Boop!

**Comment by aballano** [comment]
@arrow-kt/maintainers Please check that you're successfully receiving emails about failures in your PRs and feel free to reopen this if there's any issue 👍

**Comment by i-walker** [comment]
I'll close the issue once this is resolved.

**Comment by rachelcarmena** [comment]
Besides email notification, we'll add issue creation in case of error for the new arrow organization.

**Comment by i-walker** [comment]
Thanks @rachelcarmena ! 😄
