### ISSUE TITLE
[Documentation] Check Algolia configuration

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/arrow#1731]
It seems it's necessary to re-index the content in the website because Algolia service doesn't find results for **Data Types**.

For instance: 

![Screenshot from 2019-10-22 10-11-18](https://user-images.githubusercontent.com/22792183/67268564-0e702800-f4b5-11e9-88e6-27d55d09c347.png)

However, there is a page for `Kleisli`:

![Screenshot from 2019-10-22 10-12-17](https://user-images.githubusercontent.com/22792183/67268566-0e702800-f4b5-11e9-86fd-2a3c285cffce.png)

It works properly for **Optics**:

![Screenshot from 2019-10-22 10-12-41](https://user-images.githubusercontent.com/22792183/67268567-0e702800-f4b5-11e9-86e0-6afb932996ba.png)

and there is a page about it:

![Screenshot from 2019-10-22 10-13-17](https://user-images.githubusercontent.com/22792183/67268568-0f08be80-f4b5-11e9-99a3-c1cb32970390.png)

**Comment by calvellido** [comment]
The crawling occurs once a day, scheduled by the free service offered by Algolia.

What we should review is the way this crawling is happening at the moment. Actually, we should be probably reviewing it once we have the new site design in place.

This is our current config file:

https://github.com/algolia/docsearch-configs/blob/master/configs/arrow.json

And here it is some documentation about how to configure it:

https://community.algolia.com/docsearch/how-do-we-build-an-index.html
https://community.algolia.com/docsearch/required-configuration.html
https://community.algolia.com/docsearch/config-file.html

**Comment by rachelcarmena** [comment]
Hi! New issue from KotlinLang slack.

When looking for `ListK`, the result is: 

* https://arrow-kt.io/docs/arrow/data/listk/#listk

However, the right link is:

* https://arrow-kt.io/docs/apidocs/arrow-core-data/arrow.core/-list-k/

**Comment by rachelcarmena** [comment]
I changed the title because re-index happens once a day as @calvellido commented :+1:

**Comment by calvellido** [comment]
This has been now fixed with the awesome support of the Algolia team:

https://github.com/algolia/docsearch-configs/blob/7eee192dbcc19f791989c48839421cf1512e30b6/configs/arrow.json

:raised_hands: :raised_hands:

**Comment by rachelcarmena** [comment]
Thanks @calvellido !!! :tada:
