### ISSUE TITLE
Short circuit foldable operations

### ISSUE THREAD

**Issue by 1Jajen1** [arrow-kt/arrow#1734]
Currently a call to `firstOption` for example forces the entire fold to go through, which is especially bad if it is infinite (this has bitten me more than once with sequences...). This is unnecessary and should be easy to fix by short circuiting in right folds.

Any opinions?

Edit: The only method that does not use a right-fold (and the one firstOption is implemented with) is `get`. Changing that to a right fold will do the trick

**Comment by pakoito** [comment]
Sounds like a job for `tailrecM` and `traverse` :D

**Comment by 1Jajen1** [comment]
Hmm, it does need something other than `foldRight` because thats not gonna work for infinite sequences. `get` needs a left fold implemented using eval (similar to the right fold). Does that exist somewhere already?

**Comment by pakoito** [comment]
so what you want is a `traverse` that starts from the right? hmmmm

**Comment by 1Jajen1** [comment]
if we were in `Traversable` then yes, traverse with Option would work just fine, but in foldable not so much. (Also depends on Traversable's implementation for possibly infinite structures)

`get` just needs to return as soon as it hits its index and not continue folding the rest of the structure, which is what it is doing right now. 

Also I just noticed, all first/firstOrNull methods from the stdlib (for sequences) return the first matching element, whereas firstOption with a predicate returns only the first element if it matches. Kinda weird as well.

**Comment by 1Jajen1** [comment]
So the only two implementations I can think of to accomplish this, within Foldable, are:
- add a foldLeft variant with Eval
- throw an exception with the result inside foldLeft -> catch it and return it

The first one is definitly better, but forces all foldables to implement yet another method (but maybe we can implement the current foldLeft with the new one to make this less painful. This would also be great for a right fold without eval)

**Comment by pakoito** [comment]
I'd go back to scala cats/scalaz and try to find if there's an equivalent. It rings a bell as a different typeclass tbh. Hoogle the signature maybe?

**Comment by 1Jajen1** [comment]
I think it's a problem with missing lazyness, haskell cannot have that issue. Not really familiar with cats/scalaz, but I'll try

**Comment by 1Jajen1** [comment]
Current `get` is based on cats, scalaz is similar. Both are not lazy folds, which makes it unusable on infinite sequences sadly. Another, unsatisfying, solution would be to just specialize `get` for `Sequence`. But then again that sucks, because if `get` would be lazy all `Foldables`, finite or not, would benefit from it

**Comment by 1Jajen1** [comment]
Closed via #1816
