### ISSUE TITLE
[Ank] Add gradle deps on plugin

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow#1758]
What version are you currently using?

Gradle plugin: 0.7.1 and Arrow-ank version: 10.0.2

What would you like to see?

Automatically add Ank's runtime dependency when adding the Gradle plugin, or fix requirement of having to add the dependency to the docs modules.

Currently, when importing `Ank` through the Gradle plugin you still need to manually add the runtime dependency of `compile "io.arrow-kt:arrow-ank:0.10.2"` in order for the Gradle command `runAnk` to actually work.

Otherwise, Gradle will crash with a `main` not found exception since the runtime dependency is not added by the Gradle plugin.

**Comment by JorgeCastilloPrz** [comment]
10.0.2?

**Comment by nomisRev** [comment]
It gets deployed together with Arrow. Just pulled it from maven.

**Comment by JorgeCastilloPrz** [comment]
Yep I mean it's a typo :D

**Comment by i-walker** [comment]
If I understood this issue correctly @rachelcarmena fixed that in https://github.com/arrow-kt/arrow/pull/1936 🎉 , if you agree @nomisRev. 
Shall we close this issue?

**Comment by rachelcarmena** [comment]
Thanks @i-walker !! Right, that pull request should fix it :+1:

**Comment by rachelcarmena** [comment]
Solved via  #1936
