### ISSUE TITLE
Make retrofit module compatible with Android API 21

### ISSUE THREAD

**Issue by aballano** [arrow-kt/arrow#1761]
The retrofit module seems to be using some Java APIs only available on Android 28, which could potentially cause a crash when used on lower ones, see:

|Java API|Used in|Android API level|
|:-----:|:-----:|:-----:|
|[`getTypeName` on `java.lang.reflect.Type`](https://developer.android.com/reference/java/lang/reflect/Type#getTypeName())|`arrow-integrations-retrofit-adapter` in `CallKindAdapterFactory.kt`|28

_Originally posted by @junron in https://github.com/arrow-kt/arrow/pull/1751#issuecomment-547797475_

**Comment by junron** [comment]
Hmm according to Android documentation linked above,
> Implementation Requirements:
> The default implementation calls toString.
This seems like an easy fix then!
