### ISSUE TITLE
Extfun to go from Either to IO

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1777]
In IO.kt or the io instances file: https://github.com/arrow-kt/arrow/blob/master/modules/fx/arrow-fx/src/main/kotlin/arrow/fx/extensions/io.kt

```
fun <E, A> Either<E, A>.toIO(f: (E) -> Throwable): IO<A> = 
  fold({ IO.raiseError(f(it)) }, IO::just)

fun <A> Either<Throwable, A>.toIO(): IO<A> = 
  toIO(::identity)
```

This function helps people with mixed stacks of `suspend () -> Either` and `IO`

**Comment by abendt** [comment]
i'd like to try that. will create a PR

**Comment by pakoito** [comment]
Done and completed! Thank you @abendt !

**Comment by abendt** [comment]
that was quick :-) happy to help
