### ISSUE TITLE
Try is deprecated in the source code, but the documentation on the website does not talk about it

### ISSUE THREAD

**Issue by Jiehong** [arrow-kt/arrow#1786]
Hello,

We can see that `Try` is deprecated (https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-core-data/src/main/kotlin/arrow/core/Try.kt#L577), but the website documentation about it does not reflect that: https://arrow-kt.io/docs/arrow/core/try/#try

This leads to a dissonant communication IMO.

The website should reflect this point correctly I think.

Note that is seems to force you to use coroutines now, which is not a non-breaking translation.

**Comment by calvellido** [comment]
Hi @Jiehong, thanks for pointing this out.

This is now fixed.

The docs are released along each Arrow stable release, in the case of _Try_ the latest stable release (0.10.2) didn't reflect that (it was actually a problem on the point where the _Try_ docs were located, as it should be [this](https://arrow-kt.io/docs/apidocs/arrow-core-data/arrow.core/-try/))

For the next release, that it can be checked already through [next.arrow-kt.io](https://next.arrow-kt.io) you can see that the deprecation notice is there already:

https://next.arrow-kt.io/docs/arrow/core/try/
https://next.arrow-kt.io/docs/apidocs/arrow-core-data/arrow.core/-try/

Thanks!

**Comment by Jiehong** [comment]
@calvellido : ah, thanks for the link!

**Comment by calvellido** [comment]
NP!  Feel free to submit any improvement that you find the documentation could have, thanks!
