### ISSUE TITLE
Move Const back with the other datatypes

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1789]
Const was historically part of the typeclasses module due to some circular dependencies. Now that we've merged data and typeclasses together in core, it can be moved back with the others :D

https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Const.kt

move to

 modules/core/arrow-core-data/src/main/kotlin/arrow/core/

and make sure that all the references to it in the docs reflect the change

**Comment by PhBastiani** [comment]
I found a literal string '' into the meta module !

A basic refactorig 
- seems ok for core, optics, ui, recursion,
- fails for free

> Task :arrow-free-data:compileKotlin
e: C:\Users\phbastia\IdeaProjects\arrow\modules\free\arrow-free-data\src\main\kotlin\arrow\free\FreeApplicative.kt: (68, 62): Type mismatch: inferred type is Kind<ConstPartialOf<M> /* = Kind<ForConst, M> */, A> but MonoidOf<A> /* = Kind<ForMonoid, A> */ was expected
e: C:\Users\phbastia\IdeaProjects\arrow\modules\free\arrow-free-data\src\main\kotlin\arrow\free\FreeApplicative.kt: (68, 62): Type mismatch: inferred type is Monoid<A> but Const<M, A> was expected
e: C:\Users\phbastia\IdeaProjects\arrow\modules\free\arrow-free-data\src\main\kotlin\arrow\free\FreeApplicative.kt: (68, 68): Type inference failed: fun <A> MonoidOf<A#1 (type parameter of arrow.typeclasses.fix)> /* = Kind<ForMonoid, A#1> */.fix(): Monoid<A#1>
cannot be applied to
receiver: Kind<ConstPartialOf<M> /* = Kind<ForConst, M> */, A#2 (type parameter of arrow.free.FreeApplicative.analyze.<no name provided>.invoke)>  arguments: ()
> Task :arrow-free-data:compileKotlin FAILED

**Comment by pakoito** [comment]
Check the imports of the file, there may be an incorrect exfun or path around there.
