### ISSUE TITLE
[Bug] suspended causes an exception "Already resumed"

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1807]
As reported in: https://www.reddit.com/r/Kotlin/comments/dvzlv3/arrow_v0103_is_now_available_47_degrees/f7rru38/

Minimal use case: https://gist.github.com/paulosuzart/5e729697aad68ec453658b93ee61b880

In line 33, changing `val x = certainClient()` to `val x = certainClient().k().suspended()` causes `IllegalStateException: Already resumed`

**Comment by paulosuzart** [comment]
Thanks for opening the issue. 

This repo I used to reproduce the case.

By just doing a `curllocalhost:8080/parse?keys=124` should be enough to get the exception.

**Comment by aballano** [comment]
@paulosuzart Thank you for reporting! This issue should be fixed in the next version of Arrow 🙌

**Comment by paulosuzart** [comment]
That's awesome!! Just checked the changes, nice stuff. Thanks!!
