### ISSUE TITLE
Whitelist in detekt all generated files 

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#181]
I've recently added two suggestions for the processor that are based on the fact that we run detekt over generated files. Maybe the solution should be that detekt shouldn't run on generated files at all, whitelisting them. I know how to whitelist for a rule, not for all of them,

https://github.com/kategory/kategory-annotations/issues/9
https://github.com/kategory/kategory-annotations/issues/13

**Comment by pakoito** [comment]
Depends on https://github.com/kategory/kategory/issues/272

**Comment by mkobit** [comment]
Some issues now is that if you run `./gradlew build`, and then another `./gradlew build`:

* build will fail on second execution of detekt
* detekt executions are never up-to-date

**Comment by pakoito** [comment]
It is a known issue, we always run clean builds and use commands other than build.

Updating detekt to the latest version added a bunch of issues and new behaviors we'd had to account for, so the current state was good enough.

If you'd like to help us update that'd be great.

**Comment by nomisRev** [comment]
Moved from Detekt to Ktlint.
