### ISSUE TITLE
Rename Applicative#map to #mapN

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1842]
We have `parMapN`, plus it's easy to confuse Applicative#map (constructor) with Functor#map (function)

**Comment by nomisRev** [comment]
@pakoito shall we mark `map` as deprecated in `0.10.x`?

I think this is a good time to do these things so we can add them to the deprecation cycle for `0.10.x` which will removes some of those hurdles towards 1.0 already.

**Comment by pakoito** [comment]
Yeah we can do both.
