### ISSUE TITLE
Doc versions links

### ISSUE THREAD

**Issue by AntonioMateoGomez** [arrow-kt/arrow#1869]
We need to fix the links to the stable and next version in the doc version sidebar dropdown.

Right now there are pointing to `https://arrow-kt.io/docs` and `https://next.arrow-kt.io/docs`, but that url doesn´t exist anymore in those versions. We will set them to `https://arrow-kt.io/docs/core` and `https://next.arrow-kt.io/docs/core`

**Comment by rachelcarmena** [comment]
> Right now there are pointing to `https://arrow-kt.io/docs` and `https://next.arrow-kt.io/docs`, but that url doesn´t exist anymore in those versions. We will set them to `https://arrow-kt.io/docs/core` and `https://next.arrow-kt.io/docs/core`

Thanks @AntonioMateoGomez !! And it also happens for Arrow Fx and Arrow Optics. Thanks!!

**Comment by calvellido** [comment]
This has been fixed at the server level, as a fix in the repo won't fix current behaviour until next Arrow release

**Comment by rachelcarmena** [comment]
> This has been fixed at the server level, as a fix in the repo won't fix current behaviour until next Arrow release

Thanks @calvellido !! It also happens for Arrow Fx and Arrow Optics and the menu for them is redirecting to Arrow Core now. Thanks mate!! :+1:

**Comment by AntonioMateoGomez** [comment]
Ok @rachelcarmena I´m on it to make every module point to its documentation
