### ISSUE TITLE
Change error handling tutorial to use a model different than nukes/bombs

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow#1873]
https://arrow-kt.io/docs/patterns/error_handling/

Places where this needs to change: 

https://github.com/arrow-kt/arrow/blob/04b28f462e5de576c029db8aa8cac35d6ac70c9e/modules/docs/arrow-docs/docs/_code/core-home-code.md
https://github.com/arrow-kt/arrow/blob/44bb3419febf2cafaae3812ffcd64a448b5c076f/modules/docs/arrow-docs/docs/docs/arrow-core/patterns/errorhandling/README.md
https://github.com/arrow-kt/arrow/blob/93091c50314b22b2589455bfa127b735ce2da7d2/modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/MonadError.kt

**Comment by rachelcarmena** [comment]
Closed via #1915
