### ISSUE TITLE
[Bug] rx2 Traverse/Foldable instances are not lawful

### ISSUE THREAD

**Issue by 1Jajen1** [arrow-kt/arrow#1882]
Uncovered by #1877 

For `ObservableK` and `FlowableK` foldable is implemented using `blockingGet`. Not too familiar with those types but isn't that equal to `unsafeRunSync` in terms of semantics? Either way this fails when given errors and rightly so. We should remove those instances, they are not lawful. We could keep the combinators, but definitly not as part of `Foldable` or `Traversable`.

**Comment by abendt** [comment]
i think `FluxK` Foldable is affected too. It uses `block`
