### ISSUE TITLE
[Web] Code blocks are missing

### ISSUE THREAD

**Issue by deweyx** [arrow-kt/arrow#1887]
If I view the glossary on [Github](https://github.com/arrow-kt/arrow/tree/master/modules/docs/arrow-docs/docs/docs/arrow-core/patterns/glossary), I see code blocks in almost every section. On the [new site](https://arrow-kt.io/docs/patterns/glossary/), all code blocks are skipped on Firefox or Chrome.

E.g., in the Datatypes section, this block is not showing up.

```kotlin
import arrow.fx.*

IO { 0 }
 .flatMap { IO { it * 2 } }
 .map { it + 1 }
```

**Comment by calvellido** [comment]
They shouldn't be skipped, they rely on [Arrow Playground](https://github.com/arrow-kt/arrow-playground) to be shown. Do you use any Adblock, or JS blocking similar tool?  If you do you'd probably need to add an exception for Arrow Playground. If that's not the case, or you still can't see them, could you share the console on your browser when you go to that page?

**Comment by nomisRev** [comment]
@deweyx @calvellido I am seeing them fine on my machine on MacOs with Firefox & Chrome.
Both code blocks linked, and runnable snippets in other pages such as [Either](https://arrow-kt.io/docs/apidocs/arrow-core-data/arrow.core/-either/).

**Comment by deweyx** [comment]
It loads ok now, from one of my previous attempts last night, I see:

```
Failed to load resource: the server responded with a status of 429 ()
arrow-kt.io/:1 Unchecked runtime.lastError: The message port closed before a response was received.
```
