### ISSUE TITLE
[Add Media] Kompute Arrow-Meta Plugin

### ISSUE THREAD

**Issue by MikeDepies** [arrow-kt/arrow#1893]
Arrow-Meta Plugin
https://github.com/MikeDepies/Kompute

Description:
Kotlin Compiler plugin bringing reactivity to variable declarations. 

Author:
Michael Depies

**Comment by MaureenElsberry** [comment]
Hi @MikeDepies - this doesn't quite fit into the media section at the moment as it's a project and not blog/video/conference etc. but it's definitely cool, it was shared in our internal arrow slack :). 

We'll discuss where to best add a listing of projects/libs built with arrow and make sure this is added in the right spot! Thanks - and i'm just linking this reddit post for my reference here: https://www.reddit.com/r/Kotlin/comments/efy2ar/kompute_compile_time_reactive_variable/

**Comment by MikeDepies** [comment]
Excellent.

**Comment by pakoito** [comment]
Reopening as there's one place where it can be added: https://arrow-kt.io/docs/quickstart/projects/#katas-and-exercises

**Comment by MaureenElsberry** [comment]
Thanks @pakoito - Added.
