### ISSUE TITLE
[Bug]: Ank playgrounds are not runnable

### ISSUE THREAD

**Issue by i-walker** [arrow-kt/arrow#1908]
The Docs on the new webpage, don't show the run Icon for Ank:playground snippets. 
Here is one example: https://next.arrow-kt.io/docs/apidocs/arrow-core-data/arrow.core/-either/, though other docs show the same effect. 

Browser:
Safari Version 13.0.4 (15608.4.9.1.3)
Chrome Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by calvellido** [comment]
Oops, cert was expired. Fixed now :heavy_check_mark:
