### ISSUE TITLE
["Request"] Add monad-trans typeclass

### ISSUE THREAD

**Issue by 1Jajen1** [arrow-kt/arrow#1913]
MonadTrans is a typeclass that abstracts lifting arbitray monadic computations in another context. It is a necessity in mtl style programs as lifting becomes quite verbose if done manually for each type.

Note some instances might need to reorder the parameters of certain mtl types like `EitherT` otherwise it would make for a weird `MonadTrans` instance.

Basically port this + laws:
http://hackage.haskell.org/package/transformers-0.5.6.2/docs/Control-Monad-Trans-Class.html

**Comment by abendt** [comment]
i had a look at this and have some questions now:

first issue is regarding the laws:
i didn't fully understand how to make the first law work (http://hackage.haskell.org/package/transformers-0.5.6.2/docs/Control-Monad-Trans-Class.html). Is it the same as basic monad associativity laws? I assumed that and implement laws based on that as it was easier to understand: 
https://github.com/abendt/arrow/blob/monad_trans/modules/core/arrow-test/src/main/kotlin/arrow/test/laws/MonadTransLaws.kt#L35

second i was not able to come up with a typeclass interface that can be used with `OptionT` and  `EitherT`. Issue here is that `EitherT` is a `Kind3` and `OptionT` just `Kind2` and i didn't find a common type. for now i have created two typeclasses  (https://github.com/abendt/arrow/blob/monad_trans/modules/mtl/arrow-mtl-data/src/main/kotlin/arrow/mtl/typeclasses/MonadTrans.kt#L8) but i guess this is not the way to go.

**Comment by 1Jajen1** [comment]
For the first law imagine we have `MM = Monad<M>, MF = Monad<F>, MonadTrans<F>` then `MM.just(x).lift() == MF.just(x)`

`MonadTrans` takes a higher kinded type of arity 2 as a type. Those are, in arrow, the witness types `ForEither`, `ForOptionTPartial`, `EitherTPartial<L>` etc.

For example the lift instance for OptionT would be: `MonadTrans<ForOptionT>` and `fun <M, A> Kind<M, A>.lift(MM: Monad<M>): Kind3<ForOptionT, M, A> = OptionT.lift(MM, this)` or similar, not sure how the `lift` method  actually looks ^-^

There are problems tho: `EitherT` is defined as `EitherT<F, L, A>` wich means it has `Kind4<ForEitherT, F, L, A>` which is `Kind<Kind3<ForEitherT, F, L>, A>` and `Kind<Kind<Kind2<ForEitherT, F>, L, A>>`. This means it would have `MonadTrans<Kind2<ForEitherT, F>>` but that is bullshit because we want to abstract over `F` in `MonadTrans`. 

Imo this should be solved by redefining it as `EitherT<L, F, A>` similar to how haskell does it.

We have `Conest` which can skip a type (through unsafe type cast magic) but this is even uglier when the `F` that `Conest` is used with has arity > 2 and you want to skip types that are not the last type. This can be done, but needs more typecast ext functions. This is a really ugly hack imo.

**Comment by 1Jajen1** [comment]
If we do parameter reordering, then don't attempt this in one pr. I made that mistake with #1767 ^^ This should be discussed and changed on a case by case basis, so for now just adding `MonadTrans` with `ForOptionT` is fine.

**Comment by abendt** [comment]
> For the first law imagine we have `MM = Monad<M>, MF = Monad<F>, MonadTrans<F>` then `MM.just(x).lift() == MF.just(x)`

How do the types match here? to me it looks`MM.just(x).lift()` is of type `f m a` and `MF.just(x)` of type `f a`. How can then different types be equal?

> For example the lift instance for OptionT would be: `MonadTrans<ForOptionT>` and `fun <M, A> Kind<M, A>.lift(MM: Monad<M>): Kind3<ForOptionT, M, A> = OptionT.lift(MM, this)` or similar, not sure how the `lift` method actually looks ^-^

do you mean `Kind2<ForOptionT, M, A>` here? 

> If we do parameter reordering, then don't attempt this in one pr. I made that mistake with #1767 ^^ This should be discussed and changed on a case by case basis, so for now just adding `MonadTrans` with `ForOptionT` is fine.

ok, i will prepare another branch then

**Comment by 1Jajen1** [comment]
> How do the types match here? to me it looks `MM.just(x).lift()` is of type `f m a` and `MF.just(x)` of type `f a`. How can then different types be equal?

Yes `MF` needs to be `Monad<Kind<F, M>>` my bad :pray: 

> do you mean Kind2<ForOptionT, M, A> here?

:+1:

**Comment by abendt** [comment]
i have prepared the instance for OptionT now with tests. i will add a readme next and then open a PR

https://github.com/abendt/arrow/tree/monad_trans2

> Yes `MF` needs to be `Monad<Kind<F, M>>` my bad 🙏

ok, with that i could implement the law. 
however, i still have a hard time to understand the haskell definition: `lift . return = return` do the two returns here refer to different monads? how is this resolved?

**Comment by 1Jajen1** [comment]
> however, i still have a hard time to understand the haskell definition: lift . return = return do the two returns here refer to different monads? how is this resolved?

`lift . return` is resolved to `forall f m a. Monad m => MonadTrans f => a -> f m a` (by definition of lift and return) and the rhs is `forall m a. Monad m => a -> m a`. This is probably what the type of the both sides will be. Types in ghc are resolved at call-site, which means types are resolved as soon as you call it with a more specific type (that fits the requirements) (although by just trying all known types ghc could figure out all possible implementations as well, and it can do that already ^^). Using a ghc extension I could write: `(lift . return $ 0) :: MaybeT IO Int` and that would typecheck. I could also do `return @MaybeT IO` and get a type `forall a. a -> MaybeT IO a`. 

Oh and also remember these laws are not valid haskell code `lhs = rhs` won't compile because `=` does not exist and `==` won't work because there is no `Eq` instance for functions. Only when you have concrete types and no more partial application you can test them.

**Comment by 1Jajen1** [comment]
This can be closed. All mtl types now have a `MonadTrans` instance
