### ISSUE TITLE
["Bug"] next.arrow-kt.io does not load any code blocks

### ISSUE THREAD

**Issue by 1Jajen1** [arrow-kt/arrow#1918]
<title> @raulraja asked me to tag you two on slack :)

I am on arch-linux + brave (also happens on chrome)

**Comment by calvellido** [comment]
Yep, it seems they get broken after [this PR](https://github.com/arrow-kt/arrow/pull/1911) :disappointed:.

Thanks for reporting it @1Jajen1

**Comment by calvellido** [comment]
They are back now: https://next.arrow-kt.io/docs/aql/select/
