### ISSUE TITLE
Github stars

### ISSUE THREAD

**Issue by AntonioMateoGomez** [arrow-kt/arrow#1923]
We are going to bring back github stars to the new design.
In the future when we separate the Arrow modules in different repos, all libraries (Core, Optics, Incubator, Meta, Fx) should point to a single star count, that of the main arrow repo. When all libs are split out that repo will remain as the index of what is in the arrow org.

Besides we are going to implement a modal card that link to the Arrow stars.
![Captura de pantalla 2020-01-15 a las 15 00 27](https://user-images.githubusercontent.com/25897490/72439770-cdcc3600-37a7-11ea-9755-c35818244b76.png)

Once user closes it won´t appears anymore in that session so it won´t be anoying.

This must be implemented in every Arrow module. Here is the link to the Arrow Meta [issue](https://github.com/arrow-kt/arrow-meta/issues/416)

**Comment by jnorthrup** [comment]
I may be alone in measuring two different arrow sub-projects on the basis of their individual merits, and contributors as separate contributors, but I would definitely downgrade something that was 5 stars in all respects a star or two by conflating the projects, the contributors, all things as one point of publicity and likely classify this as purely commercial by any popup ratings dialogs.  I hope i speak only for myself in expressing these views, and not as any other viewer of the subprojects i have starred (this one is not, but it is self-explanatory why I am directed here).

**Comment by raulraja** [comment]
@jnorthrup feel free to downgrade your stars as you wish. 
Arrow is splitting from the monorepo where all stars were into many individual repos after two years and becoming a collection of libs that interoperate with each other but have a common purpose. The monorepo will be left empty after the split and as you can imagine we are not about to get rid of all those stars. The overall star count if possible will include all the repos of arrow in the site but you can still star individually each repo if you wish.

**Comment by AntonioMateoGomez** [comment]
Hi @jnorthrup , I have edited the issue description because I think it´s beign misunderstood.
