### ISSUE TITLE
Async and Concurrent Fx blocks aren't lazy

### ISSUE THREAD

**Issue by aballano** [arrow-kt/arrow#1977]
Similarly as for #1976, Async and Concurrent suffer from the same issue, which can potentially be avoided by deferring the coroutine evaluation. 

This would also allow removing specific defers on each instance for each data type as fixed in #1663

**Comment by pakoito** [comment]
Aren't they eager up to the first suspension point? IIRC it's always been intentional.

**Comment by aballano** [comment]
@pakoito I just moved the defer [from the specific instances](https://github.com/arrow-kt/arrow/pull/1663/files) to the async and concurrent roots so in case we add new types at a later point we don't need to remember to apply that fix again. Is there a reason why instances shouldn't be lazy if they support defer?

**Comment by pakoito** [comment]
`IO { }` and `later` are lazy constructors. `fx` opens a block with special syntax. Otherwise we could make `later` and `fx` be the same.

**Comment by aballano** [comment]
This is the current behaviour of IO [at the moment](https://github.com/arrow-kt/arrow/blob/master/modules/fx/arrow-fx/src/main/kotlin/arrow/fx/extensions/io.kt#L314). In any case I wouldn't expect as a dev that the fx block runs eagerly, although the test shows that this might probably be a misusage of if since that code should be wrapped in `effect` in the first place.

@arrow-kt/maintainers any thoughts?

**Comment by 1Jajen1** [comment]
In theory this should never be a problem because the eager evaluated code is assumed pure (otherwise it'd have to be warped in F anyway). However this behavior may still surprise people who don't adhere to this strictly. I kind of think my idea that I listed in the other issue, binding a unit at the start of each fx block may just be simpler until meta comes around, especially because that works over any monad and thus also mtl. Either way I am for solving this, or if not at least documenting this somewhere visible

**Comment by pakoito** [comment]
I don't remember if I was for or against unifying `fx` and `effect` 😁 (I said later before, I meant effect). I do remember the conversation and that there was a limitation. Maybe it was this differentiation of eager and lazy?

**Comment by pakoito** [comment]
cc @raulraja do you remember? was this about the Fink primitives?

**Comment by nomisRev** [comment]
The difference between `fx` is that `fx` enables special syntax for binding `!` and syntax.
And the difference between `!` and `suspend()` is that with `!` you don't leave `flatMap` and benefit from all benefits of `flatMap` while with `suspend()` you run the `IO` in a pure `suspend` context.
We do want it to run lazily for all capable monads, at least that's how I remember the conversation.

> was this about the Fink primitives?

I think I missed this completely tho
