### ISSUE TITLE
["Request"] Consider adding extra combinators to kotlinx-coroutines module

### ISSUE THREAD

**Issue by aballano** [arrow-kt/arrow#2021]
As per https://github.com/arrow-kt/arrow/pull/1939#pullrequestreview-351878183, some combinators (split into separate tickets if necessary):

* toJob
* toDeferred(?)
* fromJob

**Comment by aballano** [comment]
Currently the `suspendCancellable` extension function over IO in the new module covers the interop with Job and Deferred<T> as it can be used for both. Unfortunately it's not straightforward to move from Job to IO as the former is eager. 

Due to all this we're closing this ticket for now until we get an explicit request over a needed operator.

**Comment by nomisRev** [comment]
Thanks for the follow-up @aballano! Sounds perfect to me, can we add some examples in the documentation to cover? I'll add it to the documentation ticket.

> the suspendCancellable extension function over IO in the new module covers the interop with Job and Deferred as it can be used for both.
