### ISSUE TITLE
Create Wrapper class for SortedMap

### ISSUE THREAD

**Issue by Atternatt** [arrow-kt/arrow#205]

**Comment by krishnarb3** [comment]
Hello, I would like to take this up. Can you explain what exactly is to be done, I am new to this project.

**Comment by pakoito** [comment]
Hi @krishnarb3! Sure, the PR will be quite similar to the wrapper for regular maps. @victorg1991 completed that some weeks ago, so you can take a look at his job: https://github.com/kategory/kategory/pull/310/files

**Comment by victorg1991** [comment]
@krishnarb3 If you have any question about it I'll be happy to answer it :D

**Comment by krishnarb3** [comment]
Thanks both of you, I'm going through the operator and the PR. Will definitely ask you once I'm done 😁 @victorg1991

**Comment by krishnarb3** [comment]
Also do we have an irc/slack channel/mailing list for kategory?

**Comment by pakoito** [comment]
Yes, try https://gitter.im/kategory/Lobby!

**Comment by Cotel** [comment]
@krishnarb3 Are you still working on this Issue? I would like to take it if you dont mind 😄

**Comment by krishnarb3** [comment]
Sorry for the late response, i wasn't online for a while. 
Also amazing work on the PR, I'll look into some other issue that I can contribute to.
Cheers :D

**Comment by pakoito** [comment]
Completed by #451 . Thanks @Cotel !!!
