### ISSUE TITLE
[Bug] The current cobinding test uses a wrong assumption

### ISSUE THREAD

**Issue by 1Jajen1** [arrow-kt/arrow#2099]
Uncovered by arrow-kt/arrow#1844 . Currently `ComonadLaws` have a test for `cobinding` which assumes:
```kotlin
val x = fa.extract()
val res0 = fa.coFlatMap { it.map { it + x }.extract() }
val res = res0.map { it + x }

res == fa.map { it * 3 }
```
However this is only the case for one-element functors and easily fails for `NonEmptyList`. So the assumption this test builds on doesn't work, we need a new one.

**Comment by raulraja** [comment]
@1Jajen1 Closing this outdated issue as we no longer have these type classes in Arrow. Thanks for looking into it.
