### ISSUE TITLE
["Bug"] Dead links in documentation

### ISSUE THREAD

**Issue by tchupp** [arrow-kt/arrow#2120]
This may extend to other pages, but I found this one first;

The links under `Data types` should take you to the docs for each underlying data type, but they currently go the the wrong spot.
https://arrow-kt.io/docs/0.10/effects/effect/

For example, the `IO` link takes you to
`https://arrow-kt.io/docs/0.10/docs/apidocs/arrow-fx/arrow.fx/-i-o`.
I believe the expected destination is
`https://arrow-kt.io/docs/0.10/apidocs/arrow-fx/arrow.fx/-i-o`
or even
`https://arrow-kt.io/docs/apidocs/arrow-fx/arrow.fx/-i-o`

I'm happy to make a PR to fix this, but I was having trouble figuring out the repo structure 😅

Update:
I found another one
- `https://arrow-kt.io/docs/0.10/apidocs/arrow-core-data/arrow.core/-option/#supported-type-classes`
  - All the "type class" links have `/docs/0.10/docs/apidocs` instead of `docs/0.10/apidocs`
  - All the "functions" have correctly formed links

**Comment by rachelcarmena** [comment]
Thanks @tchupp :raised_hands: Let's wait for the next release because maybe it's fixed when release process finishes. I'll let you know when it's finished to check it again :+1: Thanks!!

**Comment by rachelcarmena** [comment]
Hi @tchupp , please, could you try it again? Please, take into account cache issues. 

It seems it's fixed when releasing `0.10.5` (`0.10` uses `0.10.5` docs instead of `0.10.4`):

```
$ curl https://arrow-kt.io/docs/0.10/effects/effect/ | grep apidocs
<a class="sidebar-menu-item " href="/docs/0.10/apidocs/arrow-fx/arrow.fx/-resource/" title="Resource">
<a class="sidebar-menu-item " href="/docs/0.10/apidocs/arrow-fx/arrow.fx/-schedule/" title="Schedule">
<a class="sidebar-menu-item " href="/docs/0.10/apidocs/arrow-fx/arrow.fx.typeclasses/-monad-i-o/" title="MonadIO">
<a class="sidebar-menu-item " href="/docs/0.10/apidocs/arrow-fx/" title="Effects">
<a class="sidebar-menu-item " href="/docs/0.10/apidocs/arrow-fx-mtl/" title="Effects MTL">
<a class="sidebar-menu-item " href="/docs/0.10/apidocs/arrow-fx-reactor/" title="Effects Reactor">
<a class="sidebar-menu-item " href="/docs/0.10/apidocs/arrow-fx-rx2/" title="Effects Rx2">
<td><a href="/docs/0.10/apidocs/arrow-fx/arrow.fx/-i-o">IO</a></td>
<td><a href="/docs/0.10/apidocs/arrow-fx-reactor/arrow.fx.reactor/-flux-k">FluxK</a>, <a href="/docs/0.10/apidocs/arrow-fx-reactor/arrow.fx.reactor/-mono-k">MonoK</a></td>
<td><a href="/docs/0.10/apidocs/arrow-fx-rx2/arrow.fx.rx2/-flowable-k">FlowableK</a>, <a href="/docs/0.10/apidocs/arrow-fx-rx2/arrow.fx.rx2/-maybe-k">MaybeK</a>, <a href="/docs/0.10/apidocs/arrow-fx-rx2/arrow.fx.rx2/-observable-k">ObservableK</a>, <a href="/docs/0.10/apidocs/arrow-fx-rx2/arrow.fx.rx2/-single-k">SingleK</a></td>
```

All the links show the format:
```
/docs/0.10/apidocs/<arrow-module>/...
```
instead of 
```
/docs/0.10/docs/apidocs/<arrow-module>/...
```

About trying to figure out the repo structure, so sorry, we're going to improve the documentation to make the contributions easier. 

Thanks again!!

**Comment by tchupp** [comment]
It works now! No need to clear my cache.
Was there a specific fix that removed the extra `/docs/`? I just want to understand how it was fixed so I - or anyone else looking at this - could do a similar fix in the future.

I think it makes sense to close this issue, since the specific links are all working now.

**Comment by rachelcarmena** [comment]
Great, thanks for your review! There wasn't a specific fix to remove that extra `/docs`. Documentation has been re-organized during `0.10.5-SNAPSHOT` version when locating all the docs for all the versions in just one S3 bucket. It was necessary to change some URLs to keep all the documentation in that new location.

Thanks again and... closing the issue! :tada:
