### ISSUE TITLE
[Request] Provide an example of migrating `Try` to `Either`

### ISSUE THREAD

**Issue by zvozin** [arrow-kt/arrow#2133]
What version are you currently using? `0.10.5`

What would you like to see? _A fairly detailed example of migrating the typical blocking use of `Try` to co-routined `Either`._  The migration isn't quite straight-forward, especially for people lacking previous exposure to co-routine arcana such as limited scopes.

**Comment by aballano** [comment]
We could use the [example here ](https://github.com/arrow-kt/arrow/issues/1644#issuecomment-680147586)

**Comment by nomisRev** [comment]
Closing this due to being stale. It's also possible now use `Result<A>` from Kotlin Std as replacement to `Try`.
