### ISSUE TITLE
[Request] Increase minimum JVM support to Java 8

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow#2138]
Currently, we have a target jdk of 1.7

From memory, I think this was done back in the day dues to compatibility with Android.

However, there is great support for Java 8 on Android (with some caveats).

We should we upgrade to Java 1.8, unless there are compelling reasons against it :)

**Comment by LordRaydenMK** [comment]
Popular Android libraries like [Retrofit](https://github.com/square/retrofit#download) and [OkHttp](https://github.com/square/okhttp/#requirements) already have the Java8 requirement.

I would guess most people doing Android already use one of those (directly or transitively) so Arrow's switch to Java8 would not impact apps.

The [Android docs for Java8](https://developer.android.com/studio/write/java8-support) for reference.
