### ISSUE TITLE
["Request"] Deploy test reports

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#2165]
It would be awesome if we could get the HTML test reports deployed somewhere by a GitHub Action, so we could easily inspect them using our browser. Finding failed tests in logs became a bit tricky given the amount of warnings at this point.

This would be cool to have for all the Arrow repositories.

**Comment by rachelcarmena** [comment]
Super useful, for sure, thanks!! Please @JorgeCastilloPrz , take a look at https://github.com/arrow-kt/arrow-fx/pull/202

It includes a screenshot and a link as an example.

**Comment by rachelcarmena** [comment]
If it's useful, I'll add it to the rest of libraries.

**Comment by rachelcarmena** [comment]
Added to the rest of libraries.

**Comment by rachelcarmena** [comment]
The reports can be downloaded from the action execution. Deploying them would add additional tasks to remove those temporary deployments. Please bud, reopen in case it doesn't work for you :pray:
