### ISSUE TITLE
Actions: cancel running actions when pushing new commits

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/arrow#2185]
## Context

The number of running actions at the same time is limited and a lot of checks are queued.

When someone accepts suggestions, the number of commits increase and checks are queued for every commit.

It would be necessary to cancel the running checks with new commits into the same branch automatically.

**Comment by rachelcarmena** [comment]
Following this request: https://github.community/t/stop-running-actions-when-new-commit-pushed-to-branch/16455

**Comment by raulraja** [comment]
@rachelcarmena, is this issue still relevant, or can we close it? Thanks!

**Comment by nomisRev** [comment]
@raulraja I think we're still waiting on Github to release this feature, but it's something that we'd love to set up. See the link Raquel shared.
