### ISSUE TITLE
["Request"] Make individual tasks in installAllWithLocalDeps optional or offer installWithLocalDeps instead

### ISSUE THREAD

**Issue by 1Jajen1** [arrow-kt/arrow#2186]
Currently executing `installAllWithLocalDeps` requires a lot of libraries to be built, which is fine except that those may have additional requirements, for example the `arrow-android` module requires the android-sdk to be present.

If we instead had a task which specialized for `buildWithLocalDeps` only installs the deps necessary or skips failing installs we would no longer have that requirement. Of course building the actual module should still fail if a actual dependency was skipped, but in those cases the extra requirements have to be installed anyway.

**Comment by nomisRev** [comment]
Closing this due to this becoming legacy. We no longer need these commands.
