### ISSUE TITLE
["Request"] Migrate Kotlintest to Kotest

### ISSUE THREAD

**Issue by aballano** [arrow-kt/arrow#2187]
https://github.com/arrow-kt/arrow/pull/2180
https://github.com/arrow-kt/arrow-core/pull/188
https://github.com/arrow-kt/arrow-fx/pull/231
https://github.com/arrow-kt/arrow-optics/pull/61
https://github.com/arrow-kt/arrow-incubator/pull/123
https://github.com/arrow-kt/arrow-integrations/pull/38
https://github.com/arrow-kt/arrow-check/pull/25
https://github.com/arrow-kt/arrow-examples/pull/7
https://github.com/arrow-kt/arrow-ui/pull/38

**Comment by rachelcarmena** [comment]
Reason: https://github.com/arrow-kt/arrow-core/pull/149#issuecomment-658322479

**Comment by nomisRev** [comment]
Closed by #2405
