### ISSUE TITLE
Move to use kts (slowly) in Gradle

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow#2190]
What version are you currently using?

0.11-SNAPSHOT

What would you like to see?

Kts Gradle support is getting better every day. Especially, with the extra support they are getting with Kotlin 1.4 and the introduction of [configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html).

So this ticket is to discuss what the team thinks about moving slowly towards the use of kts from the build scripts. I'm happy to own it and solve any problems that may arise (if any).

Working with build files in Kotlin is easier given that it is more typed, has better autocomplete and allows us to navigate to the source (which encourages editing of build scripts). 

It doesn't need to be done all at once, we can do bit by bit, and we can postpone it to a later stage if we think it's a bit risky at the moment.

Does anyone have any good objections? :)

**Comment by rachelcarmena** [comment]
Thanks @pablisco, good idea!! Here I am to help with any doubt about the current configuration :raised_hands:

**Comment by nomisRev** [comment]
Now that 1.0 is released, I think it's a good time to start tackling this.

I want to open this issue with a discussion 😅 (sorry)
Ideally, I think we should use [dependabot](https://dependabot.com/) to get automatic version updates by PR, but this is also possible if we use a regular version inline in the code. I think perhaps `ext.version` is also supported but we'd need to double check.

This could remove the maintenance effort of keeping version up to date.

**Comment by nomisRev** [comment]
I have an automatic dependency updating bot set up in [Saga](https://github.com/nomisRev/Saga) and it works very well. This will prevent us from having to manually update the version again.

**Comment by nomisRev** [comment]
Ideally, we would also get rid of the bash scripts if we can replace them with Kotlin Scripts that run from Gradle directly. This would be easier to deal with across platforms.

**Comment by i-walker** [comment]
We can write a specific issue for the bash scripts, but most of the tasks have been superseded with https://github.com/arrow-kt/arrow-gradle-config
