### ISSUE TITLE
Revalidate Readme's module config

### ISSUE THREAD

**Issue by aballano** [arrow-kt/arrow#2207]
This might come handy to save the users from self-importing this themselves, although I'm wondering if [this guide in the arrow readme](https://github.com/arrow-kt/arrow/blame/master/README.md#L105) was then accurate to the previous state 🤔  

I think we should check that document and validate if it's correct (for example arrow-optics doesn't seem to expose core, yet core doesn't appear in the readme for  optics)

_Originally posted by @aballano in https://github.com/arrow-kt/arrow-core/pull/224#discussion_r476494297_

After this PR is merged we should revisit the module guide to validate the config and add/remove modules if necessary

**Comment by rachelcarmena** [comment]
Awesome idea @aballano :raised_hands: Here the dependencies graph before the split: [arrow-dependencies](https://user-images.githubusercontent.com/22792183/91190907-6b9bc200-e6f4-11ea-8b16-ecdabb81823b.png)

**Comment by rachelcarmena** [comment]
Pending improvement after https://github.com/arrow-kt/arrow-core/pull/224: Arrow Optics should add Kotlin Standard library to compile so it will be able to be removed from Arrow Annotations as exported to consumers.

**Comment by nomisRev** [comment]
@i-walker @aballano can this issue be closed?
