### ISSUE TITLE
["Discussion"] Arrow Infra Gradle Plugin deployment

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow#2220]
I was testing the use of Kotlin for Gradle, as part of #2190, on a branch on `arrow-incubator` and I came across a problem regarding applying the [`gradle/settings.gradle`](https://github.com/arrow-kt/arrow/blob/master/gradle/settings.gradle) script. The IDE would not recognise the extension for automodule in [`settings.gradle`](https://github.com/arrow-kt/arrow-incubator/blob/master/settings.gradle#L6).

Given that, I'm playing around with the idea of packing the scripts that we have here inside a Gradle Plugin (`arrow-gradle-infra`) that we can use on all the arrow repositories. These are some of the benefits of this conversion:

 -  It should ease the transition to using Kotlin with Gradle. 
 - We can provide versioning to the build script. This, in theory, could simplify the way we upgrade each repository to newer versions and scripts, as we can do them individually. I'm not 100%, maybe @rachelcarmena or @aballano may have more of an inside on the deployment and upgrade process.
 - We don't require to download the scripts on each build, which is what happens at the moment.

This plugin has to be deployed somewhere so the other repositories can make use of it. So, there are a few options:

1️⃣ Deploy to a local artifact repository inside the git repository. It means we have to manually reference it inside each `settings.gradler[.kts]`. Also, we can either create a PR with the release with the new version or create a GitHub action that generates a new commit with each merge to master. The first one is a bit error bound and the second one may add a bit too much noise.

2️⃣ Deploy to Github Packages. This one is a bit more scalable than 1️⃣ but requires a bit more work.

3️⃣ Use Composite builds. Another option could be to check out the infra plugin locally and add it as a composite build (`includeBuild`). This is something I am planning to do as part of automodule, but it's not quite there yet.  This would mean that we loose versioning plus the script will have to check for a new version of the plugin. Adding an extra check.

4️⃣ Deploy to the Gradle Plugin Portal. This will mean that minimal set up is necessary on other repos. We just need to register with them and drop the API keys on Github Secrets to use it in Github Actions. We will need to hold the keys locally for the first release so they can validate the deployment.

Let me know which one do you all prefer 😃

**Comment by pablisco** [comment]
Here is a sneak peak of how it's looking like:
![image](https://user-images.githubusercontent.com/260697/93633329-b43e5680-f9e6-11ea-9e96-5b3f401bb661.png)

**Comment by rachelcarmena** [comment]
@pablisco and I talked about it :raised_hands:  and we'll wait after `1.0.0` for this change to prioritize other improvements. Thank you so much @pablisco !!

**Comment by pablisco** [comment]
Probably not relevant now that we have a single repo again. Closing :)
