### ISSUE TITLE
Bump ktlint version

### ISSUE THREAD

**Issue by danimontoya** [arrow-kt/arrow#2228]
Bump ktlint version in order to support fun-interfaces, trailing commas... It's being done only for core so far:
https://github.com/arrow-kt/arrow-core/pull/248

**Comment by raulraja** [comment]
Hi @danimontoya! Is this still relevant, or can we close it? Thanks!

**Comment by nomisRev** [comment]
Still relevant. We're on `0.39.0`, and KtLint is `0.42.0`.

We continuously want to do this, since they keep updating with new features such as mentioned above.
Support for `value class` is also something we're interested in.

**Comment by danimontoya** [comment]
👍 I think updating Ktlint would be a continuous thing to do.. even tho its still relevant, I would close this because that work got merged.. and I would open a new issue when needed. But up to you folks :))

**Comment by nomisRev** [comment]
Closing this since we'll need to do this on a regular basis.
