### ISSUE TITLE
Out of date documentation for monad comprehensions?

### ISSUE THREAD

**Issue by Sintrastes** [arrow-kt/arrow#2239]
Looking at the [current documentation](https://arrow-kt.io/docs/patterns/monad_comprehensions/) for arrow on monad comprehensions, it says:

    Arrow uses this capability of the compiler to bring you coroutines-like notation to all instances of the Monad typeclass.

    This means that comprehensions are available for Option, List, Reader, Observable, Flux, or IO all the same.

As well as:

    Every instance of Monad contains a method binding that receives a suspended function as a parameter.

However, the documentation then goes on to use the extension `IO.fx` (rather than IO.binding), and looking at the generated kapt code when I have implemented my own monads using arrow (using a `@extension` interface), I do not see either such methods generated for the companion object of my monad, or the monad class itself.

Does monad comprehension in fact work for all monad instances? If so, it seems as if the arrow documentation is not accurate, if I'm not missing anything here. If not, is there something else one has to do to enable monad comprehensions with arrow?

**Comment by pakoito** [comment]
You're right, it was written for a handful of versions ago. I believe a pass is overdue alongside the 0.12 release, with top-level function + bind syntax :D

**Comment by Sintrastes** [comment]
@pakoito So I assume it is not in fact true that every monad in arrow can use comprehension syntax out of the box?

I found a work-around for now, as my custom monad is essentially isomorphic to `ReaderT<Ctx, ForIO, A>`  (for a type Ctx I have defined), so I can use monad comprehension syntax now by manually translating from `MyMonad<A>` back and forth to `ReaderT<Ctx,ForIO, A>`, but I'd still prefer to be able to use the monad comprehension syntax directly for my own monad.

Is [this](https://www.youtube.com/watch?v=0_zatebXMDU&feature=youtu.be) a good resource for how arrow currently does things?

**Comment by pakoito** [comment]
>So I assume it is not in fact true that every monad in arrow can use comprehension syntax out of the box?

Oh, that part is true. It's just the syntax that's changing over time. And I believe 1.0 is dropping HKTs for functional interfaces (? @raulraja @nomisRev )

**Comment by raulraja** [comment]
@Sintrastes @pakoito I missed this issue, but a while back, the monad tutorial got an update based on suspend and Either. Closing this one. Thanks!

**Comment by Sintrastes** [comment]
@raulraja Yes, I've been making good use of the new approach to monad comprehension. Thanks!
