### ISSUE TITLE
Examples Roadmap

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#225]
Description TBD

Libraries:
https://gist.github.com/i-am-tom/6eb66e40549cd161833db680103728d0 (Requieres recursion schemes)

**Comment by raulraja** [comment]
@pakoito github projects are limited for orgs like kategory, we should use instead waffle.io which is free and supports single board for multirepositories. For example https://waffle.io/frees-io/freestyle

**Comment by raulraja** [comment]
Closing old, outdated issue as the workload supervision of Arrow is mostly managed by @marfacio, and others in ClickUp and GitHub projects are not in use now. Thanks @pakoito
