### ISSUE TITLE
arrow-typeclasses 0.9.0 is incompatible with arrow-core-data 0.11.0

### ISSUE THREAD

**Issue by BaekGeunYoung** [arrow-kt/arrow#2271]
I'm using arrow-typeclasses 0.9.0 & arrow-core-data 0.11.0, and the following error happens.

```kotlin
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class arrow.typeclasses.MonadContinuation, unresolved supertypes: arrow.core.Continuation
```

when I change the version of arrow-core-data to 0.9.0, then there is no more error anymore. But I want to use arrow-core-data 0.11.0, which is the recent version.

What am I doing wrong? Or is this a bug?

**Comment by rachelcarmena** [comment]
Hi @BaekGeunYoung 

Thanks for your interest :raised_hands:

All the Arrow libraries should have the same version to ensure their working.

Since `0.11.0` version, a BOM file was added to avoid that issue: https://github.com/arrow-kt/arrow/blob/master/arrow-stack/README.md

Best regards!

**Comment by rachelcarmena** [comment]
By the way, `0.12.0` and `0.13.0` versions are going to be released very soon (last 2 versions before `1.x`) in case you want to wait for upgrading your libraries.

**Comment by BaekGeunYoung** [comment]
@rachelcarmena 
yeah I'm already using that BOM file, but it seems that there is no dependency of `arrow-typeclasses` in `arrow-stack` BOM file.
furthermore, I cannot see `arrow-typeclasses` 0.11.0 in maven repository, so I could not help using 0.9.0 of `arrow-typeclasses`, which is the latest version published in maven repository.

**Comment by rachelcarmena** [comment]
Oh, sorry, I missed that detail :pray:  That library was replaced by `arrow-core-data`.
