### ISSUE TITLE
Bintray is being sunsetted and the readme points to it

### ISSUE THREAD

**Issue by anjosc** [arrow-kt/arrow#2305]
Bintray is being sunetted as mentioned here: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
But the readme still suggests adding maven { url "https://dl.bintray.com/arrow-kt/arrow-kt/" } even though packages are already in maven central.
The reference to bintray should just be removed.

**Comment by rachelcarmena** [comment]
Hi @anjosc , thanks for the warning! Arrow will remove it after `0.12.0` and `0.13.0` releases.

It's also necessary to upgrade Dokka because the current version depends on `jCenter` to find a dependency.

Thank you so much again!

**Comment by rachelcarmena** [comment]
Thanks @anjosc again :raised_hands: That reference doesn't exist now. 

More improvements will be done very soon because of that sunset. Thanks!
