### ISSUE TITLE
["Request"] Add documentation and examples for CircuitBreaker

### ISSUE THREAD

**Issue by aballano** [arrow-kt/arrow#2314]
What would you like to see?

I think it'll be useful having some docs and specially examples of usages

**Comment by i-walker** [comment]
A duplicate from https://github.com/arrow-kt/arrow-fx/issues/367
We could transport them here

**Comment by aballano** [comment]
@i-walker Indeed! I assumed we would have already moved all issues to this repo when the migration was done 😅

**Comment by nomisRev** [comment]
cc\\ @rachelcarmena

**Comment by nomisRev** [comment]
Closed by #2460
