### ISSUE TITLE
Adding Instil Arrow Course Outline to Website

### ISSUE THREAD

**Issue by garthgilmour** [arrow-kt/arrow#2317]
Following discussions with @raulraja I have created an outline for an Arrow training course and added to the Instil website:

https://instil.co/courses/functional-programming-in-kotlin-with-arrow/

Would it be possible for this to be added to the training section of the Arrow site? Happy to supply any extra information required, although for corporate info on Instil our marketing director Zarah (zarah.akilagun@instil.co) is the best contact. 

CC @rachelcarmena

**Comment by raulraja** [comment]
Thanks, @garthgilmour! This is addressed in https://github.com/arrow-kt/arrow/pull/2376, which is being reviewed and will be published sometime next week
