### ISSUE TITLE
["Request"] Support KSP

### ISSUE THREAD

**Issue by fondesa** [arrow-kt/arrow#2358]
Currently Arrow uses KAPT.

[KSP](https://github.com/google/ksp) offers an alternative to KAPT which can speed up the build times because it doesn't need to generate the stubs.

**Comment by raulraja** [comment]
Hi @fondesa, we are eliminating all instances of Kapt to make Arrow multiplatform. The last remaining processor, the optics processor it's being ported to become a compiler plugin based on Arrow Meta.

**Comment by fondesa** [comment]
Thanks for answer, nice to know!
