### ISSUE TITLE
["Request"] Review `suspend () -> A` "Safety / Purity / Referential transparency" docs

### ISSUE THREAD

**Issue by aballano** [arrow-kt/arrow#2359]
In the latest version there's [this section](https://arrow-kt.io/docs/effects/io/#safety--purity--referential-transparency) in the suspend docs which I think incorrectly mentions how suspend functions are executed or what do they return, at least regarding their most common way of use.

**Comment by nomisRev** [comment]
Could you be more precise on what do you think is incorrect?

**Comment by aballano** [comment]
> suspend always results in Result<A> 

This is not like this at least for the vast majority of users using coroutines.

> So the suspend API can also always return any exception safely to the user, and it can be recovered from at any point in the code. 

I'm not sure about the "safely" part here as they're thrown unless the user catches them

> we can only find startCoroutine in the standard library and it’s isomorphic to unsafeRunAsync.

This is not the way for launching coroutines, so making an example out of it is not correct I'd say

**Comment by nomisRev** [comment]
You're speaking strictly in terms of KotlinX Coroutines @aballano whilst the doc is strictly in terms of what the behavior is of `suspend` of the Kotlin Standard Library / Language point of view.

Whatever KotlinX Coroutines does was manually implemented that way by the library, but it's not what Kotlin provides out-of-the-box.

**Comment by aballano** [comment]
> Maybe that's worth clarfying in the docs.
That's what I meant all along 😅 

I can elaborate more:

What's confusing for me is that the docs are explaining the differences from IO vs suspend mainly **from the consumer point of view**, therefore the examples shown. So then in this specific section

>IO<A> always results in Either<Throwable, A> whether we run it with unsafeRunSync (throws Throwable), unsafeRunAsync or unsafeRunAsyncCancellable. This is done so that any exceptions that occur within the IO API can be safely returned to the user, and it can be recovered from at any point in the code. Important here is that a Throwable that occurs in an async thread is safely captured in the IO as well and can be recovered from at any point.

we talk about using unsafeRunXXX with IO, but then for the suspend in the next paragraph we talk about the behaviour of suspend in the stdlib, as you say, comparing it directly, and that's where I get a bit lost, why are we comparing a consumer API with the suspend stdlib API if they don't serve the same purposes?

>suspend always results in Result<A> which is isomorphic to Either<Throwable, A>, and it can be used to offer the same safety guarantees as IO. So the suspend API can also always return any exception safely to the user, and it can be recovered from at any point in the code. In contrast to IO, we can only find startCoroutine in the standard library and it’s isomorphic to unsafeRunAsync. Instead of f: (Either<Throwable, A>) -> Unit you provide f: (Result<A>) -> Unit to run the suspend () -> A program.

To me, this part is ok(ish) but is missing the consumer point of view, as per: how can I do the same as I was doing with IO? How do I wrap my errors in Result/Either without using APIs that I shouldn't use? Basically there are no mentions to `Either.catch` in that page whilst it's an important part when dealing with exceptions, so we may want to promote it

**Comment by nomisRev** [comment]
> without using APIs that I shouldn't use?

Which API shouldn't you use?
Not sure if you're referring to `startCoroutine` but it is in `kotlin.coroutines`, not in the special `intrinsics` package. https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.coroutines/
It's on `startCoroutine` is on the same level as `suspendCoroutine` which is `IO.async`.

Would be great if you could open a PR with the changes you think are needed, then we can get the improvement on the website asap instead of brainstorming here 👍

**Comment by aballano** [comment]
> Not sure if you're referring to startCoroutine

Yes, I mean that because AFAIK it's not meant to be used by consumers directly but via libs. At least I've never seen people or companies doing projects and using `startCoroutine` in their codebase as a general thing...

> Would be great if you could open a PR with the changes you think are needed, then we can get the improvement on the website asap instead of brainstorming here 👍

My idea was to discuss here if it would make sense to review the section because I do not have time at the moment to do such changes, so I wanted to bring this to the table, as we already discussed internally via slack, in case we think it makes sense to change something for clarification. 

This way I also won't block anyone willing to work on this in the meantime :)

Maybe others have some opinion on the docs? @raulraja @JorgeCastilloPrz Otherwise we can close this

**Comment by raulraja** [comment]
I also think that section can be improved to focus it more on suspend and its use cases and finalize comparing with IO. I agree at the moment it's not well oriented for the final end-user but rather to the FP programmer that was used to do IO which is the journey we have experienced. If we agree on a set of header points we want to showcase in this document I can write up some stuff or gather others that can help push the changes.
@aballano Would you like to list the main header points the document should include? I'll take it from there.

**Comment by nomisRev** [comment]
Closed by #2460
