### ISSUE TITLE
Optics annotation (arrow-meta) results in error in Kapt after migrating to 0.13.1

### ISSUE THREAD

**Issue by abdulkaderjeelani** [arrow-kt/arrow#2361]
[stack-trace-full.txt](https://github.com/arrow-kt/arrow/files/6248987/stack-trace-full.txt)

I migrated from 0.11 to 0.13.1, This is causing me error when I try to use optics in code In 0.11 the below snippet was generating the code seamlessly. Now results in Kapt compiler error. For complete stacktrace see the attached file.

**Snippet**
```
@optics
data class Product(val name: String)
```

**Error**
Execution failed for task ':kaptKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)

**Stacktrace:**
Caused by: java.lang.IllegalAccessError: Class org/jetbrains/kotlin/kapt3/base/KaptContext(unnamed module 0x00000000FF050E28) can not access class com/sun/tools/javac/util/Context(module jdk.compiler) because module module jdk.compiler does not export package com/sun/tools/javac/util to module unnamed module 0x00000000FF050E28

**Comment by abdulkaderjeelani** [comment]
@raulraja Should I rollback ?

**Comment by abdulkaderjeelani** [comment]
Also results in these errors !!
![image](https://user-images.githubusercontent.com/15631308/113407219-7de88780-93ca-11eb-90fc-de42971ec7d0.png)

**Comment by JorgeCastilloPrz** [comment]
Those errors seem correct, Kinds and those type classes and their extensions are removed in 0.13.1

**Comment by abdulkaderjeelani** [comment]
Does that apply to @optics annotation as well?

**Comment by JorgeCastilloPrz** [comment]
No, Optics should still work fine

**Comment by abdulkaderjeelani** [comment]
:(, I would pack a demo code with error in a public repo and share it here. I am quite sure I do not miss any fundamentals.

**Comment by rachelcarmena** [comment]
Thanks for your interest @abdulkaderjeelani and for sharing a repo to reproduce the error :raised_hands: 

The trace:

```
* What went wrong:
Execution failed for task ':kaptKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)
```

should show the clue before:

```
> Task :kaptKotlin FAILED
error: package not found
FAILURE: Build failed with an exception.
```

Please, add a package to solve it in `src/main/kotlin/main.kt` like:

```diff
+package example
+
 import arrow.optics.optics
```

And I think it won't work with OpenJDK 16 but 8.

Please, reopen if those things don't solve your issue. Thanks again!! :raised_hands:
