### ISSUE TITLE
["Request"] Either.toOption() is gone so code completion sugests A?.toOption() 

### ISSUE THREAD

**Issue by aballano** [arrow-kt/arrow#2374]
In the latest Arrow release it seems [`Either.toOption()`](https://github.com/arrow-kt/arrow-core/blob/master/arrow-core-data/src/main/kotlin/arrow/core/Either.kt#L945) was deprecated and removed, so after upgrading the version, the only function suggested is [`A?.toOption()`](https://github.com/arrow-kt/arrow-core/blob/master/arrow-core-data/src/main/kotlin/arrow/core/Option.kt#L998).

Before the problem **was** that the two functions can be easily mixed up as the option one is available for all types, including Either. The problem now is that there's no handy way anymore of converting an Either to an Option.

My suggestion would be to bring back `Either.toOption()` and rename the option one to `A?.asOption()` or something similar, to avoid confusions due to an import.

**Comment by myuwono** [comment]
There's a lot more type to Option conversion/extraction that got missing after the upgrade..

Ive also stumbled upon this during migration. We have to introduce many deleted functions locally as a lot of the `Option<A>` returning extensions are now missing. It's not the end of the world but i had to manually reintroduce for instance from the top of my head:
- `fun <R> Either<*, R>.orNone(): Option<R>` 
- `fun <A> List<Option<A>>.flatten(): List<A>`
- `fun <A> Collection<A>.find(predicate: (A) -> Boolean): Option<A>`
- `fun <K, V> Map<K, V>.getOrNone(key: K): Option<V>`
- some more that I can't remember..

**Comment by raulraja** [comment]
@aballano @myuwono thanks for bringing this up. I think these functions make sense but some of them should follow the new naming conventions we introduced. I think if we bring these back they should probably be called:
orNone -> (same)
flatten -> flattenOption
find -> firstOrNone
getOrNone -> (same)

**Comment by nomisRev** [comment]
Contribution very welcoem @myuwono 🙏

[`flattenOption`](https://github.com/arrow-kt/arrow/blob/2c3b3129a3ad0849055c84efc32c239f05ff4e98/arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/Iterable.kt#L896) already exists ;)

**Comment by myuwono** [comment]
Oh lol not sure if that name `filterOption` is intended

**Comment by nomisRev** [comment]
@myuwono I think the name `filterOption` was inspired by `filterNotNull` from Kotlin Std. https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/filter-not-null.html
