### ISSUE TITLE
["Bug"] Bad formatting in documentation

### ISSUE THREAD

**Issue by legzo** [arrow-kt/arrow#2379]
Hi, 

I just stumbled upon this in the docs :

![image](https://user-images.githubusercontent.com/113336/115781905-4d897d00-a3bb-11eb-89c2-1146c539a893.png)

I guess it should be :

![image](https://user-images.githubusercontent.com/113336/115781998-6abe4b80-a3bb-11eb-8ebb-8650f5919c12.png)

```
[`fold`](https://kotlinlang.org/docs/reference/collection-aggregate.html#fold-and-reduce)
```

It's really a small fix, but it's better than nothing  ¯\_(ツ)_/¯

**Comment by rachelcarmena** [comment]
All the contributions are welcome!! :clap: Thanks!!

**Comment by rachelcarmena** [comment]
The result of #2380 can be seen in the next version: https://arrow-kt.io/docs/next/optics/fold/

**Comment by legzo** [comment]
Feels strange to see my name alongside yours in the new version announcement tweet as I still struggle to understand 90% of the library, but I guess there are no small contributions and you have to start somewhere !

Thanks for your messages.

**Comment by rachelcarmena** [comment]
Thanks to you @legzo !! Your pull request appears in the release notes and Marketing team usually mentions the contributors. Welcome to Arrow :tada:
