### ISSUE TITLE
[BUG] Gradle configuration with platform("arrow-stack") does not work

### ISSUE THREAD

**Issue by jmfayard** [arrow-kt/arrow#2388]
**Describe the bug**
I am using the Gradle BOM to set dependencies versions, and I have a regression in version 0.13.2 where Gradle does not find the dependency

**To Reproduce**
1. Go to https://github.com/LouisCAD/kotlin-libraries-playground/blob/f3f8a227495f78a3f913c05c3da4d2369723c6f9/kotlin-codegen/build.gradle.kts#L18-L24

```
    // BUG: upgrading to 0.13.2 does not work https://gradle.com/s/46b4yz6jpglq4
    implementation(platform("io.arrow-kt:arrow-stack:0.11.0"))
    kapt("io.arrow-kt:arrow-meta:0.11.0")
    implementation("io.arrow-kt:arrow-core")
    implementation("io.arrow-kt:arrow-fx")
    implementation( "io.arrow-kt:arrow-syntax")
    implementation( "io.arrow-kt:arrow-optics")
```

2. Run gradlew :kotlin-codegen:build with version 0.11.0, it works
3. Update to Arrow 0.13.2 at line 19
4. See error https://scans.gradle.com/s/46b4yz6jpglq4/failure#1

```
> Could not resolve all files for configuration ':kotlin-codegen:compileClasspath'.
   > Could not find io.arrow-kt:arrow-fx:.
     Required by:
         project :kotlin-codegen
   > Could not find io.arrow-kt:arrow-syntax:.
```

**Expected behavior**
the BOM should work

**Environment (please complete the following information):**
 - Kotlin version 1.5.0, Gradle 7.0

**Comment by rachelcarmena** [comment]
Hi @jmfayard , 

Thank you so much for your interest!

`arrow-fx` was removed in 0.13.x (that version doesn't include a lot of the deprecated things in 0.12.x).

Please, find more details in this post by @nomisRev: https://www.47deg.com/blog/arrow-0.13.0-release/

And you can find more help in [#arrow channel on Kotlin Slack](https://kotlinlang.slack.com/messages/C5UPMM0A0) or [here](https://github.com/arrow-kt/arrow/discussions).

Thanks!!

**Comment by Marcono1234** [comment]
@rachelcarmena, could you please update the [`arrow-stack/README.md`](https://github.com/arrow-kt/arrow/blob/main/arrow-stack/README.md)? It still lists `arrow-fx` and `arrow-mtl` in the "Use" section.
