### ISSUE TITLE
kotlin.Result Comprehensions

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow#2389]
With Kotlin 1.5 `kotlin.Result` is becoming stable so it would be a good idea to add some of the same functionality that we have with other Bifunctors like `nullable` or `Either`.

This is a follow up from [this Thread](https://kotlinlang.slack.com/archives/C8UK6RTHU/p1618393956013200) in Slack.

**Comment by raulraja** [comment]
@pablisco Do we have plans to land these on 1.0? Otherwise, this is going to have to wait until after September.

**Comment by pablisco** [comment]
Let's focus on bringing a stable 1.0 and we can work on new comprehension DSLs for the next milestone 🙂 
Do we have a 1.1 label? :D
