### ISSUE TITLE
[Investigation] Allow to use JDK 9 and later

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow#2391]
I'm not entirely sure of what is required but limiting the JDK to 9 may come with problems in the near future. Jetpack Compose and AGP 7.0.0 require JDK 11, so it's not possible to have a project using Compose at the same time as this project on the same IDE.

**Comment by rachelcarmena** [comment]
I think it would be necessary to differentiate:

-    The requirements to **build** Arrow to be able to contribute with its development
-    The requirements to **use** Arrow

There was an interesting chat about it in [KotlinLang Slack](https://kotlinlang.slack.com/archives/C5UPMM0A0/p1619021205356700) about it.

**Comment by pablisco** [comment]
From the looks of it this seems to be that we require to add `toolJar` as a dependency for compiling the tests source code.  On SDK 11 running ./gradlew build runs OK, so I think that it should be enough to not include the toolJar if it's not there. I'll open a PR to test this 🤞
