### ISSUE TITLE
Duplicated API for nonFatalOrThrow() without CancellationException

### ISSUE THREAD

**Issue by aballano** [arrow-kt/arrow#2393]
[The API for nonFatalOrThrow is duplicated in arrow-fx-coroutines](https://github.com/arrow-kt/arrow/blob/main/arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Platform.kt#L158) (from arrow-core) but it doesn't include exceptions like CancellationException, which is needed for coroutines to properly work with cancellation. Meaning that people using the implementation from arrow-fx-coroutines might have bugs.

![image](https://user-images.githubusercontent.com/3294640/117431772-e5de4080-af29-11eb-82dc-9d81b93c8818.png)

Suggestion: If possible remove such API from arrow-fx-coroutines since it depends on arrow-core already

**Comment by nomisRev** [comment]
This duplicated functionality has been removed.
