### ISSUE TITLE
Investigate compiler inline crash

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow#2394]
I came across this compiler failure while working on #2390 with version v1.0.0-SNAPSHOT (Kotlin 1.4.32)

![image](https://user-images.githubusercontent.com/260697/117419670-bffa7100-af14-11eb-82a1-05946adda1e1.png)

It was solved by making `IterablEffect` not abstract so it could be a problem with the anonymous class.

![image](https://user-images.githubusercontent.com/260697/117420183-36976e80-af15-11eb-981c-dd51c8215e3b.png)

Need to see if this is reproducible with Kotlin 1.5 and IR on. This is not necessarily a problem with Arrow but worth investigating and reporting to JB if we find this to be an issue.

Discussion from Slack can be found [here](https://kotlinlang.slack.com/archives/C8UK6RTHU/p1620335126068100)

**Comment by raulraja** [comment]
@pablisco closing this as it refers to an old version and we have not heard any other similar reports. If you think it's still valid please reopen. Thanks! :)
