### ISSUE TITLE
Include iterable comprehensions on the website

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow#2399]
Make sure we have visibility of [this feature](https://github.com/arrow-kt/arrow/pull/2396) on the website.

There is two options here:

- We could have a dedicated section for comprehensions where we include `Iterable` comprehensions and other ones like `Flow`, `Sequence`, and even existing ones like `nullable`, or `either`.
- Have a dedicated section for Iterables where we include the comprehensions. I don't see many things going here, but may be easier to find

There is also the option to have both entry paths :)

**Comment by serras** [comment]
Closed because the feature is not present in Arrow
