### ISSUE TITLE
Create laws for Iterable Comprehensions

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow#2400]
Currently, [these](https://github.com/arrow-kt/arrow/pull/2396/files#diff-358fc8e67988b210795cfc3652585542f79fbed9374c401050393b20a3f46a5bR6) are defined without property testing. 

We should define some Laws for this functionality. Similar to how they are defined [here](https://github.com/arrow-kt/arrow/blob/1d2771f057d398115823e882e066b8c654a68711/arrow-libs/core/arrow-core/src/test/kotlin/arrow/core/EitherTest.kt) for Either.

**Comment by nomisRev** [comment]
The referenced ticket was closed, so I am also going to close this dependent ticket.
