### ISSUE TITLE
["Request"] Option.forEach

### ISSUE THREAD

**Issue by gabrieljones** [arrow-kt/arrow#2410]
What version are you currently using?
0.13.2

What would you like to see?
Option.forEach

Unless Arrow is strictly attempting to avoid use in non pure code.  But then one might be attempted to abuse map and put side effects in a map call.

Or maybe there is already an Option.forEach under some other name?

**Comment by gabrieljones** [comment]
See
https://www.scala-lang.org/api/2.13.6/scala/Option.html#foreach[U](f:A=%3EU):Unit
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/for-each.html

**Comment by pakoito** [comment]
`map` is inline so it supports suspension, which means that yes, mapping or tapping (#2416) to side-effect is legitimate.

**Comment by nomisRev** [comment]
This has been closed with https://github.com/arrow-kt/arrow/pull/2459
