### ISSUE TITLE
["Request"] Variance for generic types in compositions

### ISSUE THREAD

**Issue by magneticflux-** [arrow-kt/arrow#2414]
What version are you currently using?

Arrow Optics `0.13.2`

What would you like to see?

Variant generic types in `compose` functions. Due to limitations of the Kotlin language, these type variants can't be applied to the type as a whole. This is a compromise that should cover the main use-case.

Test case:

```kotlin
interface MyInterface {
    val myValue: String
}

// 2 or more subclasses
class Implentation1(override val myValue: String) : MyInterface
class Implentation2(override val myValue: String) : MyInterface

val getter = Getter<MyInterface, String> { it.myValue }

val myOtherLens: Lens<String, Implentation1> = TODO("external to the problem")

val composition = myOtherLens + getter // Error!
```

**Comment by raulraja** [comment]
Related slack conversation https://kotlinlang.slack.com/archives/C5UPMM0A0/p1622881518063600
