### ISSUE TITLE
["Request"] tap / effectful extensions for Either / Validated

### ISSUE THREAD

**Issue by codymikol** [arrow-kt/arrow#2416]
What version are you currently using?

0.13.2

What would you like to see? 

Currently I have written a few extensions written for handling effectful things like logging.

`tap` `tapLeft` `tapFold`

Essentially these are called in the same way that `map` `mapLeft` and `fold` are called, but their return values are unused. These are primarily useful for things like logging.

for example

```kotlin
doEitherFn()
  .tap { RedisService.commit("foo", it.message) }
  .tapLeft { logger.error("Failed to get foo: ${it.error}") }
  .map { transformFoo(it) }
  .tapFold({ logger.error("Failed Transformation! ${it.error}") }, { logger.info("Did Transformation! ${it.message}) })
```

Admittedly `tapFold` might not be the greatest nomenclature, but I think it gets the idea across 😉. I have these written out internally, and if the arrow team is interested I'd be willing to make a PR.

**Comment by pakoito** [comment]
This was on the repo at some point, I don't know if it accidentally went away when typeclasses got removed.

**Comment by nomisRev** [comment]
They were removed, but they're welcome to come back since they seem to be very commonly used.
And they make sense in combination with `suspend` for convenient logging etc like shown above.

A PR would be great @codymikol!!

**Comment by nomisRev** [comment]
This has been closed https://github.com/arrow-kt/arrow/pull/2459.
