### ISSUE TITLE
["Request"] Optic composition with standard Kotlin `KProperty`s

### ISSUE THREAD

**Issue by magneticflux-** [arrow-kt/arrow#2418]
What version are you currently using?
0.13.2

What would you like to see?

Having extension functions similar to the existing ones like `Getter<A,B> + Getter<B,C> -> Getter<A,C>` would be super handy.

I found out that this code works (because `Getter` is a functional interface?):
```kotlin
fun example(getter: arrow.optics.Getter<T, V>) { }

fun main() {
    val prop: KProperty1<T, V> = TODO("External")
    example(prop)
}
```

So naturally now I want to be able to use typical optic compositions on the results.

This won't be able to replace the `@optics` annotation since it can't derive the equivalent `Setter`-type lenses, but it would make it easier to create optics on non-constructor parameters of data classes.

I am currently using this snippet:
```kotlin
operator fun <T, V, U> KProperty1<T, V>.plus(other: Getter<V, U>): Getter<T, U> {
    return Getter {
        other.get(this(it))
    }
}
```

**Comment by nomisRev** [comment]
Hey @magneticflux-,

That's a great idea, and a great addition to Optics! If you're up for adding your snippet in a small PR that'd be awesome.

> (because Getter is a functional interface?):

Since `Getter<S, A>` is a functional interface it matches anything of the shape `(source: S) -> A`. 
`fun interface` works like `@FunctionalInterface` in Java where you can pass anything of the same shape of the single abstract method.

**Comment by serras** [comment]
@magneticflux- since some time we have an `arrow-optics-reflect` which allows turning any `KProperty` into a lens. If you have time to have a look and give feedback, that would be awesome!

**Comment by magneticflux-** [comment]
Looks good, thank you!

Something like Scala's implicit conversions would be awesome, but unfortunately I don't think that's on the roadmap for Kotlin since it's a bit niche.
