### ISSUE TITLE
Error in "arrow" for new project

### ISSUE THREAD

**Issue by Jacky-YC** [arrow-kt/arrow#2439]
![image](https://user-images.githubusercontent.com/42370375/124423289-663ce880-dd97-11eb-8f75-d2386fef5a6a.png)
![image](https://user-images.githubusercontent.com/42370375/124423301-6b9a3300-dd97-11eb-9269-6998269e356b.png)
![image](https://user-images.githubusercontent.com/42370375/124423318-7654c800-dd97-11eb-9be0-d86b903f5c6e.png)

**Comment by Jacky-YC** [comment]
![image](https://user-images.githubusercontent.com/42370375/124423467-ce8bca00-dd97-11eb-9457-bb89759603a7.png)
Whenever you use @optics, you get an error

**Comment by nomisRev** [comment]
Hey @Jacky-YC,

I think this issue is caused by 1.5.20.
Arrow Meta (the KAPT based one) is using an old dependency that is build against 1.5.10 currently. This might be causing an issue at runtime if there is a breaking change in the Kotlin Std library (metadata).

Could you try with Kotlin 1.5.10?

**Comment by Jacky-YC** [comment]
I tried to lower the Kotlin version, but the same problem occurred.
kotlin version [1.5.0/1.5.10/1.5.20]
arrow version 0.13.2

**Comment by rachelcarmena** [comment]
Hi! 

`JvmBytecodeBinaryVersion` changed from Kotlin 1.4.x to 1.5.x.

Arrow `0.13.2` was [compiled with Kotlin 1.4.32](https://github.com/arrow-kt/arrow/blob/0.13.2/arrow-libs/gradle.properties#L31) so `io.arrow-kt:arrow-meta` depends on `io.arrow-kt:kotlin-metadata:1.4.32`.

A possible way to fix that error:

- Exclude `io.arrow-kt:kotlin-metadata` as transitive dependency of `arrow-meta` (see [Gradle documentation](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ModuleDependency.html#exclude-java.util.Map-)).
- Add `io.arrow-kt:kotlin-metadata:1.5.10` dependency.

**Comment by Jacky-YC** [comment]
![image](https://user-image.githubusercontent.com/42370375/126027777-f079e39a-1f75-4d3f-aa15-bd098d47664f.png)

Problem solved, thank you!
@rachelcarmena @nomisRev

**Comment by Jacky-YC** [comment]
fixed

**Comment by rachelcarmena** [comment]
Awesome, thanks to you for letting us know :raised_hands:
