### ISSUE TITLE
Upgrade Gradle to 7.0

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow#2442]
For us to support JDK 16 for the compilation of the project, we need to upgrade to Gradle 7 first, as I found out while adding multiple runs for different JDKs in #2392

**Comment by pablisco** [comment]
This is where I got the hint about JDK 16 support: https://www.infoq.com/news/2021/04/gradle-releases-version-7/

**Comment by felixdivo** [comment]
The  README still reads:

>  JDK 16 doesn't currently work but will do once we upgrade to Gradle 7.0

Was it just not updated? It links here.

**Comment by nomisRev** [comment]
You're correct. That is out of date in the README.
