### ISSUE TITLE
Unreasonable behavior of option monad in cases when Option.none is bound?

### ISSUE THREAD

**Issue by skapral** [arrow-kt/arrow#2448]
Version: 0.13.2

While studying arrow-kt capabilities and trying out various examples from the tutorial, I noticed that option monad behavior is strange in cases when `Option.none` is bound. Consider this example (slightly changed version of [this](https://arrow-kt.io/docs/apidocs/arrow-core/arrow.core/-option/#computing-over-dependent-values-ignoring-absence) one):

```
import arrow.core.computations.option
import arrow.core.Some
import arrow.core.none
import arrow.core.Option

suspend fun value(): Option<Int> =
        option {
            val x = none<Int>().bind()
            val y = Some(1).bind()
            val z = Some(1 + y).bind()
            y + z
        }
suspend fun main() {
    println(value())
}
```

Expecting to get `Some(3)` in output, I got `None`, despite the fact that x doesn't participate in result calculation.

The issue is reproduced anytime `None` is bound. Binding unused `Some` instead of `None` take no impact on sum result.

**Comment by skapral** [comment]
Ok, I was wrong. Haskell's maybe behaves in the same way. Seems like I missed something about monads :)

```
calc = do 
   x <- Nothing
   y <- Just 1
   z <- Just (y + 1)
   return (y + z)

main = case calc of
  Just value -> print value
  Nothing    -> print "Nothing"
```

**Comment by nomisRev** [comment]
The reason it behaves that way is because monad is defined in flatMap.

Where flatMap is also called "bind" in comprehensions or computation blocks as we call them in Arrow.

For Option that means short-circuiting behaviour over bind.

This code is the equivalent of


None.flatMap { x ->
  Some(1).flatMap { y ->
    Some(2).map { z -> x + y}
  } 
}

So, None takes part in the computation whether the value is used or not.

**Comment by skapral** [comment]
@nomisRev yeah, my bad, some moments later after reporting the issue I recalled that :)

Thanks.
