### ISSUE TITLE
["Request"] Either to support nullable as well

### ISSUE THREAD

**Issue by rishabhdeepsingh** [arrow-kt/arrow#2474]
What version are you currently using?
V-0.13.2

What would you like to see?
I want either to support null as well. something like. 
I would like to contribute for this if it gets accepted
```kotlin
fun doSomething( drawable: Either<Int, String>? = null ) {
    drawable.ifNull{
        // drawable is Null
    }.ifLeft{
        // Int is passed
    }.ifRight {
        // String is passed     
    }
}
```

**Comment by nomisRev** [comment]
Hey @rishabhdeepsingh,

This is already possible by combining Kotlin's nullable syntax with `Either`.

```kotlin
fun doSomething( drawable: Either<Int, String>? = null ) {
    drawable?.let {
        // drawable is Null
    }.ifLeft{
        // Int is passed
    }.ifRight {
        // String is passed     
    }
}
```

but maybe even more idiomatic:

```kotlin
fun doSomething( drawable: Either<Int, String>? = null ) = when(drawable) {
  is null -> // drawable is Null
  is Either.Left -> // Int is passed
  is Either.Right -> // String is passed     
}
```

or

```kotlin
fun doSomething( drawable: Either<Int, String>? = null ) =
  drawable.fold(
    ifLeft = { // Int is passed },
    ifRight = { // String is passed }
  ) ?: // drawable is Null
```

Would these alternatives suffice, or did you have a specific use-case where you encountered this pattern often?

**Comment by rishabhdeepsingh** [comment]
the 1st and 3rd don't work

**Comment by nomisRev** [comment]
Seems I forgot to use proper `?.` syntax in some cases. Do these work?

```kotlin
fun doSomething( drawable: Either<Int, String>? = null ) {
    drawable?.ifLeft{
        // Int is passed
    }?.ifRight {
        // String is passed     
    } ?: // null
}
```

or

```kotlin
fun doSomething( drawable: Either<Int, String>? = null ) =
  drawable?.fold(
    ifLeft = { // Int is passed },
    ifRight = { // String is passed }
  ) ?: // drawable is Null
```

**Comment by rishabhdeepsingh** [comment]
@nomisRev I am sorry but both of these also don't work 😞 . This is because we need operators for Nullability as well. in case of `Either`

**Comment by nomisRev** [comment]
Hey @rishabhdeepsingh,

I am not sure what you mean with:

> This is because we need operators for Nullability as well


As far as I understand all the shared examples cover your original request 🤔 The new `either` DSL also supports `ensureNotNull`, and handlers can be installed through `onLeft` and `onRight`.

Contracts are also used in `isLeft()` and `isRight()`, so smart-castings should also apply there.
