### ISSUE TITLE
[bug] option.zip (5) has incorrect type

### ISSUE THREAD

**Issue by myuwono** [arrow-kt/arrow#2476]
the type parameter `I` isn't needed. we can't use this zip in our codebase due to this. 
```kotlin
public inline fun <B, C, D, E, F, G, H, I> zip(
    b: Option<B>,
    c: Option<C>,
    d: Option<D>,
    e: Option<E>,
    f: Option<F>,
    g: Option<G>,
    map: (A, B, C, D, E, F, G) -> H
): Option<H> = ...
```

**Comment by nomisRev** [comment]
Thanks for the ticket and fix @myuwono.

This fix will be released very soon, but you should be able to walk around it by providing a redundant generic param.
Although that always forces you to explicitely provide all type arguments.

**Comment by myuwono** [comment]
yeah, we're not blocked. We do have a copy of the implementation in-house currently which we assign to the Option companion object like below. It's used throughout the codebase currently. Something like this

```kotlin
fun <A, B, Z> Option.Companion.bind(optionA: Option<A>, optionB: Option<B>, fn: (Pair<A, B>) -> Z): Option<Z> = ...
// etc
```

Historically it was introduced to hide `.fix()` from the previous higher kind emulation in arrow 0.11.x. Theoretically right now with zip we don't need it anymore. Currently I'm piggybacking that relic to hide the fix typing.

**Comment by myuwono** [comment]
that syntax is borrowed from kotest's `Arb.bind` syntax.
