### ISSUE TITLE
Arrow Mpp Targets

### ISSUE THREAD

**Issue by i-walker** [arrow-kt/arrow#2487]
The following supported platforms are missing in Arrow and the general Kotlin ecosystem. Having [Coroutines support](https://github.com/Kotlin/kotlinx.coroutines/blob/master/gradle/compile-native-multiplatform.gradle).
References can be found [here](https://github.com/Kotlin/kotlinx.coroutines/issues/855), and the blocking issue running tests over linux targets in [Team City](https://youtrack.jetbrains.com/issue/KT-43996) for kotlinx.coroutines.

- [ ] linuxArm32Hfp
- [ ] linuxMips32
- [ ] linuxMipsel32
- [ ] mingwX86
- [ ] wasm32

similar for Android Native targets, [here](https://github.com/Kotlin/kotlinx.coroutines/issues/812):

- [ ] androidNativeArm32
- [ ] androidNativeArm64

experimental targets:
- [x] watchosArm64 #2491

Any Feedback is welcome, if there are new developments on this.

**Comment by nomisRev** [comment]
@i-walker if KotlinX is blocking these new targets it's only blocking Arrow Fx.
We could support all these targets already for Arrow Core & Arrow Optics.

Arrow is no longer depending on Atomic Fu, so that is also unblocked.

**Comment by serras** [comment]
We now support every target supported by KMP, so I'm closing this one.
