### ISSUE TITLE
Eval does not guarantee stack-safe

### ISSUE THREAD

**Issue by tonilopezmr** [arrow-kt/arrow#252]
Evidence of problems with Eval#flatMap in #240 

In kategory
https://github.com/kategory/kategory/blob/master/kategory/src/main/kotlin/kategory/data/Eval.kt#L40

In cats
https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/Eval.scala#L81

**Comment by pakoito** [comment]
Fixed by https://github.com/arrow-kt/arrow/pull/618
