### ISSUE TITLE
["Request"] Automatically commit `api files` on PR branches.

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow#2521]
What would you like to see?

We can leverage Github Actions to automatically run `./gradlew apiDump` and commit any changes. This would allow contributors to effectively ignore the whole Binary Compat Validator configuration and completely automate it in CI.

The goal of the Binary Compat Validator is not perse to break CI on breaking changes but to make changes in the binary reviewable.

**Comment by nomisRev** [comment]
https://github.com/stefanzweifel/git-auto-commit-action

**Comment by pakoito** [comment]
Maybe a git hook instead? It may happen early.

**Comment by nomisRev** [comment]
What may happen early? We control the command that creates output we'd want to include into git.
I have an example [here](https://github.com/nomisRev/Saga/blob/main/.github/workflows/pr.yml#L21) where I do this for keeping Dokka Github Pages automatically up-to-date.

**Comment by pablisco** [comment]
I think that operations that do code formatting are great to run on git-hooks. However, tasks like API dump and others that don't touch code we can probably push commits upstream without causing significant conflicts. The IDE or CLI should prompt the contributor to rebase or merge changes, which should go fairly smooth :crossed\_fingers: 

Some of these tasks are quite long, so we probably don't want to be waiting for 2-3 minutes with every commit :sweat\_smile:

**Comment by serras** [comment]
Fixed by #2605
