### ISSUE TITLE
Investigate Gradle Kts accessors for Gradle plugins

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow#2530]
As mentioned [here](https://github.com/arrow-kt/arrow/pull/2529#discussion_r714553396) we may be able to define our plugins in the traditional way and rely on Kts accessor generation to make them work :crossed\_fingers:

**Comment by i-walker** [comment]
As we're using `arrow.gradle.config` plugin https://github.com/arrow-kt/arrow-gradle-config this is already satisfied
