### ISSUE TITLE
Add centralise version catalogue

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow#2532]
There are new features that can help us manage versions across modules (and potentially across repos): [https://docs.gradle.org/current/userguide/platforms.html](https://docs.gradle.org/current/userguide/platforms.html)

One thing to keep in mind is how this interacts with auto-update GH Actions. As mentioned by @[JavierSegoviaCordoba](https://github.com/JavierSegoviaCordoba) we may be able to use [Renovate](https://docs.renovatebot.com/java/) or [RefreshVersions](https://jmfayard.github.io/refreshVersions/). The second one may not have the automation that we are after though.

**Comment by nomisRev** [comment]
done
