### ISSUE TITLE
Add Traverse and Sequence operations for kotlin.Sequences

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow#2535]
We have traverse and Sequence operations for Iterable instances. We could probably add these for `kotlin.Sequence` instances too. This is specially nice for \`traverseResult\` and `sequenceResult`as we could short circuit the sequence when we get a failure :slightly\_smiling\_face: 

Additionally, we may want to check these for Flows too

**Comment by pakoito** [comment]
Additionally indeed hahaha

**Comment by pablisco** [comment]
@pakoito Too many things at the same time :sweat\_smile:

**Comment by abendt** [comment]
i have created a PR that adds _sequenceResult_ and _traverseResult_

**Comment by i-walker** [comment]
Can we close this @pablisco as the reason, why this promotes Anti-patterns is described here https://github.com/arrow-kt/arrow/pull/2602#issuecomment-1000769802

**Comment by i-walker** [comment]
Closing this as Pablisco agreed on slack
