### ISSUE TITLE
Arrow site calling localhost

### ISSUE THREAD

**Issue by IRus** [arrow-kt/arrow#2541]
<img width="1321" alt="выява" src="https://user-images.githubusercontent.com/493656/135302949-0cdc9550-5005-4e35-9d00-f2f07b2edddc.png">

**Comment by pakoito** [comment]
Poor thing, it's homesick.

**Comment by raulraja** [comment]
Addressed in #2545 which will eventually see the light. Thanks, @IRus for reporting it and @israelperezglez for the fix! 🥂
