### ISSUE TITLE
Add Benchmarks

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow#2542]
In order to evaluate if a change increases or reduces performance and/or memory we should add some form of benchmarks suite.

As an strech goal, it would be great to be able to run this in PRs and fail if we see degradation over a given threshold.

**Comment by nomisRev** [comment]
Hey @pablisco,
I am closing this ticket as part of housekeeping. I don't think we currently have the bandwidth to look into, nor do I think there currently a strong need or desire to do benchmarking.

Feel free to re-open this ticket, or re-ignite the discussion 😘
