### ISSUE TITLE
["Request"] ResultEffect leaks to the global namespace

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#2547]
What version are you currently using?
1.0.1

What would you like to see?
`arrow.core.computations.ResultEffect.bind` is available globally, so you can do disallowed things such as

```
Either.catch {
    either.bind()
}
```

**Comment by nomisRev** [comment]
Ye, it's indeed publically available as through the `object`. Which exposes the behavior in an unsafe way.
We should fix this without making a binary breaking change 😅

Think we could either make it `internal` after deprecation of the `public` object, this would result in least changes and would keep the JVM binary the same.

Or we should deprecate it completely making it private, but without any breakage in the Kotlin API whilst keeping the old JVM API around as `DeprecationLevel.HIDDEN`.

**Comment by nomisRev** [comment]
It's only been released in `1.0.0` should it shouldn't have much usage out there.

**Comment by pakoito** [comment]
Ye go for it IMO

**Comment by nomisRev** [comment]
@i-walker the `result { }` builder is still missing from the new `arrow.core.continuations` package. Correct?
We should add it there, and deprecate whatever we have in the current `result { }` builder.
Then we can take this issue into account, and get rid of it.

I've heard more reports of it being problematic. You can also do a global import for `Either<Throwable, A>.bind()` through this code that throws 😱

**Comment by i-walker** [comment]
I am on it @nomisRev, it will be available here https://github.com/arrow-kt/arrow/pull/2669

**Comment by i-walker** [comment]
Can we close this PR @pakoito since it has been deprecated with a Warning in https://github.com/arrow-kt/arrow/pull/2669?

**Comment by pakoito** [comment]
Yay! Go for it!
