### ISSUE TITLE
["Request"] Add module-info for jvm artifacts

### ISSUE THREAD

**Issue by AlbertoSH** [arrow-kt/arrow#2553]
What version are you currently using?
1.0.0

What would you like to see?
Otherwise arrow is not usable with jlink
As an example, find the following ticket in which the Kotlin team introduced it in the stdlib 
https://youtrack.jetbrains.com/issue/KT-21266

I'll try to find some time in the following days to see if I can implement this and contribute to the project :)

**Comment by serras** [comment]
Closed as duplivate of #2800
