### ISSUE TITLE
IO Monad deprecation - Ergonomics section

### ISSUE THREAD

**Issue by modernptz** [arrow-kt/arrow#2554]
https://arrow-kt.io/docs/effects/io/ 
Not sure that ergonomics section has been written correctly, but since IO monad is Semigroup it should be possible to write something like that: 

```    
val number = IO.just(1)
val triple: IO<Triple> = (number,number,number).mapN(Triple(it))
```
So there is no need of flatMap.

However it's not exact code, just translation from cats to imaginable arrow.

**Comment by serras** [comment]
@modernptz @pakoito are you OK with closing this issue? I think it's a long time since Arrow migrated from `IO` to `suspend` functions.
