### ISSUE TITLE
["Request"]  NonEmptySet

### ISSUE THREAD

**Issue by hoc081098** [arrow-kt/arrow#2565]
What version are you currently using?
1.0.0

What would you like to see?
NonEmptySet, ref:
- https://hackage.haskell.org/package/non-empty-0.3/docs/Data-NonEmpty-Set.html
- https://typelevel.org/cats/api/cats/data/index.html#NonEmptySet[A]=cats.data.NonEmptySetImpl.Type[A]

- https://github.com/quickbirdstudios/NonEmptyCollections

**Comment by ibado** [comment]
Hi there :wave: I'd like to take this one! Is that okan? @serras

**Comment by serras** [comment]
Sure, I'm really happy to see somebody taking over this. Since this doesn't conflict with anything in Arrow 1.x, please target `main` when doing the corresponding PR. Thanks for your help!

**Comment by nomisRev** [comment]
This has been fixed by @ibado in #2899
