### ISSUE TITLE
documentation is not being correctly rendered

### ISSUE THREAD

**Issue by robotlovesyou** [arrow-kt/arrow#2581]
Many of the examples on arrow-kt.io are either incorrectly rendered, or completely missing. 

For example on https://arrow-kt.io/docs/apidocs/arrow-fx-coroutines/arrow.fx.coroutines/-resource/index.html
or https://arrow-kt.io/docs/apidocs/arrow-core/arrow.core/-either/

I could not see any obvious issues with the formatting of the comments in the related kotlin source files, so I guess it may be a problem with the utility you are using to extract them out to the web documents?

**Comment by LVMVRQUXL** [comment]
I've noticed the same problem on [arrow.core.ior](https://arrow-kt.io/docs/apidocs/arrow-core/arrow.core/-ior/)!

**Comment by stewSquared** [comment]
Reporting this page as well: https://arrow-kt.io/docs/effects/io/
Code blocks don't render properly, though they are present in source: https://github.com/arrow-kt/arrow/tree/d1bd27e245d592f38b098b822ee0db73771d08fa/arrow-site/docs/docs/io

And it generally seems like a lot of pages are missing that were present in older versions, in spite of those classes still existing.

**Comment by nomisRev** [comment]
Thanks, @robotlovesyou, @LVMVRQUXL & @stewSquared for reporting!

Sadly these issues are coming upstream from bugs inside [Dokka](https://github.com/Kotlin/dokka).
As a temporary workaround, we're trying to patch them.

**Comment by barm** [comment]
Hi, we've been adopting (and enjoying!) arrow-core starting with `Either` at https://github.com/partyround/ and this issue definitely makes it tricky to help being understand the library. Has there been any success is patching Dokka? Is there an issue on their repo I could read about to better understand the issue?

**Comment by nomisRev** [comment]
This should be fixed by the new website, and the new API docs which leverage `dokkaHtml` instead of `dokkaGfm`.

Thanks for the feedback, and support. Please re-open the ticket if you still encounter any issues.
