### ISSUE TITLE
Documentation for Maven import specified 'arrow-core' but 'arrow-core-jvm' is required

### ISSUE THREAD

**Issue by twh270** [arrow-kt/arrow#2597]
The instructions for importing Arrow Core to a Maven project (https://arrow-kt.io/docs/core/#Maven) appear to be incorrect. They specify 'arrow-core' as the artifactId but 'arrow-core-jvm' is required.

Ref thread at https://intellij-support.jetbrains.com/hc/en-us/community/posts/4412380221586-Unable-to-import-Arrow-core-classes-after-adding-Maven-dependency

**Comment by srnm** [comment]
Also, the 1.0.1 arrow-stack bom does not define arrow-core-jvm

**Comment by nomisRev** [comment]
@jay-peper this should be working correctly for `1.0.0`.
`1.0.1` is identical to `1.0.0` and only includes "fixes" for Kotlin MPP publishing, but we broke Maven in the process. The next version will fix the Maven support again. Sorry for the inconvience.

**Comment by i-walker** [comment]
@jay-peper can you try it out with 1.0.3-alpha.12. There is also on here, which works https://github.com/arrow-kt/Arrow-Maven-Template/blob/main/pom.xml

**Comment by i-walker** [comment]
Closing this since the Maven template above provides the details thanks @twh270
