### ISSUE TITLE
Link to https://arrow-kt.io/docs/core/#Maven does not work

### ISSUE THREAD

**Issue by twh270** [arrow-kt/arrow#2598]
On https://arrow-kt.io/docs/core/, the link in the Quick Start section to "Maven Setup" does not work.

Browser/OS: Firefox 94.0.2 on Windows 10, also reproduced in Edge

**Comment by larsw** [comment]
+1

I've been struggling for ours trying to figure out how this works. Right now, I'm looking into if Kapt processing is also needed for core, since the core.jar file only contains `.kotlin_metadata` files and not `.class` files.

**Comment by pakoito** [comment]
The link may be broken, but the section is there 🙌 Just scroll down a bit


![Screenshot 2021-12-17 at 10-59-06 Λrrow](https://user-images.githubusercontent.com/514871/146526576-4915ebb4-9c33-4f4c-9739-e3c7dd64aed2.png)

**Comment by twh270** [comment]
@larsw see my other issue #2597 -- you'll need to import 'arrow-core-jvm' as the artifactId in your POM and not 'arrow-core'.

**Comment by i-walker** [comment]
fixed please check out the Maven template https://github.com/arrow-kt/Arrow-Maven-Template
