### ISSUE TITLE
Could not find io.arrow-kt:arrow-optics-ksp-plugin:1.0.1

### ISSUE THREAD

**Issue by m0skit0** [arrow-kt/arrow#2619]
After following the [instructions for adding Arrow Optics](https://arrow-kt.io/docs/optics/#Gradle-kotlin) to my project, I get the following error:

```
      > Could not find io.arrow-kt:arrow-optics-ksp-plugin:1.0.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/io/arrow-kt/arrow-optics-ksp-plugin/1.0.1/arrow-optics-ksp-plugin-1.0.1.pom
          - https://repo.maven.apache.org/maven2/io/arrow-kt/arrow-optics-ksp-plugin/1.0.1/arrow-optics-ksp-plugin-1.0.1.pom
          - https://jcenter.bintray.com/io/arrow-kt/arrow-optics-ksp-plugin/1.0.1/arrow-optics-ksp-plugin-1.0.1.pom
```

Also [searching Maven Center for the plugin artifact](https://search.maven.org/search?q=arrow-optics-ksp-plugin) did not yield any result.

**Comment by 0xKZ** [comment]
Same issue here. I managed to get things to compile by instead using this dependency:

```
ksp("io.arrow-kt:arrow-optics:1.0.1")
```

My guess is that the plugin was merged into the optics package and the documentation wasn't updated?

**Comment by nomisRev** [comment]
Is that working @0xKZ? oO
Arrow Optics KSP has been merged but will be released in 1.0.2 or 1.1.0.

**Comment by nomisRev** [comment]
@0xKZ @m0skit0 you should be able to try this now for `1.0.2-alpha.22`.
Hopefully, the stable `1.0.2` release will follow later this month.

**Comment by i-walker** [comment]
There is a template repository with arrow optics tsp plugin set up and running https://github.com/arrow-kt/Arrow-JVM-Template/tree/optics-setup Thanks for raising this @m0skit0 !
