### ISSUE TITLE
["Request"] Convenience conversion from Resource<R> to Flow<R>

### ISSUE THREAD

**Issue by 404-** [arrow-kt/arrow#2632]
What version are you currently using? 1.0.1

What would you like to see? `Resource` to `Flow` converter, just like [fs2.Stream[F[_], O].resource(r: Resource[F, O])](https://oss.sonatype.org/service/local/repositories/releases/archive/co/fs2/fs2-core_2.13/3.2.0/fs2-core_2.13-3.2.0-javadoc.jar/!/fs2/Stream$.html#resource[F[_],O](r:cats.effect.kernel.Resource[F,O])(implicitF:cats.effect.kernel.MonadCancel[F,_]):fs2.Stream[F,O])

Example:
```
// Presumably, something along the lines of:
fun <R> Resource<R>.asFlow(): Flow<R> = flow {
  use { acquired ->
    emit(acquired)
  }
}
```

```
// So, given
val data: Resource<InputStream> = TODO()
//    and
fun InputStream.chunked(size: Int): Flow<ByteArray> = TODO()


// This can be done:
val chunks: Flow<ByteAray> = data.asFlow().flatMapConcat { it.chunked(64) }
```

**Comment by nomisRev** [comment]
Hey @404-,

Thanks for creating the ticket. That's an operator I'm using myself from time-to-time in some projects.
