### ISSUE TITLE
Issue with 1.0.1 versjon with maven

### ISSUE THREAD

**Issue by etse** [arrow-kt/arrow#2658]
Hi. when I try to use the `1.0.1` version with maven I get `unresolved reference Either` wherever I try to use that class. With the `1.0.0` version everything works fine. 

In short I have a small spring-boot app with kotlin and I add arrow as dependency as follow:
```
<dependency>
    <groupId>io.arrow-kt</groupId>
    <artifactId>arrow-core</artifactId>
    <version>1.0.1</version>
</dependency>
```

If I downgrade to version `1.0.0` everything works fine. 

When using `1.0.0` i noticed that maven added `arrow-core-jvm:1.0.0` as a transitive dependency. I tried adding `arrow-core-jvm:1.0.1` as an explisit dependency and now everything works fine.

So this seems to work:
```
<dependency>
    <groupId>io.arrow-kt</groupId>
    <artifactId>arrow-core</artifactId>
    <version>1.0.1</version>
</dependency>
<dependency>
    <groupId>io.arrow-kt</groupId>
    <artifactId>arrow-core-jvm</artifactId>
    <version>1.0.1</version>
</dependency>
```

So this leads me to think there might be something wrong with the maven-package, that makes maven not include this dependency (which seems to be required).

**Comment by raulraja** [comment]
hi @etse,  there was an issue in the 1.0.1 release but the maven support is restored in `main` and will be available in the next release. It was addressed in #2652 and https://github.com/arrow-kt/arrow-gradle-config/pull/36

**Comment by etse** [comment]
Thanks for the quick reply. Good to hear it is already fixed. I'll just use this workaround until the next release :)

**Comment by hallyhaa** [comment]
Could it be that we have this problem again in v2.0.0?

**Comment by klobuczek** [comment]
> Could it be that we have this problem again in v2.0.0?

Yes, I have similar problem as well.
