### ISSUE TITLE
 Iso generation is supported for data classes with up to 22 constructor parameters

### ISSUE THREAD

**Issue by uma-bodduluri-idexx** [arrow-kt/arrow#2704]
What version are you currently using?
1.0.1

What would you like to see?
 work around

**Comment by nomisRev** [comment]
Hey @uma-bodduluri-idexx,

I also answered your question on StackOverflow.

> In Arrow-kt we only support automatic generation for Iso up to 22 parameters. The reason for this is that Arrow only has > Tuple3 -> Tuple22 defined. Pair and Triple from Kotlin Std are also used.
> 
> The example you shared data class test( 1,2,...23) has 23 parameters, so Arrow cannot generate the desired Iso.
> 
> You can still automatically genrate Lens and Optional for your data class by specifying > @optics(arrow.optics.OpticsTarget.Lens, arrow.optics.OpticsTarget.Optional).


It's not possible to fix this, but you can still generate Optics for your data class with the above instruction.
I hope that helps, if you have any other question or issues then please re-open the issue, or feel free to ask more questions here :)

You can also always find help in the #arrow channel on KotlinLang Slack.
