### ISSUE TITLE
["BUG"] Incorrect licenses in latest version's POM

### ISSUE THREAD

**Issue by aballano** [arrow-kt/arrow#2710]
The license section in the artifact POM is wrong for versions > 1.0.1

In 1.0.1 -> https://search.maven.org/artifact/io.arrow-kt/arrow-core/1.0.1/pom

>   <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

version 1.1.0 and 1.1.2 -> https://search.maven.org/artifact/io.arrow-kt/arrow-core/1.1.2/pom

> <licenses>
    <license>
      <name>https://www.apache.org/licenses/LICENSE-2.0.txt</name>
    </license>
  </licenses>

This causes issues with the [cashapp lib for validating licenses](https://github.com/cashapp/licensee)

I'm not sure what changed exactly, I was taking a look at the [license declarations](https://cs.github.com/?scope=org%3Aarrow-kt&scopeName=arrow-kt&q=LICENSE-2.0.txt) but couldn't find anything.

**Comment by raulraja** [comment]
thanks @aballano , this may be related to the new release process.  /cc @JavierSegoviaCordoba @i-walker

**Comment by JavierSegoviaCordoba** [comment]
Found:

```kotlin
licenses {
   license {
      name.set(pomLicenseName)
      name.set(pomLicenseUrl)
   }
}
```

I will fix it tomorrow :)

**Comment by i-walker** [comment]
Hi @aballano,
by tomorrow there should be an alpha `1.1.3-alpha.1`. Can you give us a feedback verifying your project with this

**Comment by aballano** [comment]
Seems to be fixed 👍 

https://search.maven.org/artifact/io.arrow-kt/arrow-core/1.1.3-alpha.1/pom

```
<license>
      <name>The Apache Software License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
</license>
```
