### ISSUE TITLE
New detekt rules and features

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#272]
Rules:

- Line jump after expression body
- Enforce expression body for simple methods
- Flag compiler warnings, i.e. unused lambda parameters
- Enforce explicit return type, including Unit

Kategory rules:

- Provide implicit object for instances
- Companion object must have constructor for all instances

Other features:

- Whitelist generated code

**Comment by mikezx6r** [comment]
A number of these are in newer versions of Detekt. I'm going to investigate upgrading the version of Detekt used by the project as a step towards completing this issue. Will post findings after upgrading Detekt locally

**Comment by nomisRev** [comment]
Closed due to using KtLint.
