### ISSUE TITLE
["Request"] ease conversion from Kotlin Iterable to NonEmptyList

### ISSUE THREAD

**Issue by christophejan** [arrow-kt/arrow#2727]
### What version are you currently using?

1.1.2

### What would you like to see?

```fun <T> Iterable<T>.toNonEmptyList(): Option<NonEmptyList<T>>```
or
```fun <T> fromIterable(i: Iterable<T>): Option<NonEmptyList<T>>```

### Why?

I think that currently, we have to convert ```Iterable``` first to ```List``` then to ```NonEmptyList``` : ```NonEmptyList.fromList(iterable.toList())```

**Comment by nomisRev** [comment]
Hey @christophejan,

Thank you for the ticket. The current way of transforming is indeed a bit Kotlin unidiomatic.
I would like to take the opportunity to also remove `Option` from the signature, in this case, there is no technical reason to use `Option` so we can safely use `?` instead.

With that in mind WDYT about `fun <T> Iterable<T>.toNelOrNull()` and `fun <T> Iterable<T>.toNonEmptyListOrNull()`?

**Comment by christophejan** [comment]
Hi @nomisRev 

Thank you very much. That would be perfect for me.

I'm a rather new Arrow user. I've suggested methods using the same pattern than ```fromList``` but I've no idea why ```Option```  rather than ```?``` was used on it.

**Comment by nomisRev** [comment]
> I've no idea why Option rather than ? was used on it.

There are purely historic, so you could say it's a bit of legacy API that has not yet been revamped :)
