### ISSUE TITLE
["Request"] Optics generation fails on multiplatform project

### ISSUE THREAD

**Issue by brezinajn** [arrow-kt/arrow#2737]
Project fails to build with the optics plugin enabled. 

Minimal repro project here: https://github.com/brezinajn/repro

What version are you currently using? 1.1.2

What would you like to see?
Project building correctly.

**Comment by i-walker** [comment]
adding ksp plugins needs other configurations, than those in the repo above, just as it is stated in the official Docs https://kotlinlang.org/docs/ksp-multiplatform.html

**Comment by serras** [comment]
@brezinajn were you able to make this work by following the KSP docs?

**Comment by brezinajn** [comment]
No, but this one fixed it #2840. Closing.
