### ISSUE TITLE
Syntax for kategory-effects-rx2

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#274]
https://github.com/kategory/kategory/pull/233#issuecomment-324806528

**Comment by krishnarb3** [comment]
Is this issue done?

**Comment by pakoito** [comment]
Hi Krishna! It isn't done yet, no. Feel free to take it, although I have to warn you, it is a challenging task for your first contribution!

**Comment by nomisRev** [comment]
RxJava now has Fx syntax enabled in its bindings.
