### ISSUE TITLE
Add recursion's Mu

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#275]
It didn't quite work *sigh*

https://github.com/kategory/kategory/commit/0fcf6a50757dd6f2c0c484e9e41126c708e83990

**Comment by JorgeCastilloPrz** [comment]
Which was the problem with that implementation?

**Comment by pakoito** [comment]
The types never quite aligned correctly. Recursion schemes are a special kind case that's trickier than usual. In Scala they look like oneliners, yet they're meatier and harder to understand than most impls I've done before.

**Comment by pakoito** [comment]
Done by @aedans
