### ISSUE TITLE
["Request"] add parZipEither

### ISSUE THREAD

**Issue by hoc081098** [arrow-kt/arrow#2758]
What version are you currently using?
1.1.2

What would you like to see?
I used my `parZipEither` many times in my projects.
It will be great if we have `parZipEither` for `Either`s.

```kotlin
suspend inline fun <A, B, C, L, R> parZipEither(
  ctx: CoroutineContext = EmptyCoroutineContext,
  crossinline fa: suspend () -> Either<L, A>,
  crossinline fb: suspend () -> Either<L, B>,
  crossinline fc: suspend () -> Either<L, C>,
  crossinline combiner: (A, B, C) -> R,
): Either<L, R> = either {
  coroutineScope {
    val a = async(ctx) { fa().bind() }
    val b = async(ctx) { fb().bind() }
    val c = async(ctx) { fc().bind() }
    combiner(a.await(), b.await(), c.await())
  }
}
```

**Comment by nomisRev** [comment]
Hey @hoc081098,
Do you feel that following snippet requires to much boilerplate?
The current direction Arrow is discourages this kind of overloads since they only offer small syntactic benefits at the cost of a larger API surface. Additionally this also suffers from the arity-n issue 😞

```kotlin
either<L, R {
  parZip({ fa.bind() }, { fb.bind() }, { fc.bind() }) { a, b, c -> combiner(a, b, c) } 
}
```

**Comment by nomisRev** [comment]
All operators in Arrow are currently being developed in such a way that everything safely composes, and you can combine the semantics of `E` with `Throwable`. The same pattern is for example also available for `Resource`.

```kotlin
resource<C> {
  parZip({ fa.bind() }, { fb.bind() }) { a, b -> combiner(a, b) }
}
```

**Comment by hoc081098** [comment]
It's nice. Thanks @nomisRev for you help
