### ISSUE TITLE
New syntax module

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#276]
As we're approaching release we need a better story about importing syntax. Syntax in this context are the collection of extension functions used to provide functionality based off typeclasses and datatypes. For example:

https://github.com/kategory/kategory/blob/master/kategory-core/src/main/kotlin/kategory/typeclasses/Functor.kt#L28

https://github.com/kategory/kategory/blob/master/kategory-core/src/main/kotlin/kategory/typeclasses/Applicative.kt#L20

https://github.com/kategory/kategory/blob/master/kategory-core/src/main/kotlin/kategory/data/Either.kt#L240-L242

At the moment all syntax exists in the package kategory, which makes intellisense method lookup very polluted. Ideally for release we'd like syntax to be optionally imported.

So, the plan:

1. Create a new module: kategory-syntax
2. The module has a single package: `kategory.syntax`
3. In this package is comprised of many packages, each one representing the syntax for one typeclass or datatype
4. These packages are all on the same physical location, there's no need to create a folder for each one of them

The expectation is that:
a -> importing `kategory.syntax.*` brings all syntax
b -> importing `kategory.syntax.either.*` brings the syntax just for Either

Known challenges:

Not all typeclasses and dataclasses have syntax defined. The project needs a complete pass to extract those that are relevant, and strive to avoid naming collisions.

**Comment by raulraja** [comment]
I think `syntax` should not require a new dependency, just an import:
```
import kategory.syntax.foldable.* //imports syntax for foldable.
import kategory.syntax.all.* //imports all syntax.
```
If users are required to include an extra dependency to just get syntactic sugar many will choose not to use it leading to more convoluted code.

**Comment by pakoito** [comment]
Right now due to how extension functions work syntax adds many methods that are not part of the required machinery. We could have a separate artifact and allow removing it as a transitive dependency with maven/gradle to trim the library's size down. So opt-out instead of opt-in.

**Comment by JorgeCastilloPrz** [comment]
I vote for @pakoito 's option also since that would be imported by default but you still have the change to exclude it on your compilation

**Comment by raulraja** [comment]
I still find syntax in a different jar as a bad idea for usage, anything not in core will get relegated to specific use cases and code snippets that people share won't compile in kategory for most users. This is trivial and common and part of syntax:
```
1.pure<OptionHK>()
```
That will not compile unless you add the dependency for syntax. A user sharing that and another pasting it won't compile unless they are aware that that lives in a different jar. No FP library neither cats or scalaz would consider separating syntax from the core as that would be equivalent as removing collections from the standard lib, a nightmare for first time users that just want to use the library.

**Comment by nomisRev** [comment]
@raulraja if it's an opt-out instead of an opt-in like @pakoito suggested than 
> code snippets that people share won't compile in Kategory for most users.

would only valid for people that explicitly opted out. Which I doubt is going to happen often.

I am unsure if we need to go as far as putting it in a separate module since I don't feel the syntax package would be that big. 50~75 methods? Are we expecting it to dramatically grow? Or is there another reason you'd want people to be able to opt out I am not thinking of?

**Comment by pakoito** [comment]
Okay, I don't want to get ahead of myself. Let's take the next release and do some metrics on it to see our current size and method count.

**Comment by pakoito** [comment]
@raulraja already did this :D
