### ISSUE TITLE
Not finding @extension

### ISSUE THREAD

**Issue by dolinja** [arrow-kt/arrow#2762]
Does this annotation still exist in latest versions of arrow?  I'm trying v1.1.2, don't see it in any of the 4 modules listed in the quickstart.  Does arrow still support implementing typeclasses with this?

**Comment by nomisRev** [comment]
Hey @dolinja,

Arrow no longer supports this functionality. Kotlin released context receivers experimentally for the JVM, and it will become MPP.

There is an ongoing effort in Arrow Inject repository that will solve the automatic injection typeclasses typically support to cover this same behaviour.
