### ISSUE TITLE
["Issue"] Duplicate `Either.orNull()` extension function and member function

### ISSUE THREAD

**Issue by hoc081098** [arrow-kt/arrow#2767]
What version are you currently using?
1.1.2

What would you like to see?

Duplicate `Either.orNull()` extension function and member function

https://github.com/arrow-kt/arrow/blob/feb3c446a52ba52eb3f0ed0b6e247163a1b1850e/arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt#L993

and

https://github.com/arrow-kt/arrow/blob/feb3c446a52ba52eb3f0ed0b6e247163a1b1850e/arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt#L1280

Is this a mistake or intention? Thanks!

**Comment by nomisRev** [comment]
That is a mistake @hoc081098. I guess the extensions method should be deprecated until Arrow 2.0 to not break binary compat.
