### ISSUE TITLE
["Request"] Setup Arrow 2.0 branch

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow#2768]
We've learned quite a lot from pre-Arrow 1.x.x, and post-Arrow 1.x.x.

A lot of improvements have been made such as `Effect`, and streamlining APIs further.
We also have `context receivers` on the horizon, and I think it's time we started shaping Arrow 2.0.

After some small discussions on Slack, and in the bi-weekly Arrow meeting (which is open for everyone to join) we agreed that the easiest way is to start an `2.0.0` branch where we can start making actual changes and discuss changes directly in PRs.
That way we'll have a better overview between the diff of `1.x.x` and `2.x.x`.

I think the biggest hurdle will be to keep `2.x.x` up-to-date alongside `1.x.x`, so ideally we'd have `1.x.x` automatically merged into `2.x.x` with Github issue creation if it fails to auto-merge.

**Comment by serras** [comment]
Closing in favor of #2778
