### ISSUE TITLE
[Arrow 2.0] Remove Validated and move methods to Either<NonEmptyList<E>, A>

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow#2787]
- [ ] Remove Validated
 - [ ] Remove `traverse`
 - [ ] Replace `zip` from `Either` to https://github.com/nomisRev/kotlin-gists/blob/d5943ef9dd09f765d32506508c481d3b80ac447d/src/main/kotlin/arrow2/Either.kt#L285
 - [ ] Add `mapAccumulating` for `Either` https://github.com/nomisRev/kotlin-gists/blob/d5943ef9dd09f765d32506508c481d3b80ac447d/src/main/kotlin/arrow2/Either.kt#L120

**Comment by Atternatt** [comment]
update: working on it

**Comment by serras** [comment]
Closed by #2795
