### ISSUE TITLE
Missing documentation for Validated

### ISSUE THREAD

**Issue by jakubgwozdz** [arrow-kt/arrow#2796]
Hi.

Something wrong happened to the docs.
They were beautiful in 1.0.1: https://github.com/arrow-kt/arrow/blob/1.0.1/arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Validated.kt

And they are missing in 1.1.2: https://github.com/arrow-kt/arrow/blob/1.1.2/arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Validated.kt

That makes using it a bit harder...

**Comment by nomisRev** [comment]
Hey @jakubgwozdz,

This was sadly due to the fact that the tool we use to validate code completely broke over the `Validated` documentation when we upgraded. So we felt forced to temporarily remove it. Thank you for making this ticket reminding us to re-add it.

However for Arrow 2.0 we're investigating merging `Validated` and `Either`. That would solve this problem as well 😅

**Comment by jakubgwozdz** [comment]
Thanks for the swift reply @nomisRev 

I assumed that 2.0 and this possible switch from Validated to Either is a song of distant future :) - I read somewhere else that you aim for Kotlin 1.9 or so...

And frankly my team is not using Arrow yet, but the Validated functionality looks so promising we probably will soon at least for this. Anyway, please consider fixing docs if you feel there's a point to it.

**Comment by nomisRev** [comment]
> is a song of distant future :) - I read somewhere else that you aim for Kotlin 1.9 or so...

I think that was a miss-understanding. Arrow 2.0 is aimed to release asap, but we're in the process of researching new implementations / APIs. Two have already been proposed, #2786 & #2782. 
All APIs will be back-ported, where applicable to ease the transition to any new APIs or potential breaking changes in 2.0.

> Anyway, please consider fixing docs if you feel there's a point to it.

We would love any contributions putting back the documentation! So anyone willing to put the time and effort into fixing the doc, and putting it back would be greatly appreciated. 🙏

Thanks for your interest in Arrow, cool to hear your team is considering adopting it. There is an active #arrow channel on KotlinLang Slack if anyone of your team is interested in joining there :)

**Comment by jakubboesche** [comment]
still waiting for the fix or 2.0... ;(((

**Comment by nomisRev** [comment]
Sorry, for the delay on this. All the new information should be on the new Arrow website, please check if this suffices for you. If you're missing anything please file a new issue not he https://github.com/arrow-kt/arrow-website repository.

Thank you for your patience, and support for Arrow 🙏
