### ISSUE TITLE
Can not compose Traversal with Getter

### ISSUE THREAD

**Issue by feser** [arrow-kt/arrow#2799]
Documentation for Traversal mentions that a `Traversal` can be composed with `Getter` which results in `Fold`.
https://arrow-kt.io/docs/optics/traversal/#composition

However, only following compose functions are available for `Traversal` which don't include `Getter`.
https://github.com/arrow-kt/arrow/blob/5d0bc9e214f9b92f8492a8202a7c165d5e81fa9e/arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Traversal.kt#L47
https://github.com/arrow-kt/arrow/blob/5d0bc9e214f9b92f8492a8202a7c165d5e81fa9e/arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Setter.kt#L56

This is required to get nested attribute without modifying it.
For example, getting `employeeStreetName` in Traversal usage example.
https://arrow-kt.io/docs/optics/traversal/#usage

Thanks in advance!

**Comment by serras** [comment]
It seems that the documentation is the culprit here. A `Traversal` in Arrow Optics is defined as something which modifies 0 to N elements, so it makes no sense to compose it with a `Getter`.

Just to double check, @raulraja @nomisRev, is this right? If so I'll open a PR to update the docs

**Comment by nomisRev** [comment]
Yes, I think you're right @serras.
`Getter` cannot compose with `Traversal` because it cannot satisfy the `modify` behavior of `Traversal.

**Comment by serras** [comment]
The new hierarchy in Arrow 2.0 (merged in #2873) is greatly simplified. This problem won't happen then. Closing this issue as a result.
