### ISSUE TITLE
[Documentation bug] >> is replaced by »

### ISSUE THREAD

**Issue by Arthur-Milchior** [arrow-kt/arrow#2809]
On https://arrow-kt.io/docs/apidocs/arrow-core/arrow.core/-ior/
you have `Either<Either<A,B>, Pair<A,B»`  that should be `Either<Either<A,B>, Pair<A,B>>`

**Comment by nomisRev** [comment]
This should be fixed by switching to Dokka HTML. We longer use the old Jekyll/GFM output. Please let us know if you encounter any bugs on the API docs, or website. Thank you for creating an issue 🙏
