### ISSUE TITLE
["Request"] Project is not compatible with Gradle 8.0

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow#2813]
What would you like to see?

Arrow should support Gradle 8.0. This is most likely something in https://github.com/arrow-kt/arrow-gradle-config

**Comment by JavierSegoviaCordoba** [comment]
Which is the part tha it is not compatible? I think the warning we are getting are related to Kotlin Gradle Plugin so we can only wait to update it when it is ready for 8.0

**Comment by nomisRev** [comment]
Someone on Slack said he was building the Arrow project using Gradle 8.0 (from within IDEA), and the project crashed.

**Comment by JavierSegoviaCordoba** [comment]
I am not sure if Kotlin supports 8.0 yet. I would try to compile a vanilla Kotlin project with no libraries using the latest 8.0.

But to be honest, the latest nightly is 7.7, so I am not sure if 8.0 even exists yet 🤔

**Comment by jasonab** [comment]
This is the relevant conversation: https://kotlinlang.slack.com/archives/C8UK6RTHU/p1662124353126499

He says he's "having trouble compiling" but I don't think anything crashed.

**Comment by serras** [comment]
We're currently running on Gradle 8.2 without issues, so this issue seems outdated
