### ISSUE TITLE
["Request"] Consider overloading Arrow Fx ParZip for tupling

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow#2821]
When working with `parZip` you often want to combine it with `Effect`, rather than exposing many variants of the API these API compose naturally. In Arrow 1.x.x we decided not to overload `parZip` with a default `lambda` for the size of the binary.

Since Arrow 2.0 will significantly reduce the size of the binary, we should consider adding these overloads again. For example, when ignoring results or turning values into a tuple it currently requires some annoying overhead.

```kotlin
either<E, Unit> {
  parZip(
    { computation().bind() },
    { computation().bind() }
  ) { _,_ -> }
}

either<E, Pair<Unit, Unit>> {
  parZip(
    { computation().bind() },
    { computation().bind() }
  ) { a, b -> Pair(a, b) } // ::Pair lambda reference is not allowed here due to the `CoroutineScope` receiver.
}
```

See discussion on Slack: https://kotlinlang.slack.com/archives/C5UPMM0A0/p1662715323510559

**Comment by lgtout** [comment]
@nomisRev Something like this, in addition to the [existing](https://github.com/lgtout/arrow/blob/99e50bd2b5dfcc452d401fc8acfdffd7172d685a/arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/ParZip.kt#L38-L38) `parZip`?  
```kotlin
public suspend inline fun <A, B> parZip(
  crossinline fa: suspend CoroutineScope.() -> A,
  crossinline fb: suspend CoroutineScope.() -> B,
):  Pair<A, B> = parZip(Dispatchers.Default, fa, fb) { a, b ->
    Pair(a, b)
}
```

**Comment by nomisRev** [comment]
Hey @lgtout,
Sorry for the late reply!

> Plus the same for [each](https://github.com/lgtout/arrow/blob/99e50bd2b5dfcc452d401fc8acfdffd7172d685a/arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/ParZip.kt#L157) parZip that takes a CoroutineContext?

Actually, we're going to remove these signatures and they should just take `context: CoroutineContext = EmptyCoroutineContext` as an argument. As done in this PR for [parTraverse](https://github.com/arrow-kt/arrow/pull/2863/files#diff-74bf2a702683ff9b5377a1d02d00a2708862d90d5d5dc25e72f675283ee14b1cR19). This is in line with what KotlinX Coroutines does and allows for better optimisations by Kotlin.

So the functions should be exactly as you've shown here:

```kotlin
public suspend inline fun <A, B> parZip(
  context: CoroutineContext = EmptyCoroutineContext,
  crossinline fa: suspend CoroutineScope.() -> A,
  crossinline fb: suspend CoroutineScope.() -> B,
):  Pair<A, B> = parZip(context, fa, fb) { a, b ->
    Pair(a, b)
}
```

This should be done for `Pair`, `Triple`, `Tuple4-9`.

Thanks for looking into this ticket @lgtout. You can just target this to `main` btw, since it's non-breaking ☺️

**Comment by lgtout** [comment]
@nomisRev Got it.  Thanks!

**Comment by lgtout** [comment]
@nomisRev Existing `parZip`s has overloads with up to 8 function parameters.  But you said you also want to return `Tuple 9`.  So should I add the missing overloads with 9 function parameters?  Thanks!

**Comment by nomisRev** [comment]
Yes, that would be great @lgtout! Thank you 🙏

**Comment by lgtout** [comment]
@nomisRev Should I write tests for the added `parZip`s?  I see that there are tests for the existing ones, but they seem to be generated by Knit from the documentation. And they don't appear to actually verify anything. They just print the result of running the `parZip`.  Thanks!

**Comment by nomisRev** [comment]
Hey @lgtout,
Here are the tests:

-  https://github.com/arrow-kt/arrow/tree/main/arrow-libs/fx/arrow-fx-coroutines/src/commonTest/kotlin/arrow/fx/coroutines/parMapN
- https://github.com/arrow-kt/arrow/blob/main/arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/arrow/fx/coroutines/ParMap2JvmTest.kt

Since the code in your PR should be derived from these methods, I don't think any additional tests are needed. WDYT?

**Comment by nomisRev** [comment]
Hey @lgtout,
The name `parMap` is legacy, feel free to flatten the tests directly into `arrow.fx.coroutines` or rename the folder to `parZip` 👍
Yes, adding the tests for the 9-arity function would also be great! 🙏

Thank you for being so thorough ☺️ 👏 🙌
