### ISSUE TITLE
[Add company logo]

### ISSUE THREAD

**Issue by blas233** [arrow-kt/arrow#2826]
**Company Name:**

**Website:**

**Logo:**

Please upload a high-res logo of either .svg or .png to this issue.

- [ ] By checking this box, I’m confirming that I have permission to add this company to the public list of users.

**Optional Information:**

Tell us a bit on how you’re using Arrow! We’d love to hear it:

**Comment by MaureenElsberry** [comment]
Hi @blas233 - we're you trying to add a company as using Arrow in Production or was this an accident? The answers are blank so you can either fill in the necessary info or let me know and we can close out the issue. 

Thanks!
