### ISSUE TITLE
["Request"] Check for missing bind() in either {} block

### ISSUE THREAD

**Issue by lukasz-kalnik-gcx** [arrow-kt/arrow#2841]
It would be nice to add an IDE warning for a missing `bind()` call if the result of a function returning `Either` inside an `either {}` block is not used.

Example:

```
interface Api {
    fun claimSystem(systemId: String): Either<CallError, System>
    fun connectToSystem(system: System): Either<CallError, Unit>
}

val systemId = "systemId"

either<CallError, System> {
    val system: System = api.claimSystem(systemId).bind()
    api.connectToSystem(system) // forgot to call bind(), but there is no IDE warning about this! Possible `CallError` will be ignored.
    system
}
```

**Comment by nomisRev** [comment]
Thank you for the issue report. This is something that we'd love to do, but it would require an IDEA plugin atm.

We're hoping that when K2 is complete, we can provide a more convenient way of doing this through a Gradle Plugin or even better through the Arrow dependency if that'd be possible somehow.

**Comment by lukasz-kalnik-gcx** [comment]
Thank you for the quick answer. Yes, that's just a "nice to have".

**Comment by nomisRev** [comment]
@pakoito I know it exists in Java, but not Kotlin 🤔

**Comment by lukasz-kalnik-gcx** [comment]
There is a whole discussion in the Kotlin [issue](https://youtrack.jetbrains.com/issue/KT-12719/Add-CheckResultMustUseReturnValueDiscardableResult-to-warn-about-unused-return-value) about reversing the default in Kotlin. The long-term plan is to require all non-Unit result from functions to be used, and the ones that can be ignored would have to be annotated with `@DiscardableResult`.
There is apparently nothing that could solve it right now though.

**Comment by lukasz-kalnik-gcx** [comment]
@pakoito Indeed, for my Android project the `@androidx.annotation.CheckResult` annotation indeed forces me to use the result! That could be a nice workaround, I "only" have to annotate all the functions returning `Either` ;)
Thanks for the suggestion.

**Comment by lukasz-kalnik-gcx** [comment]
Also `@io.reactivex.rxjava3.annotations.CheckReturnValue` produces the same Lint warning.
I think I will close it for now, because apparently there's no point to try implement some custom solution here in Arrow. Hopefully the language support will come soon, and until then there are at least some workarounds using the annotations.
