### ISSUE TITLE
["Request"] Publish SNAPSHOT or alphas for Arrow 2.x.x

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow#2848]
What version are you currently using?

1.1.x

What would you like to see?

2.x.x is currently in development, but no SNAPSHOT or alphas are being released. We should publish versions for 2.x.x so people can test them on projects already.

**Comment by serras** [comment]
@nomisRev we can close this one, right? Maybe we should push some small change to `README.md` in `main` so that people know these are being published.

**Comment by nomisRev** [comment]
Yes, we can close this issue after updating the `README.MD` 👍
