### ISSUE TITLE
Deprecated fun `exists` in Either was named `exist` in Validated which makes migration harder

### ISSUE THREAD

**Issue by Zordid** [arrow-kt/arrow#2938]
This function was previously known as `exist`, not `exists` - so coming from 1.1.5 to 1.1.6 or 1.2.0 breaks with unresolved reference if you exchange `Validated` with `Either` types.
Maybe it should not be added to mitigate transition to `Either`.

https://github.com/arrow-kt/arrow/blob/b3ef809e6543c7ef7a0558666ef88db3497ca389/arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt#L1085-L1091

**Comment by nomisRev** [comment]
Oof, that is indeed not correct. That rename must have accidentally gone unnoticed in the PR somehow 😞
Thanks for testing the `alpha` and opening these tickets 🙏

You mentioned on Slack that you were interested in contributing, this seems like a small fix you could pick-up as a first-contribution to get familiar with the process of contributing to Arrow. WDYT?

I'm happy to help with any issues you come across, if you don't have any time I'll pick up the issue before the 1.2.0 release 👍

**Comment by Zordid** [comment]
All right. Will give it a shot! Renaming functions is one of my strengths! :-D

**Comment by Zordid** [comment]
Ok, I sorted this one out deeper now. Turns out it is a little bit more complex.

In previous versions of Arrow, `Either` and `Option` had `exists` (with an s) and `Validated` has the `exist` function.
Both `Either` and `Option` deprecate their respective exists now in favor of `isRight` and `isSome` funs.

But: when migrating `Validated` to `Either` and using `EitherNel` as a drop-in replacement for `ValidatedNel`, consumers will face an `unresolved reference` on the exist call without proper assistance on what to do now.

One possibility would be to now *add* (and deprecate) the `exist` function to `Either`, but I am not sure whether this is wanted...

**Comment by Zordid** [comment]
Another option and possibly good idea is to deprecate `Validated.exist` and add a `Validated.exists` to align these functions.

**Comment by nomisRev** [comment]
> One possibility would be to now add (and deprecate) the exist function to Either, but I am not sure whether this is wanted...

I think that's a good idea. Adding an intermediate step for the migration is probably a good thing, even though it introduces an extra deprecated method. I'm proposing to do the same [here](https://github.com/arrow-kt/arrow/pull/2940/files#diff-44a762c203185e0889fe0fc1fbaf6a2ee7ed2960cac415256742a6fbbc4e23d3R1965).
