### ISSUE TITLE
Document use cases for `effect { }`

### ISSUE THREAD

**Issue by dave08** [arrow-kt/arrow#2945]
1. Deferring running of effects,
2. Composing effects before running in proper context,
3. Handling side effects at the last possible moment,
4. Having explicit exceptions in effect signatures

See thread on slack: https://kotlinlang.slack.com/archives/C5UPMM0A0/p1677146988286359

**Comment by serras** [comment]
Since `effect` is being deprecated as of Arrow 1.2.x, I'm closing this issue
