### ISSUE TITLE
Use Kotlin for build files

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow#295]
It would be nice to use Kotlin for the build files because the tooling is must better. This gradle feature is still experimental, but may be worth a shot.

**Comment by raulraja** [comment]
@pablisco, is this still relevant, or can we close it? Thanks!

**Comment by pablisco** [comment]
I personally would like to have a look at converting build scripts to Kotlin as they bring a nicer Dev Experience. I am not sure what are the issues we had in the past, I think the latest kts support is a lot better. Happy to do it after 1.0 though

**Comment by nomisRev** [comment]
@pablisco I'm going to close this ticket in favor of https://github.com/arrow-kt/arrow/issues/2190.

I think we already established that we want to do it now, after 1.0.0 and I think Kotlin Gradle is no longer experimental.
Let's discuss in the other ticket what we want to achieve, and which improvements we want to make to the current setup by moving to Kotlin.

I.e. writing a generic dokka, publish and ktlint method that can be re-used from all Arrow repos and potentially from anyone else that is interessted.
