### ISSUE TITLE
Fix deprecation replacements

### ISSUE THREAD

**Issue by gutiory** [arrow-kt/arrow#2964]
Some of the deprecation suggestions are not working when running `Replace with` action in `Intellij`. This is a bit annoying when we want to replace the deprecated method automatically.

The list of failed replacements is:

## Either
| Method | Working | Priority |
| ----------| ----------| ----------|
| all zip | NO |
| all | YES |
| bifoldLeft | YES |
| bifoldMap | NO |
| bimap | YES |
| bitraverseNullable | NO |
| bitraverseOption | NO |
| bitraverseValidated | NO |
| bitraverse | NO |
| catchAndFlatten | YES |
| catch | YES |
| combineK | YES |
| combine | YES |
| conditionally | YES |
| contains | YES |
| ensure | YES |
| exists | YES |
| filterOrElse | YES |
| filterOrOther | YES |
| findOrNull | YES |
| foldLeft | YES |
| foldMap | NO |
| fromNullable | YES |
| getOrHandle | YES |
| handleErrorWith | YES |
| handleError | YES |
| isEmpty | YES |
| leftIfNull | YES |
| orNone | YES |
| orNull | YES |
| orNull | YES |
| redeemWith | YES |
| redeem | YES |
| replicate | YES |
| replicate | YES |
| rightIfNotNull | YES |
| rightIfNull | NO |
| sequenceNullable | YES | 
| sequenceOption | YES |
| sequenceValidated | YES |
| sequence (list) | YES |
| sequence (option) | YES |
| sequence | YES |
| tapLeft | YES |
| tap | YES |
| toEither | NO |
| traverseNullable | NO |
| traverse | NO |
| traverse | NO |
| void | YES |
| all zips | YES |
 
## Ior 
| Method | Working | Priority
| ----------| ----------| ----------| 
| foldLeft | YES | |
| foldMap | YES | |
| bifoldLeft | YES | |
| bimap | YES | |
| padNull | YES | |
| orNull | YES | |
| all | YES | |
| exists | YES | |
| findOrNull | YES | |
| isEmpty | YES | |
| isNotEmpty | YES | |
| traverseEither | YES | |
| traverseOption | YES | |
| traverseValidated | YES | |
| void | YES | |
| getOrElse | YES | |
| bisequence | NO | | // fixed
| bisequenceEither | NO | | // fixed
| bisequenceOption | NO | | // fixed
| bisequenceNullable | NO | | // fixed
| bitraverseValidated | NO | |// fixed
| replicate | YES | |
| replicate - Monoid | NO | | // fixed
| sequence() | NO | | // fixed
| sequenceEither | YES | |
| sequence( Either ) | NO | | // fixed
| sequenceOption() | YES | |
| sequence( Option ) | NO | | // fixed
| sequenceNullable() | YES | |
| sequence( Nullable ) | NO | | // fixed
| sequenceValidated() | YES | |
| sequence( Validated ) | NO | | // fixed
| leftWiden() | NO | | // fixed
| zip (all)  | NO | | // All fixed
| bifoldMap | NO | |
| toValidated | NO | |
| bicrosswalk | NO | |
| bicrosswalkMap | NO | |
| bicrosswalkNull | NO | |
| bitraverse | NO | |
| bitraverseEither | NO | |
| bitraverseOption | NO | |
| bitraverseOption | NO | |
| bitraverseNullable | NO | |
| bitraverseValidated | NO | |
| crosswalk ( List ) | NO | |
| crosswalkMap | NO | |
| traverse ( List ) | NO |
| traverse ( Either ) | NO | |
| traverse ( Option ) | NO | |
| traverseNullable  | NO |
| traverse ( Validated ) | NO | |

**Comment by serras** [comment]
We already released 1.2.x, and the next is 2.0, so this issue is now outdated. Closing as a result.
