### ISSUE TITLE
["Request"] Fix incorrect Sequence signatures 

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow#2966]
What version are you currently using?

1.x.x

What would you like to see?

There are a bunch of `Sequence` signatures that in their signature give the impression that they're lazy, but in reality they're _terminal_ and consume the entire `Sequence` before returning.

From my short investigation it looks like these cannot be made lazy, but perhaps we can instead update their implementation for them to return `List` instead of `Sequence`.

- `crosswalk`
- `crosswalkMap`
- `crosswalkNull`
- `separateEither`
- `unalign`
- `unzip`

This might be possible to rewrite as a lazy version:

- `unweave` (investigate if can be made lazy)

**Comment by serras** [comment]
Implementations returning `List` have been added as part of #2993, and the incorrect ones marked for deprecation. We should remember to remove them in 2.0.

**Comment by nomisRev** [comment]
This was taken care of by @gutiory
