### ISSUE TITLE
["Request"] conditional modifying

### ISSUE THREAD

**Issue by stefanusayudha** [arrow-kt/arrow#3050]
What version are you currently using? latest

What would you like to see? 

i don't know if optics can do this, if it can i would love to know how..

the **"conditional modifying"** feature that will select and interact only with those matching the condition:

List<Model>.modify( condition : (Model) -> Boolean, mapper: (Model) -> Model ) : List<Model>

the select lambda working as a filter condition to which we will interact with.
the mapper bloc is the map function that capable to modify the object.

example: i have a list of car with many colors, i want to modify only the car with color of red.. 

the output that i expect is the same list with same length, that spesific items of the list been modified.

**Comment by ibado** [comment]
Hi there :wave:  Not sure if this is a super common use case but here is one way it could be implemented:

```kotlin
inline fun <T> Iterable<T>.modifyIf(shouldModify: Predicate<T>, modify: (T) -> T): Iterable<T> =
    map {
        it.takeIf { shouldModify(it) }?.let(modify) ?: it
    }
```

**Comment by serras** [comment]
I'm not sure either whether this is better than simply doing:

```kotlin
list.map { if (condition(it)) mapper(it) else it }
```

or if you want to be a bit more explicit even,

```kotlin
list.map {
  when {
    condition(it) -> mapper(it)
    else -> it
  }
}
```

**Comment by serras** [comment]
It seems that the consensus here is that this utility function is not worth including in the library, so I'm closing this issue.
