### ISSUE TITLE
["Request"] CyclicBarrier cancellation/reset

### ISSUE THREAD

**Issue by HSAR** [arrow-kt/arrow#3054]
What version are you currently using?
1.1.5

What would you like to see?
`java.util.concurrent.CyclicBarrier` supports interrupting awaited threads by offering a `reset()` method that interrupts all awaiting threads with a CancellationException. Something similar would be very useful in the implementation offered in this library: when called, it should interrupt all coroutines currently awaiting and cancel them.

**Comment by HSAR** [comment]
I have had an attempt at implementing this, see below. I can submit a PR and figure out the tests if that would be useful.

I added a boolean to the `State` class and check it at the start of the loop call during `await()`.

```
class CancellableCyclicBarrier(private val capacity: Int) {

    private data class State(
        val awaiting: Int,
        val epoch: Long,
        val reset: Boolean,
        val unblock: CompletableDeferred<Unit>
    )

    private val state: AtomicRef<State> = AtomicRef(State(capacity, 0, false, CompletableDeferred()))

    fun reset() {
        state.update { original -> original.copy(reset = true) }
    }

    /**
     * When [await] is called the function will suspend until the required number of coroutines have reached the barrier.
     * Once the [capacity] of the barrier has been reached, the coroutine will be released and continue execution.
     */
    suspend fun await() {
        state.loop { original ->
            if (original.reset) {
                throw CancellationException("CyclicBarrier was reset.")
            }

            val (awaiting, epoch, reset, unblock) = original
            val awaitingNow = awaiting - 1
            if (awaitingNow == 0
                && state.compareAndSet(original, State(capacity, epoch + 1, reset, CompletableDeferred()))) {
                unblock.complete(Unit)
                return
            } else if (state.compareAndSet(original, State(awaitingNow, epoch, reset, unblock))) {
                return try {
                    unblock.await()
                } catch (cancelled: CancellationException) {
                    state.update { s -> if (s.epoch == epoch) s.copy(awaiting = s.awaiting + 1) else s }
                    throw cancelled
                }
            }
        }
    }
}

```

**Comment by nomisRev** [comment]
Hey @HSAR,

Such functionality would be great if we can support more use-cases from `java.util.concurrent.CyclicBarrier`!

We'd need to write some test to check for edge-cases. I need to look at this a couple of times more to figure out if we're missing anything 😅 On first sight it would seem to me that `reset` needs to be checked first in the `when` block.

And can `compareAndCycleState` not result in a race condition in the `reset` function? 🤔

A PR with tests would be amazing! 🙏 Thank you for your interest in Arrow, and willingness to contribute 🙌

**Comment by HSAR** [comment]
I appreciate more eyes on the change - I had expected it to be a short and simple but as always it grew in complexity. I'm currently trying to use this in a production case so have written some tests myself to assure its base functionality, but must admit that I'm not an expert in concurrent programming so there is a very real possibility of having race conditions.

I'm trying a few other things, mostly via `unblock.cancel()`, and I'll see if I can put together a PR where we can discuss the state of my coding more directly. I do appreciate that I have somewhat ruined the elegant simplicity of the original class...
