### ISSUE TITLE
[Docs] parMapUnordered link under High-level concurrency is broken. (https://arrow-kt.io/docs/apidocs/arrow-fx-coroutines/arrow.fx.coroutines/par-map-unordered.html)

### ISSUE THREAD

**Issue by GuyKe** [arrow-kt/arrow#3069]
Expedia Group

expedia.com

![1225964](https://github.com/arrow-kt/arrow/assets/8113772/cf873e8f-9c90-428b-92a4-f7962a6fdae3)

- [ X] By checking this box, I’m confirming that I have permission to add this company to the public list of users.

it seems like this function isn't available in `1.2.0-RC` yet it exists in the docs.

**Comment by serras** [comment]
@GuyKe I'm having a bit of trouble finding out the link (or maybe one of the maintainers have already fixed the problem). Do you mean the link to `parMapUnordered` in https://arrow-kt.io/learn/coroutines/parallel/#flows?

**Comment by GuyKe** [comment]
Hey @serras , yeah that's right, `parMapUnordered` and I just notice that `parMap` link is broken as well

**Comment by serras** [comment]
It seems that the fix is applied in https://github.com/arrow-kt/arrow-website, but the new update hasn't been released yet. @nomisRev could you trigger the update? I'll close this issue in the meanwhile.
