### ISSUE TITLE
[Docs] Link under "builders" seems to be broken

### ISSUE THREAD

**Issue by laskovenko1** [arrow-kt/arrow#3083]
Link under "builders" leads to the parent section, but I suppose that it should lead to something more concrete:

> The preferred way to work with Either and Ior is to use [builders](https://arrow-kt.io/learn/typed-errors/).
https://arrow-kt.io/learn/typed-errors/either-and-ior/#using-builders

**Comment by laskovenko1** [comment]
I expected this link to be https://kotlinlang.org/docs/type-safe-builders.html

If I'm misunderstood the structure of the docs, feel free to close the issue.

**Comment by serras** [comment]
Thanks for catching it! Fixed in https://github.com/arrow-kt/arrow-website/pull/212
