### ISSUE TITLE
Documentation Status

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow#311]
Steps to contribute documents:
1. Pick a section not already :heavy_check_mark:  and claim it with a comment on the issue.
2. Clone this repository `git clone git@github.com:arrow-kt/arrow.git`
3. Docs are at `arrow-docs/docs/docs`
4. Build docs with `./gradlew clean :arrow-docs:clean :arrow-docs:runAnk`
5. Preview site with `~/.gem/ruby/2.4.0/gems/jekyll-3.5.2/exe/jekyll serve --source arrow-docs/build/site/`
6. If you have any questions join us at the kotlin slack channel https://kotlinlang.slack.com/messages/C5UPMM0A0

- [X] Quick Start #366
  - [x] Module description #634
- Data Types
  - [x] Option
  - [x] OptionT
  - [x] Either
  - [x] EitherT 
  - [x] Validated
  - [x] Try #312
  - [x] Ior #313
  - [x] Id
  - [x] Reader #314
  - [x] Kleisli #315
  - [x] State #316
  - [x] StateT #317
  - [ ] WriterT #318
  - [ ] Trampoline #319
  - [ ] Coproduct #320
  - [x] Eval
  - [x] NonEmptyList #321
  - [x] ListKW #322
  - [x] SequenceKW #323
  - [x] SetKW #324
  - [ ] MapKW #638
  - [ ] SortedMapKW #638
  - [ ] Weak #639 (removed from codebase) 
- Type classes
  - [x] Functor
  - [ ] FunctorFilter #330
  - [x] Applicative
  - [x] ApplicativeError #331
  - [ ] Foldable #332
  - [ ] Traverse #333
  - [ ] TraverseFilter #334
  - [x] Monad #335
  - [ ] MonadFilter #336
  - [ ] MonadReader #337
  - [ ] MonadWriter #338
  - [ ] MonadState #339
  - [ ] MonadCombine #340
  - [x] MonadError  #341
  - [x] Semigroup
  - [x] Monoid 
  - [ ] SemigroupK  #342
  - [ ] MonoidK  #343
  - [ ] Bifoldable  #344
  - [ ] Bimonad  #345
  - [ ] Comonad  #346
  - [X] Order  #347
  - [x] Eq  #348
- Effects
  - [x] IO  #349 
  - [x] Sync #588
  - [x] Async  #350
  - [ ] Effect
- Optics
  - [X] Iso #351
  - [X] Lenses
  - [X] Optional #352
  - [X] Prism #353
  - [x] Setter #388 
  - [X] Getter #389
  - [x] Fold #390
  - [x] Traversal #391
- Free
  - [ ] Free #325
  - [ ] FreeApplicative #326
  - [ ] Cofree #327
  - [ ] Coyoneda #328
  - [ ] Yoneda #329
- Patterns
  - [x] Glossary
  - [x] Monad Comprehensions #354
  - [ ] Comonad Comprehensions #355
  - [ ] Applicative Builder #356
  - [ ] Polymorphic programs #357
  - [ ] Free Algebras #358
  - [x] Error Handling #359
  - [x] Dependency Injection #360
  - [ ] Monad Transformers #361
  - [ ] Concurrency #362 
  - [ ] Optics #392
- Integrations
  - [x] Rx2 #363
  - [x] kotlinx.coroutines #468
  - [x] KindedJ
  - [x] Project Reactor
  - [ ] Retrofit   
- Generic
  - [x] `@product`
- [x] Credits #364
- [x] License #365

**Comment by earroyoron** [comment]
I was thinking about write about this documentation: https://arrow-kt.io/docs/arrow/data/coproduct/
but is pretty well explained here: https://arrow-kt.io/docs/generic/coproduct/#coproduct
so....??

**Comment by pakoito** [comment]
@earroyoron yep, we are slowly migrating from manual docs to dokka ones, and the links should be updated and they aren't -.-

**Comment by raulraja** [comment]
Closing this outdated issue. Quick update: we migrated most docs that made sense to kdocs and went over all existing data types in Arrow, adding missing documentation. Thanks to everyone for looking into this and helping out. Cheers!
