### ISSUE TITLE
["Request"] Keep `handleErrorWith` function

### ISSUE THREAD

**Issue by PavlosTze** [arrow-kt/arrow#3122]
What version are you currently using?
```
    // Data types and more
    implementation(platform("io.arrow-kt:arrow-stack:1.2.0"))
    implementation("io.arrow-kt:arrow-core")
    implementation("io.arrow-kt:arrow-fx-coroutines")
```

What would you like to see?
I can see that `handleErrorWith` function is deprecated, I would like to ask to keep it as is. It seems way more complex to use the `recover` functionality for some simple thins and I still haven't figured out how to do it in some instances e.g:
```
    override suspend fun getHourlyWeatherHistory(
        deviceId: String,
        date: LocalDate,
        forceUpdate: Boolean
    ): Either<Failure, List<HourlyWeather>> {
        return if (forceUpdate) {
            Timber.d("Forced update. Skipping db.")
            getHistoryFromNetwork(deviceId, date)
        } else {
            Timber.d("Non-forced update. Trying db first.")
            getHistoryFromDatabase(deviceId, date)
                .handleErrorWith {
                    getHistoryFromNetwork(deviceId, date)
                }
        }
    }
```
If I use the suggestion from Android Studio the `getHistoryFromNetwork` doesn't return an `Either` with `recover`, but returns a `List<HourlyWeather>`.

Also I can't make the following work with `recover`, compiler errors.
```
    override suspend fun getSearchSuggestions(
        query: String
    ): Either<Failure, List<SearchSuggestion>> {
        return addressRepository.getSearchSuggestions(query)
            .handleErrorWith {
                when (it) {
                    is CancellationError -> Either.Right(emptyList())
                    else -> Either.Left(it)
                }
            }
    }
```

**Comment by nomisRev** [comment]
Hey @PavlosTze,

Thanks for the bug report! First of all, let's see if we can fix your snippets (for documentation purposes)

In the first snippet, it's would need an additional `bind` when switching from `handleErrorWith` to `recover`.

```kotlin
    override suspend fun getHourlyWeatherHistory(
        deviceId: String,
        date: LocalDate,
        forceUpdate: Boolean
    ): Either<Failure, List<HourlyWeather>> {
        return if (forceUpdate) {
            Timber.d("Forced update. Skipping db.")
            getHistoryFromNetwork(deviceId, date)
        } else {
            Timber.d("Non-forced update. Trying db first.")
            getHistoryFromDatabase(deviceId, date)
                .recover {
                    getHistoryFromNetwork(deviceId, date).bind()
                }
        }
    }
```

In the second snippet you're returning `Either<E, A>`, and that would need to be changed to `A`.

```kotlin
    override suspend fun getSearchSuggestions(
        query: String
    ): Either<Failure, List<SearchSuggestion>> {
        return addressRepository.getSearchSuggestions(query)
            .recover {
                when (it) {
                    is CancellationError -> emptyList()
                    else -> raise(it)
                }
            }
    }
```

This way both snippets should compile, and work. Would be great if you could test them. I've been wondering a lot about `recover`, because there is one short-coming that is annoying with inference.

```kotlin
val original: Either<String, Int> = "failure".left()
val x = original.recover { -1 } // cannot infer `Left`, should be `Either<Nothing, Int>`
val y: Either<Nothing, Int> = original.recover [ -1 } // is fine because of explicit type
val z = original.recover { raise(MyError) } // is fine because of builder inference
```

Let's get some more opinions here, but I think we can consider keeping `handleErrorWith`, and perhaps also `handleError` because those are popular APIs and will not bloat the API or binary since they're only needed for `Either`.

Ideally the Kotlin compiler could infer `Nothing` for receiver lambda arguments when the receiver is unused, but perhaps we can get that feature in the future.

cc\\ @raulraja @franciscodr @serras

**Comment by PavlosTze** [comment]
@nomisRev The first one isn't working properly. This way, the return result of:
```
                .recover {
                    getHistoryFromNetwork(deviceId, date).bind()
                }
```
is `List<HourlyWeather>` based on what Android Studio says. The problem is that my original code:
```
                .handleErrorWith {
                    getHistoryFromNetwork(deviceId, date)
                }
```
returns an `Either<Failure, List<HourlyWeather>>` which is what I would want to. So I think in some cases the `recover` code will produce wrong results?

**Comment by PavlosTze** [comment]
@nomisRev Any news on the above? I still get the warning.

**Comment by nomisRev** [comment]
I am already going to call in some other maintainers for their opinions ☺️ I need to review this issue, and give it some more thought before properly replying again. I'm going to let this sink in this weekend, but without `@BuilderInference` being to infer `Nothing` the new API can indeed be annoying for inference.

cc\\ @serras @kyay10 @CLOVIS-AI

**Comment by serras** [comment]
I think that in fact we're missing that operation. My reasoning is that for a "complete" API for `Either` you need the 2 functorial functions (`map` and `mapLeft`), the `fold`, and the 2 monadic functions. In that latter bucket we had `flatMap` but had removed "`flatMapLeft`", or with the usual name, `handleErrorWith`. So I vote to bring back that single function for those with a more combinator-style programming style.

I've created a PR (https://github.com/arrow-kt/arrow/pull/3456) in case you agree with my reasoning.
