### ISSUE TITLE
`Iterable<A>.toNonEmptyListOrNull()` is broken for nullable `A`

### ISSUE THREAD

**Issue by mjadczak** [arrow-kt/arrow#3123]
The current implementation of this function is as follows:

```kotlin
public fun <A> Iterable<A>.toNonEmptyListOrNull(): NonEmptyList<A>? =
  firstOrNull()?.let { NonEmptyList(it, drop(1)) }
```

but when `A` is a nullable type, and the first element of the list is null, the function incorrectly returns `null`!

It's also probably not best practice to iterate the iterable twice, just in case it cannot be iterated multiple times, or it is costly to do so.

Here is a proposed replacement, which is admittedly less pretty, but doesn't have the same issue and only iterates the iterable once:

```kotlin
public fun <A> Iterable<A>.toNonEmptyListOrNull(): NonEmptyList<A>? {
    val iter = iterator()
    if (!iter.hasNext()) return null
    return NonEmptyList(iter.next(), Iterable { iter }.toList())
}
```

**Comment by nomisRev** [comment]
Hey @mjadczak,

Thank you for this bug report! 🙌 Ouch, nullability problems 🙈 So easy to sneak through when not using `Option` in generic context.

If you're interested in contributing this could be a great contribution!

**Comment by mjadczak** [comment]
@nomisRev submitted as #3127 - my first PR so please let me know if there's some extra bits I need to run (not sure if the various format and ABI checking runs as part of the normal CI)
