### ISSUE TITLE
["Request"] Lossy `nullable` builder

### ISSUE THREAD

**Issue by CLOVIS-AI** [arrow-kt/arrow#3138]
**Edit.** After @serras' comment, it is clear that Arrow already supports this feature. I'm therefore switching this issue to "mention the fact that it is supported in the documentation".

The rest of the text is the original body of this issue.

---

As of 1.2.0, the `nullable` builder takes a `Raise<Null>`, which only accepts raising `null`. I assume this is the case to avoid accidentally losing error messages by raising `Any`.

However, I often make overloads of my functions that return nullable values in case the real implementation raises. Currently, the best solution is `either { block }.getOrNull()`, which is not very explicit, and may be less performant (??).

I'd like to introduce a `nullableLossy` builder which introduces `Raise<Any?>`. If the block raises, no matter with what, the error is swallowed and only `null` is returned. Therefore, the 'nullable overload' use case will look like;

```kotlin
context(Raise<SomeError>)
fun foo() {
    …
}

fun fooOrNull() = nullableLossy { foo() }
```

**Comment by serras** [comment]
Closing this since we came to the conclusion that `ignoreErrors` was good enough.
