### ISSUE TITLE
Reader (and ReaderT) docs

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow#314]
They must be added **using kdocs** over the data type.

[An old PR](https://github.com/arrow-kt/arrow/pull/1062/files) got closed because of no changes in a very long time but had some `Reader` docs that we could use as a reference to write kdocs for `Reader` and `ReaderT`.

**Comment by iboss-ptk** [comment]
Would love to help with this but I wonder how to build docs?

**Comment by iboss-ptk** [comment]
Sorry, I didn't look into #311. Thank you :D

**Comment by nomisRev** [comment]
Closed due to deprecated
