### ISSUE TITLE
Refactor AtomicBooleanTest from Kotest Plugin to Kotlin-test runtime

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow#3144]
Arrow is migrating from the Kotest Multiplatform plugin to Kotlin-test,
not because we don't love Kotest but because Arrow wants to support experimental targets like wasm and be buildable and testable with Kotlin EAP & DEV version such that we can help the Kotlin team prevent regression. We're continue using Kotest property testing, and Kotest assertions.

Arrow needs the help of the community to do this, and the Arrow maintainers will be more than happy to help you through the progress.

This ticket requires following changes in `AtomicBooleanTest.kt`. Here is a small list of things to do:

 1. Fork & clone the Arrow repository
 2. Checkout the `arrow-2` branch and create a new branch from it.
 3. Replace all tests with shape `"name of test {"` to camelCase/dromedaryCase `@Test fun nameOfTest() = runTest {` in the test class
 4. Remove `StringSpec` as the super class from the test class
 5. Run `./gradlew spotlessApply`
 6. Commit your changes, and push the new branch to your repo
 7. Create a PR on the Arrow repository from your branch targetting `arrow-2`.

Arrow really appreciates all the help, and looks forward to a bright future together in Kotlin :party:

Thanks in advance!

**Comment by Gosunet** [comment]
I can do that 👍

**Comment by Gosunet** [comment]
Ah you already did it, i will do another one then

**Comment by nomisRev** [comment]
Apologies, I was doing some local testing and since I had the changes I pushed them. I am so sorry I didn't see your comment here first.

**Comment by Gosunet** [comment]
No worries!
