### ISSUE TITLE
IllegalAccessError when using Raise

### ISSUE THREAD

**Issue by CLOVIS-AI** [arrow-kt/arrow#3235]
Arrow version: 1.2.1

I'm trying to integrate `Raise` into my test library, [Prepared](https://gitlab.com/opensavvy/prepared). Since raising usually represents an error, I want to be able to declare that a test fails if an error is raised. To help with debugging, I'd like to enable tracing in those cases (since this is only for testing, I don't mind the performance implications).

I want to be able to declare something like:
```kotlin
test("Some test") {
    failOnRaise {
        raise(5)
    }
}
```

For now, here's the implementation I have:
```kotlin
@ExperimentalTraceApi
inline fun <Failure, Success> failOnRaise(block: Raise<Failure>.() -> Success): Success {
	val result = either {
		traced(block) { trace, error ->
			throw AssertionError("An operation raised $error\n${trace.stackTraceToString()}")
				.apply {
					for (suppressed in trace.suppressedExceptions())
						addSuppressed(suppressed)
				}
		}
	}

	check(result is Either.Right) { "Impossible situation: we throw an error when the passed block raises, but it still gave us a failed either: $result" }
	return result.value
}
```

However, when I execute it, I get:
```
java.lang.AssertionError: Expected exception java.lang.AssertionError but a IllegalAccessError was thrown instead.
```
The stack trace is unhelpful (it doesn't go further than the test function).

Do you know what could cause this?

---

The entire code is available [here](https://gitlab.com/opensavvy/prepared/-/merge_requests/18).

As an aside, would it be possible to expose the underlying exception in `traced`? It would be easier to simply mark it as the `cause` of the `AssertionError`.

**Comment by nomisRev** [comment]
Hey @CLOVIS-AI,

Your code doesn't compile for me 🤯 Removing `()` from `suppressedExceptions`, and works for me

```kotlin
for (suppressed in trace.suppressedExceptions)
  addSuppressed(suppressed)
```

But I think it's actually related somehow to how `suppressedExceptions` works, it uses reflection to get access to `getSuppressed`. https://github.com/JetBrains/kotlin/blob/f98451e38169a833f60b87618db4602133e02cf2/libraries/stdlib/jvm/src/kotlin/internal/PlatformImplementations.kt#L37
Calling `Method::invoke` from `java.lang.reflect` throws `IllegalAccessError `.

**Comment by CLOVIS-AI** [comment]
I don't understand it, then. The [Arrow documentation](https://apidocs.arrow-kt.io/arrow-core/arrow.core.raise/-trace/suppressed-exceptions.html) does say it is a function… It doesn't compile on my side if I try to access it any other way.

**Comment by kyay10** [comment]
Debugging, I think it has something to do with `RaiseCancellationException` being private, yet being used inside the inline method `traced`. I'm surprised that the compiler even allowed that. I think Kotlin doesn't allow that occurring with methods, but lets it happen with types, which results in client code trying to catch an exception of type `RaiseCancellationException`. I'm not sure how to reproduce this, but the fix is very simple. Testing locally, it seems to work. See #3316

**Comment by CLOVIS-AI** [comment]
Can confirm this is fixed [for me](https://gitlab.com/opensavvy/prepared/-/merge_requests/18) with Arrow 1.2.3.
