### ISSUE TITLE
Compatibility Kotlin Result

### ISSUE THREAD

**Issue by sFreezer** [arrow-kt/arrow#3242]
It would be great if there was a possibility in the library to convert a Kotlin Result to Either.

_first draft_: 
```
fun <T : Any?> Result<T>.toEither(): Either<Throwable, T> = this.fold(
    { Either.Right(it) },
    { Either.Left(it) }
)
```

**Comment by serras** [comment]
@sFreezer I'm closing this, but feel free to re-open if you would prefer another solution from our side :)
