### ISSUE TITLE
["Request"] Fix `NonEmptySet` functions returning `NonEmptyList`

### ISSUE THREAD

**Issue by 404-** [arrow-kt/arrow#3317]
What version are you currently using?
1.2.1

What would you like to see?
Fix `map`, `mapIndexed`, `flatMap`, `distinct`, and `distinctBy` of [NonEmptySet] to return `NonEmptySet` instead of `NonEmptyList`.

[NonEmptySet]: https://github.com/arrow-kt/arrow/blob/main/arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/NonEmptySet.kt

**Comment by serras** [comment]
This is by design, since we follow the same patterns as in the `kotlin.collections` library. For example, [here](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-set/) you can see that `Set::map` returns a `List`, not a `Set`.
