### ISSUE TITLE
["Request"] Improve the performance of Memoized DRF

### ISSUE THREAD

**Issue by kyay10** [arrow-kt/arrow#3319]
Originally [reported](https://slack-chats.kotlinlang.org/t/16144650/i-ve-been-doing-the-aoc-problems-in-kotlin-this-year-and-tod) on the Kotlin Slack.

To quote: 

> I've been doing the AoC problems in kotlin this year and today's problem involved caching a recursive search.  I tried using MemoizedDeepRecursiveFunction just to test it out but it is running incredibly slow.  I suspect something is wrong (maybe a bug?).  If i use DeepRecursiveFunction and manually cache it in a Map, the solution runs in ~ 400ms, but if i swap that out with MDRF, and the runtime jumps up to around 20 minutes.  Here is my usage: https://github.com/bj0/aoc-kotlin/blob/main/src/year2023/day12.kt#L122

Apparently, recreating the MDRF per outer call prevented that performance issue.
Looking at the code, It currently copies the map every single time a cache miss occurs. It also has to acquire the map to read from it.
I think it needs a concurrent map implementation instead, or perhaps some form of multi-reader, single-writer map.

**Comment by nomisRev** [comment]
> I think it needs a concurrent map implementation instead, or perhaps some form of multi-reader, single-writer map.

There is no KMP concurrent map we can easily rely on 😞 I've needed a concurrent map a lot of times in KMP in many projects. I find this really lacking in Kotlin(X).

**Comment by serras** [comment]
The just-merged PR #3296 should give enough options (for example, using Java's `ConcurrentHashMap`). If we can think of a better out-of-the-box solution without dependencies, that would be great, though.
