### ISSUE TITLE
`Foldable` docs

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow#332]

**Comment by richard-gibson** [comment]
Happy to take this if nobody is working on it

**Comment by pakoito** [comment]
@richard-gibson Perfect! Thank you :D You can check the format we use in other typeclass docs:

* We have a short intro mentioning what behavior they abstract, and which other typeclasses it inherits from
* sometimes a section depicting the main use case is placed here, i.e. Applicative has a long desctiption of applicative builders
* then go through the main combinators/operators/functions with a short description of what they can be used for. This also includes a snippet
* afterwards we mention any piece of syntax available for the operators
* then we have a short section mentioning that Arrow provides laws for this typeclass
* and finally we link all the datatypes that provide an implementation of this typeclass

**Comment by AdrianRaFo** [comment]
I'll take this if there is no problem
