### ISSUE TITLE
["Request"] Sequence + .bind() throws RaiseLeakedException

### ISSUE THREAD

**Issue by JosephDCRB** [arrow-kt/arrow#3324]
Using arrow 1.2.1

When using Sequences, I suppose because they are lazy, .bind() can end up executing 'outside' DSL scope. Here is a minimal example:
```kotlin
        val seq: Sequence<Either<String, Int>> = sequenceOf("a".left(), 1.right())
        val seq2: Either<String, Sequence<Int>> = either { seq.map { it.bind() } }
        seq2.map { println(it.joinToString(", ")) }
```
Throws:
```
arrow.core.raise.RaiseLeakedException: raise or bind was called outside of its DSL scope, and the DSL Scoped operator was leaked
This is kind of usage is incorrect, make sure all calls to raise or bind occur within the lifecycle of effect { }, either { } or similar builders.
```
The error message is reasonably clear, but I thought it would be helpful to report in case you decide the code should flash a warning when using .bind() with Sequence or other lazy code.

**Comment by serras** [comment]
Unfortunately this is inherent to the way `raise` works. We are trying to add a few more safeguards in #3329, and welcome any more ideas to warn users beforehand of this problem.

**Comment by serras** [comment]
Note that the problem there is not itself calling `bind` in a sequence, which is OK, but the fact that `seq2` captures the `Raise<E>` context.

**Comment by serras** [comment]
Closing this one because of #3329, feel free to re-open it if you think we could / should do more on this regard.
