### ISSUE TITLE
["Request"] Android Jetpack Room OPTION integration

### ISSUE THREAD

**Issue by postfixNotation** [arrow-kt/arrow#3331]
What version are you currently using?
**1.2.1**

What would you like to see?

If suspend method queries are returned from Room there's a chance that a runtime exception occurs if the return type is non-null asserted and the query results in an empty set which makes the method return null.

I described the issue in full detail here https://issuetracker.google.com/issues/317287639

I would like to see an `Option` integration so that suspend methods return `Option<T>` so that these nullability issues don't occur.

```
@Query("SELECT * FROM user WHERE id = :id")
suspend fun loadUserById(id: Int): Option<User>
```

**Comment by serras** [comment]
This is a bit out of scope for this project. However, you can get the behavior you want by using [`Option::catch`](https://apidocs.arrow-kt.io/arrow-core/arrow.core/-option/-companion/catch.html).

```kotlin
@Query("SELECT * FROM user WHERE id = :id")
suspend fun _loadUserById(id: Int): User

suspend fun loadUserById(id: Int): Option<User> =
  Option.catch { _loadByUserId(id) }
```
