### ISSUE TITLE
Road to 1.2.3

### ISSUE THREAD

**Issue by serras** [arrow-kt/arrow#3365]
This is a list of things to be done to release 1.2.2

- [ ] Rewrite documentation about [resource safety](https://arrow-kt.io/learn/coroutines/resource-safety/) to mention `AutoCloseScope` (@nomisRev)
    - [x] Add to release notes
- [x] Merge https://github.com/arrow-kt/arrow/pull/3359
    - [x] Merge into `arrow-2` 
    - [x] Add to release notes
    - [x] Update documentation https://github.com/arrow-kt/arrow-website/pull/273
- [x] Merge https://github.com/arrow-kt/arrow/pull/3360 (@serras)
    - [x] Merge into `arrow-2` 
    - [x] Add to release notes
    - [x] Prepare documentation
- [x] Remove `widen` from `arrow-2` https://github.com/arrow-kt/arrow/pull/3369
- [x] Release new version of https://github.com/arrow-kt/arrow-gradle-config (@nomisRev, @franciscodr)
    - [x] Add support for WebAssembly target
- [x] `forEachAccumulating` https://github.com/arrow-kt/arrow/pull/3367
    - [x] Add to release notes
    - [x] Prepare documentation https://github.com/arrow-kt/arrow-website/pull/274
- [x] Update `arrow-stack` to contain all projects https://github.com/arrow-kt/arrow/pull/3372
- [ ] Release 1.2.2
- [x] Update the [overview page](https://arrow-kt.io/learn/overview/): `arrow-autoclose`, `arrow-eval`, `arrow-collectors`, `arrow-functions` (only 2.0), `arrow-high-arity`, `arrow-optics-compose` https://github.com/arrow-kt/arrow-website/pull/275
    - [x] Merge all PRs in https://github.com/arrow-kt/arrow-website/pulls ensuring that Knit compiles
- [ ] Merge the https://github.com/arrow-kt/arrow-website/pull/269
- [x] Public announcement

**Comment by objektwerks** [comment]
As it pertains to any document updates, I would respectfully suggest adding imports to code samples. Intellij struggles to find the correct import at times. To wit, I struggled finding the correct zipOrAccumulate import. Thanks! :)

**Comment by nomisRev** [comment]
Hey @objektwerks,

We have that planned but in a slightly different way. Most code snippets are backed by KotlinX Knit, which generates actual Kotlin files which can be linked.

That Gradle setup part is however still missing, but it'll allow you to jump to the complete Kotlin files on Github. We have this planned for right after the release, since we don't want to continue dragging this release along. Just wanted to let you know it's on the roadmap for right after this patch release 👍 

Thank you for the feedback!

**Comment by objektwerks** [comment]
Thanks for the update - much appreciated! And all the best with your new release! Cheers! :)

**Comment by hoc081098** [comment]
1.2.2 is out 😂

**Comment by jay-peper** [comment]
Hmm, 1.2.2 isn't listed as release here on GH and it doesn't seem to be on maven-central either

**Comment by hoc081098** [comment]
> Hmm, 1.2.2 isn't listed as release here on GH and it doesn't seem to be on maven-central either

https://github.com/hoc081098/kotlin_playground/pull/45

**Comment by serras** [comment]
Just to give a heads up to everybody interested, because of #3380 and #3381, we'll be releasing 1.2.3 and announcing that one instead.
