### ISSUE TITLE
["Request"] DefaultedMap

### ISSUE THREAD

**Issue by terminalnode** [arrow-kt/arrow#3366]
**What version are you currently using?**
1.2.0

### What would you like to see?
In one of my projects I've implemented a class I call `DefaultedMap`, which I think would be a good fit for arrow. I don't mind implementing it in Arrow, but looking to see if you agree with me that it's a good fit.

The defining function of the `DefaultedMap` is that any key not in the map will return a pre-defined default value. Using kotest assertions, this describes the behavior of the DefaultedMap:
```kt
val normalMap = mapOf("a" to 1, "b" to 2)
val defaultValue = 69
val defaultedMap = normalMap.toDefaultedMap(defaultValue)

// For values defined in the underlying map, the two produce the same result
normalMap["a"] shouldBe defaultedMap["a"]
normalMap["b"] shouldBe defaultedMap["b"]

// For values not defined in the map, normalMap returns null
// but defaultedMap returns the defaultValue
normalMap["c"] shouldBe null
defaultedMap["c"] shouldBe defaultValue

// For any other methods in the Map interface,
// DefaultedMap returns the same value as a normal map
normalMap.entries shouldBe defaultedMap.entries
normalMap.keys shouldBe defaultedMap.keys
normalMap.size shouldBe defaultedMap.size
normalMap.values shouldContainExactlyInAnyOrder defaultedMap.values
normalMap.isEmpty() shouldBe defaultedMap.isEmpty()
normalMap.containsValue(x) shouldBe defaultedMap.containsValue(x)
normalMap.containsKey(x) shouldBe defaultedMap.containsKey(x)
```

### Convenience methods
In my project I also have some convenience methods.
- `fun <K, V> Map<K, V>.toDefaultedMap(default: V): DefaultedMap<K, V>
- `fun <K, V> defaultedMapOf(default: V, vararg pairs: Pair<K, V>): DefaultedMap<K, V>`
- `fun <K, V> defaultedMapOf(default: V, map: Map<K, V>): DefaultedMap<K, V>`

The `toDefaultedMap` also has variants when the value type is some kind of `Collection`, defaulting the `default` parameter to the empty version of this collection. For example:
`fun <K, V> Map<K, List<V>>.toDefaultedMap(default: List<V> = emptyList()): DefaultedMap<K, V>`

### What's the use-case?
The specific use-case for which I originally created this was to avoid null responses when creating mapped data loaders in GraphQL. For example if I fetch something by userId, then `groupBy` the results my userId I may have `userId`s for which the resulting map returns `null`. Before the `DefaultedMap` my solution for this was to add something like `inputs.associateBy { map[it].orEmpty() }`, this can now be replaced with `map.toDefaultedMap()` or `defaultedMapOf(emptyList(), map)`.

One could also imagine the `DefaultedMap` taking a lambda (a `(K) -> V` would make sense I think) as its default, perhaps memoizing the result by saving it to the map.

### Why in Arrow?
In my head, this is quite similar to classes such as `NonEmptyList` and `NonEmptySet`, serving the purpose of avoiding things like `xs.getFirstOrNull() ?: someDefault` and similar issue.

**Comment by kyay10** [comment]
Is this not covered by [stdlib](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/with-default.html) `withDefault`?

**Comment by terminalnode** [comment]
> Is this not covered by [stdlib](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/with-default.html) `withDefault`?

Didn't know about that method! 😅 That's neat and covers almost everything. There's one neat feature of having it in a wrapping class though, and that's that you can override the `get` method to return `V` instead of `V?`, and avoid either banging or null coalescing an output that you already know is not null.

It does make the concept a lot less useful though, as it covers most of the use-cases (and the use-case I mentioned in particular).

**Comment by kyay10** [comment]
`get` being nullable by default is annoying. `getValue` exists, but sometimes I wish it'd be the default, with a `getOrNull` function instead. Maybe we can do something here, but it would be sort of strange to redefine all of this in Arrow just to get better typing for that one method.

This could be a good stdlib request to expose their `MapWithDefault` interface

**Comment by nomisRev** [comment]
I agree with @kyay10, this is already partially covered by Kotlin Std, and I don't think it really belongs in Arrow. Regardless of that I think `MapWithDefault` would be beneficial.

Beware that `get` doesn't actually return the value defined by `withDefault { }` AFAIK, and it requires using `getValue`. At least this used to be the case, not sure if this has been fixed yet.

This is because `get` is defined on `Map`, and doesn't use the Java's `get` and thus ignore the `withDefault { }` handler.

**Comment by nomisRev** [comment]
I'm going to close the issue for now, but feel free to re-open or discuss further ☺️
