### ISSUE TITLE
["Request"] Raise DSL for working with nonEmptyLists

### ISSUE THREAD

**Issue by Kantis** [arrow-kt/arrow#3393]
What version are you currently using? `1.2.3`

What would you like to see?

Given a regular `List<T>`, it would be nice to have Raise DSL support for ensuring the list is either empty or non-empty, which can help convert the data to `NonEmptyList<T>`. 

This would provide an idiomatic way of refining `List<T>` to to `NonEmptyList<T>`

Suggestion:
```kotlin
val maybeEmptyList = listOf<T>(...)
val myNel = ensureNotEmpty(maybeEmptyList) { DomainError } // Nel<T> if successful, raises DomainError otherwise
```

The inverse, ensuring a list **is** empty can also be useful
```kotlin
val maybeEmptyList = listOf<T>(...)
ensureEmpty(maybeEmptyList) { nel ->
  DomainErrorWithNel(nel) // some problem which wants to include the offenders..
}
```

## Open considerations

How does this interact with `nonEmptySet`?

**Comment by hoc081098** [comment]
I think we can use `ensureNotNull` with `toNonEmptyListOrNull`

```kotlin
effect {
    val nel = ensureNotNull(maybeEmptyList.toNonEmptyListOrNull()) { "List is empty" }
   // use nel
}
```

**Comment by Kantis** [comment]
Sure but it gets rather verbose and doesn't signal intent as clearly, imo. Plus, I don't think it solves the inverse?

**Comment by serras** [comment]
Unfortunately, we cannot provide specialized operations in the library for every possible check. @hoc081098's approach is maybe the best one, since it merges the check and the change of type.
