### ISSUE TITLE
["Bug"] Arrow core 1.2.4 not compatible with Kotlin WASM JS

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [arrow-kt/arrow#3407]
What version are you currently using?
1.2.4

What would you like to see?
Be able to use Arrow in my Kotlin Multiplatform project.
Repo: (I reverted the arrow commit)
https://github.com/Ivy-Apps/learn

**Repro:**
1. Try adding arrow as a dependency to the `:composeApp` module.

```
Could not resolve io.arrow-kt:arrow-core:1.2.4.
  Required by:
      project :composeApp
   > No matching variant of io.arrow-kt:arrow-core:1.2.4 was found. The consumer was configured to find a library for use during 'kotlin-api', preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm', attribute 'org.jetbrains.kotlin.wasm.target' with value 'js' but:
 ```

**Comment by serras** [comment]
Unfortunately, we had to postpone publishing artifacts for WebAssembly until 2.0 :(

**Comment by serras** [comment]
Since #3416, we build the library with Wasm JS too. So the new version would definitely contain those artifacts :)

**Comment by fethij** [comment]
@serras any eta on the next release that includes #3416 ?
