### ISSUE TITLE
Update Arrow 2.0.0-alpha.2 misses a dependency

### ISSUE THREAD

**Issue by Atternatt** [arrow-kt/arrow#3440]
What version are you currently using?
Updating to Arrow 2.0.0-alpha.2 I faced an issue:

```
> Task :database:compileKotlinIosArm64 FAILED
e: KLIB resolver: Could not find "io.arrow-kt:arrow-continuations" in [/Users/marc/IdeaProjects/Archer, /Users/marc/.konan/klib, /Users/marc/.konan/kotlin-native-prebuilt-macos-aarch64-2.0.0/klib/common, /Users/marc/.konan/kotlin-native-prebuilt-macos-aarch64-2.0.0/klib/platform/ios_arm64]
```
seems that a dependency that is no longer present is not found.

Our initial guess is that perhaps kotest arrow is using them but we didn't find any evidence running a `dependency` task so we are a bit confused

**Comment by serras** [comment]
Could you send the output of `./gradlew -q dependencies`?

**Comment by Atternatt** [comment]
[here](https://github.com/m2f-kt/Archer/pull/35) the changes (gradle/libs.versions.toml specifically)

and here de dependencies (to make it work in the PR I added explicitly the 
```arrow-continuations = { module = "io.arrow-kt:arrow-continuations", version.ref = "arrowContinuations" }``` but i removed it in the dependencies gradle task as it's how it fails:
[deps.txt](https://github.com/arrow-kt/arrow/files/15476747/deps.txt)

**Comment by serras** [comment]
This should be fixed in `alpha.3`
