### ISSUE TITLE
["Request"]  DSL method for validation

### ISSUE THREAD

**Issue by koswag** [arrow-kt/arrow#3485]
### What version are you currently using?  
1.2.4

### What would you like to see?

Hey guys, first of all I love Arrow and how well it cooperates with Kotlin, hell of a good job!

My main use-case for the `Either` type is parallel validation. For that I use `zipOrAccumulate` of course:

```kotlin
either {
    zipOrAccumulate(
        { ensure(conditionA) { ErrorA } },
        { ensure(conditionB) { ErrorB } },
        { ensure(conditionC) { ErrorC } },
    ) { _, _, _ ->
       ResultIfValid(...)
    }
}
```

It was always quite weird to me that Raise DSL doesn't include a method that would just execute all validation checks ignoring their results, cause usually I just discard trailing lambda arguments, as above. I now implemented something like this:

```kotlin
@RaiseDSL
fun <Error> Raise<NonEmptyList<Error>>.accumulateErrors(
    vararg validationChecks: Raise<Error>.() -> Unit,
) {
    mapOrAccumulate(validationChecks.asIterable()) { check -> check() }
}

// usage:
either {
    accumulateErrors(
        { ensure(conditionA) { ErrorA } },
        { ensure(conditionB) { ErrorB } },
        { ensure(conditionC) { ErrorC } },
    )

    ResultIfValid(...)
}
```

I find this approach much cleaner, as adding a new validation check doesn't require adding another lambda argument which is usually discarded anyway. It also reads more declaratively I think: _"The result is either accumulated errors or ResultIfValid"_

The difference is cosmetic, but few people I've been working with, who had no prior experience with Arrow, got quite scared by the `zipOrAccumulate` syntax (in the first example we don't even zip anything). It's also annoying that the compiler immediately starts to complain when there are not enough lambda parameters, as it makes experimenting and refactoring harder.

**Comment by serras** [comment]
This is actually work-in-progress in https://github.com/arrow-kt/arrow/pull/3436. You'll be able to wrap each of the `ensure` in `accumulate` to get the behavior you want.

**Comment by serras** [comment]
#3436 has been merged.
