### ISSUE TITLE
Documented vs actual behavior mismatch in combine function

### ISSUE THREAD

**Issue by marinomeneghel** [arrow-kt/arrow#3496]
Arrow core `1.2.1` exposes a `combine` method with the following signature:
```
public fun <A, B> Either<A, B>.combine(other: Either<A, B>, combineLeft: (A, A) -> A, combineRight: (B, B) -> B): Either<A, B>
```

The method's docs, states:
> Combine two [Either] values.
> If both are [Right] then combine both [B] values using [combineRight] or if both are [Left] then combine both [A] values using [combineLeft], 
> otherwise it returns the `this` or fallbacks to [other] in case `this` is [Left].

which makes me intend that in case one of the two given either is "right", that'll be the one returned ("otherwise it returns the `this` or fallbacks to [other] in case `this` is [Left].")

The current behavior, is actually the opposite though with the "left" one being returned (in case there's one "left" and one "right").
```
  when (val one = this) {
    is Left -> when (other) {
      is Left -> Left(combineLeft(one.value, other.value))
      is Right -> one
    }

    is Right -> when (other) {
      is Left -> other
      is Right -> Right(combineRight(one.value, other.value))
    }

```

My question is, which of the two is the wanted behavior?

**Comment by Sujin1135** [comment]
In Arrow core 1.2.4, The method documentation in the code states:

``` kt
/**
 * Combine two [Either] values.
 * If both are [Right] then combine both [B] values using [combineRight] or if both are [Left] then combine both [A] values using [combineLeft],
 * **otherwise return the sole [Left] value (either `this` or [other]).**
 */
public fun <A, B> Either<A, B>.combine(other: Either<A, B>, combineLeft: (A, A) -> A, combineRight: (B, B) -> B): Either<A, B> =
  when (val one = this) {
    is Left -> when (other) {
      is Left -> Left(combineLeft(one.value, other.value))
      is Right -> one
    }

    is Right -> when (other) {
      is Left -> other
      is Right -> Right(combineRight(one.value, other.value))
    }
  }
```

So It seems that it was already modified and intend to return Left in the otherwise case.

**Comment by marinomeneghel** [comment]
Missed that, thanks.

I guess there's no API to combine two either returning the sole `right` one instead? (I didn't see one in `1.2.4`, just confirming I didn't miss anything).

**Comment by Sujin1135** [comment]
@marinomeneghel It isn't included in arrow-core, But I think you can define a custom extension method for the sole `right` case as follows:

``` kt
/**
 * Combine two [Either] values.
 * If both are [Right] then combine both [B] values using [combineRight] or if both are [Left] then combine both [A] values using [combineLeft],
 * otherwise return the sole [Right] value (either `this` or [other]).
 */
public fun <A, B> Either<A, B>.combineOrRight(other: Either<A, B>, combineLeft: (A, A) -> A, combineRight: (B, B) -> B): Either<A, B> =
  when (val one = this) {
    is Left -> when (other) {
      is Left -> Left(combineLeft(one.value, other.value))
      is Right -> other
    }

    is Right -> when (other) {
      is Left -> one
      is Right -> Right(combineRight(one.value, other.value))
    }
  }
```

How do you feel about it?
