### ISSUE TITLE
Arrow resilience causes an `undeclared type variable: Input` error when compiling

### ISSUE THREAD

**Issue by dave08** [arrow-kt/arrow#3499]
I used this code:
```kotlin
private val recur2 = Schedule.recurs<CallError>(3)

...
recur2.retryEither {
   searchApi.getSuggestions(...) // returns an Either<CallError, List<String>>
}
```
and I get this error when compiling:
```
error: cannot access SearchSuggestionsViewModel
    public abstract ViewModel binds(SearchSuggestionsViewModel vm);
                                    ^
  bad class file: /home/.../app/build/tmp/kotlin-classes/debug/.../searchScreens/SearchSuggestionsViewModel.class
    undeclared type variable: Input
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Comment by dave08** [comment]
See #3325 for a similar issue.

It seems like the problem is that Schedule is a value class... I removed value and @JvmInline and it works... it would be nice to be able to keep it as a value class, but if it doesn't work otherwise... then it's not the worst thing to not have it.

**Comment by dcampogiani** [comment]
@serras I'm getting a similar error while upgrading to 2.x, but related to `NonEmptyList`.

I do not know the internals but I saw you migrated Schedule away from `value class`, and `NonEmptyList` is a `value class`.

Is this related?
