### ISSUE TITLE
`Comonad Comprehensions` docs

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow#355]

**Comment by Sintrastes** [comment]
@raulraja What is the idea behind this? Is this based on Dominic Orchard's [codo notation](https://github.com/dorchard/codo-notation)? Or is this something different?

**Comment by nomisRev** [comment]
Closed due to deprecated

**Comment by nomisRev** [comment]
@Sintrastes I think that was exactly the idea behind this. To build a specialised DSL to work with Comands similar to the one we have for monads.

This is closed due to `inteface Comonad` being deprecated, but might come back in specialised DSLs for concrete comonads in the future.
