### ISSUE TITLE
Documentation maven url is incorrect

### ISSUE THREAD

**Issue by dgoetsch** [arrow-kt/arrow#430]
Creating an issue for continuity..

I noticed that the documentation has the wrong maven url for setting up a project, `https://kotlin.bintray.com/kotlinx` should be `https://dl.bintray.com/kategory/maven`

I've created an MR to fix the docs:
https://github.com/kategory/kategory/pull/429

Cheers!

**Comment by pakoito** [comment]
Fixed and merged! Thanks @dgoetsch
