### ISSUE TITLE
Native kotlin null management to Option conversion

### ISSUE THREAD

**Issue by ColinHebert** [arrow-kt/arrow#432]
Would it make sense to have tools to allow a quick conversion from kotlin native way of handing nulls (`Object?`) to kategory's way of dealing with it (`Option<Object>`).

It's pretty trivial to do and can allow easy conversions:

```kotlin
fun <T : Any> T?.toOption(): Option<T> = this?.some() ?: none()
fun <T> Option<T>.toNative(): T? = this.getOrElse { null }
```

Arguably it could also be `fun <T : Any> T?.toOption(): Option<T> = Option.fromNullable(this)` for the first one, but really anything will do.

**Comment by pakoito** [comment]
We'd happily accept a PR with it, and IIRC @ffgiraldez already proposed it. If you don't want to make the PR yourself, any of our maintainters will happily do it, as it's short :D

**Comment by ColinHebert** [comment]
Awesome, I wanted to sanity check that change in case someone else already suggested it and it was refused for good reasons I might ignore.

**Comment by pakoito** [comment]
I believe this is already in the repo!
