### ISSUE TITLE
Multi-thread Observables should run on their required threads FAILED

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow#436]
Second time I have encountered this in 1 week.

kategory.effects.ObservableKWTest > ObservableKWTest.Multi-thread Observables should run on their required threads FAILED
    java.lang.AssertionError

**Comment by pakoito** [comment]
Is it intermittent or consistent? Could you please run with -i to get the full stack.

**Comment by nomisRev** [comment]
It is intermittent. I restarted build because it was release build on master.
I shall add the `-i` flag in the after deploy commit so we can monitor it.

**Comment by pakoito** [comment]
It seems to be gone now.
