### ISSUE TITLE
Add Kategory example to googlesamples/android-architecture

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#454]
Add an example of how to build an FP architecture in Android to https://github.com/googlesamples/android-architecture

**Comment by pakoito** [comment]
@JorgeCastilloPrz is this something you'd be excited about? :D

**Comment by JorgeCastilloPrz** [comment]
Definitely. I'll open the first [required issue](https://github.com/googlesamples/android-architecture/blob/master/CONTRIBUTING.md) asking for "permission" to build it.

**Comment by JorgeCastilloPrz** [comment]
[Here](https://github.com/googlesamples/android-architecture/issues/461) it is @pakoito . Please provide any further comments that you find important on the issue, if I forgot to mention anything!

Also, take into account that this would be the "formal approach" to start the development flow over that repo, so we need to wait for them to give permission.

Hooray!

![crazy dance](https://media.giphy.com/media/xe9csf50g4SqY/giphy.gif)

**Comment by JorgeCastilloPrz** [comment]
Ok. @JoseAlcerreca gave the green light. The idea is to take a look at the resting samples and try to implement something equivalent using Kategory. Architecture samples seem to be quite basic but understandable enough, so the main concern is to make the sample readable and didactic.

**Comment by pakoito** [comment]
Cool, let's have a chat later with @raulraja about which style we'd like to have represented.

**Comment by JorgeCastilloPrz** [comment]
One question. I guess the most basic and didactic approach could be a stack of transformers? Not sure if going further for tagless final or Free is a good idea for a blueprint. Ideas?

**Comment by JorgeCastilloPrz** [comment]
Also, feels like they don't integrate all the PRs but mainly link to them as "external samples". Not sure if then we might want to push it under the kategory org or what. [Mostly following this](https://github.com/googlesamples/android-architecture/issues/412)

**Comment by JorgeCastilloPrz** [comment]
Ok they clarified now: Separate repo to link it from README. 
https://github.com/googlesamples/android-architecture/issues/461#issuecomment-343681827

So it would be time to discuss what the sample should be showcasing, and if we want to write a new one under the kategory org, or we might just use my sample KotlinAndroidFunctional repo to keep the work over it (which already provides different approaches and docs by medium posts). 

I am ok with any choice.

**Comment by pakoito** [comment]
I'd rather it was within the org, so I can work on it too (legal requirements etc)

**Comment by JorgeCastilloPrz** [comment]
No problem with that. Let's work on it here.

**Comment by raulraja** [comment]
I think the Monad transformers style with a thin wrapper over the `typealias` based on extension functions is what it would be easier for users to understand. I'd preffer tagless but given how complex the inline reified biz is at the moment for type classes it's gonna be easier to do a : 
```
typealias Result<A> = Kleisli<EitherTKindPartial<IOHK, CharacterError>, Config, A>

fun Result<A>.raiseError
fun Result<A>.flatMap
```
where each extension exposes the API the user needs to operate and hides any explicit instances required by Kleisli and friends.

**Comment by JorgeCastilloPrz** [comment]
Sounds good 👍

**Comment by JorgeCastilloPrz** [comment]
@kategory/maintainers [the repo](https://github.com/kategory/kategory/issues/454) is ready to start working on top of it.

Some basic but key things to notice (those are already described in the readme, but I'll paste them here):
* We want to cover the same use cases and replicate the same screens the original repo has (already implemented on this repo by Google but under a basic Kotlin style). So we basically need to port those to a different architecture using kategory.
* We are completely free of removing layers / adding layers, and composing the architecture the way we want. We just need to keep the user visible features as they are in terms of usage.
* We must cover **the same use cases on tests**.
* A good way to iterate over is to pick one activity and iterate over it, leaving the resting ones untouched. Once we agree on a given approach, we can move forward and port that to the resting activities. We can easily start by a leaf node on the navigation tree, like the `AddEditTaskActivity` which is used to add or edit an already existent task on the todo app.

**Comment by aballano** [comment]
@JorgeCastilloPrz Is this ticket still valid or can we close it?

**Comment by JorgeCastilloPrz** [comment]
This got totally outdated. We never managed to get the blueprint for Android 100% ready (that's how my personal project started) so I'd wait for it then think about this again. We can close the issue for now.
