### ISSUE TITLE
Ensure all instances of `Semigroup` and `Monoid` are tested with laws

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow#460]
Laws available since:
https://github.com/kategory/kategory/pull/451

**Comment by Cotel** [comment]
I can take care of this 💪

**Comment by pakoito** [comment]
The task is now up for grabs! #463 already has a bunch of the required code, if anyone'd like to take a look.

**Comment by richard-gibson** [comment]
Happy to take this

**Comment by pakoito** [comment]
Please do ;_____;

**Comment by devesh-shetty** [comment]
Seems like this is still available, I'm taking this over 😉
![](https://media.giphy.com/media/aqMY57vLdkghi/giphy.gif)

**Comment by devesh-shetty** [comment]
@pakoito good to close this now?

**Comment by pakoito** [comment]
Yay! Also fixes https://github.com/arrow-kt/arrow/issues/1717

**Comment by devesh-shetty** [comment]
Fixed with https://github.com/arrow-kt/arrow/pull/1705
