### ISSUE TITLE
Add HK emulation explanation to the docs and link it on readme

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#465]
I knew this guy on the Kotlinconf and even if he is an OOP developer he has a good average knowledge on FP. He is trying to use the lib after seeing our talks and reading some posts etc, and he had big doubts on how to align types properly because he wasn't aware of what's HK for us and how we emulate them.

This is the conversation we had today:
<img width="1346" alt="captura de pantalla 2017-11-16 a las 16 33 26" src="https://user-images.githubusercontent.com/6547526/32899677-e85d4c0a-caeb-11e7-976d-74720d693bf1.png">

<img width="1274" alt="captura de pantalla 2017-11-16 a las 16 25 08" src="https://user-images.githubusercontent.com/6547526/32899499-7261ad84-caeb-11e7-8549-c17f2c6f8124.png">

I think he is rigtht. This seems to be one of our biggest handicaps atm with our current implementation. I suffered it a bit by myself while I was wroking on all the approaches on my android sample repo, even thought I was already aware of how the library is working. So I guess you can imagine how big can be the people confusion when they see all those inferred nested HK's and their types cannot align properly. 

I think we should include this explanation or a more polished one in the docs and try to be very explicit about it (even in repo readme, which is what users look at first when they want to start working with the lib)

**Comment by pakoito** [comment]
Done!
