### ISSUE TITLE
traverse sample code 

### ISSUE THREAD

**Issue by fgaule** [arrow-kt/arrow#498]
It would be really useful for beginners to have an example of how to traverse, for example a `Try`
from: Try<Sequence<List<Try<Int>>>>  to Try<Sequence<Try<Int>>>

I have tried to find an example in docs or kdoc without success :(

Thanks!

**Comment by pakoito** [comment]
I believe @JorgeCastilloPrz worked the most with it, as he also has the docs ticket: https://github.com/kategory/kategory/issues/333

**Comment by vejeta** [comment]
I recently wrote an article with examples about this: https://www.47deg.com/blog/traverse-typeclass-in-arrow/
