### ISSUE TITLE
Introduce `Parallel` type class, docs and instances for `IO`, `DeferredKW` and `ObservableKW`

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow#514]

**Comment by pakoito** [comment]
I believe MonadSuspend & Async are the requirements: https://github.com/kategory/kategory/blob/d9eec59cd8086896c2c0cd2d71b75faee297c83a/kategory-effects/src/main/kotlin/kategory/effects/typeclass/MonadSuspend.kt

We can formalise bindingFibers over it.
