### ISSUE TITLE
Videos not shown on kategory.io

### ISSUE THREAD

**Issue by jmfayard** [arrow-kt/arrow#537]
Bug report: while the links themselves are still perfectly valid, the two last youtube videos are not displayed for me on  http://kategory.io/docs/quickstart/blogs/

macOS High Sierra / chrome & safari

Building a DSL… in Kotlin => https://www.youtube.com/watch?v=kr8iWE4Jfhc

Functional approach to Android architecture using Kotlin => https://www.youtube.com/watch?v=qGef3sFAIxU

![image](https://user-images.githubusercontent.com/459464/34453217-b05715ea-ed4e-11e7-87af-27225d36ec07.png)

**Comment by pakoito** [comment]
@ersin-ertan added them in #532!! Could you please take a look?

**Comment by ersin-ertan** [comment]
Yes that's right, @jmfayard to follow the other videos format can you add the `?rel=0` query at the end of the link to prevent auto suggestions for #538

**Comment by pakoito** [comment]
It's fixed now!
