### ISSUE TITLE
Refactor Eval to new stack-safe version

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#557]
https://github.com/typelevel/cats/pull/1888/files

I just compared implementations with cats and they introduced changes in September to improve stack safety. cc @aedans

**Comment by aedans** [comment]
Sorry about the late reply; the notification got lost somewhere along the line. I'm working on this now.

Side note: do we care about renaming Call and Compute to Defer and FlatMap? I prefer Defer and FlatMap, and it's what cats uses, but it does technically break compatibility.

**Comment by pakoito** [comment]
It doesn't necessarily as those are just internal classes. In any case we don't care yet about retrocompatibility.
