### ISSUE TITLE
Review styles code + footer text

### ISSUE THREAD

**Issue by israelperezglez** [arrow-kt/arrow#560]
- [x] Change color in code tags
- [x] Add subtitle in footer content
- [x] Meta tags

**Comment by MaureenElsberry** [comment]
@israelperezglez  - just noticed that the favicon needs updating to the new logo also, not sure if that is in another issue or not.

**Comment by israelperezglez** [comment]
@MaureenElsberry We updated the favicon in other issue and we merged this change. Thanks

**Comment by israelperezglez** [comment]
@MaureenElsberry https://github.com/arrow-kt/arrow/pull/559

**Comment by MaureenElsberry** [comment]
you're the best! thanks

**Comment by israelperezglez** [comment]
;)
