### ISSUE TITLE
Discussion area

### ISSUE THREAD

**Issue by jasonab** [arrow-kt/arrow#567]
I'm trying to use Arrow in a new project, but unsurprisingly I have a few questions about how best to use it. What's the best place to discuss that?

**Comment by pakoito** [comment]
We haven't claimed the new gitter channel after the migration. For now, please come by https://gitter.im/kategory/Lobby and we'll answer your questions. Take into account that most current maintainers are in CET and GMT :D

**Comment by jasonab** [comment]
Damn it, I demand that you answer my homework questions immediately! :-)

Thanks, I'll check it out.

**Comment by pakoito** [comment]
We have the arrow-kt channel open and we'll merge #568 to include a widget on the docs.
