### ISSUE TITLE
Add maven central badge to README and doc site quick start

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow#571]
[![Maven Central](https://maven-badges.herokuapp.com/maven-central/io.arrow-kt/arrow-core/badge.svg)](https://maven-badges.herokuapp.com/maven-central/io.arrow-kt/arrow-core)

**Comment by Octogonapus** [comment]
@pakoito Should this be closed?

**Comment by pakoito** [comment]
Doooone!
