### ISSUE TITLE
Join the discussion about Λrrow and its internal development

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow#582]
We have created #arrow-contributors in kotlinlang.slack.com to discuss about the development and internals of the library. If you are interested you are welcome to join us there for a more fluid dialog. Cheers :beers: 

/cc @arrow-kt/maintainers

**Comment by pakoito** [comment]
:trollface:

**Comment by raulraja** [comment]
@pakoito thanks bro :smile:
