### ISSUE TITLE
MonadDeferLaws

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#590]
A port of these laws:

https://github.com/typelevel/cats-effect/blob/master/laws/shared/src/main/scala/cats/effect/laws/SyncLaws.scala

in here:

https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-test/src/main/kotlin/arrow/test/laws/MonadDeferLaws.kt#L23

(Sync is called MonadDefer in Arrow)

**Comment by sanogueralorenzo** [comment]
I'll take this one 😄

**Comment by 1Jajen1** [comment]
So if I understand this correctly the current MonadDeferLaws only include laws for binding over monad defer and should be extended by those present in cats-effect. The cats-effect typeclass seems to have different functions on top of what MonadDefer in arrow has (or maybe I just can't map the names correctly).
I'll try and get as many ported as possible and then see how it works :)

**Comment by pakoito** [comment]
You're correct, the ones in the current laws are ad-hoc for monadic comprehensions. We also need the ones from cats which are the original test suite for the typeclass :D

**Comment by 1Jajen1** [comment]
Closed by #1150
