### ISSUE TITLE
Plans for reactor integration

### ISSUE THREAD

**Issue by sbuettner** [arrow-kt/arrow#600]
Hey there,
glad to have a project that unifies functional programming for kotlin. 

Curious whether there are plans to support other reactive libraries beside rx2 like [reactor](http://projectreactor.io/)?

As reactor is the foundation for of the new spring (and spring boot) version I can imagine that a lot of server-side projects would benefit from such an integration.

**Comment by MarioAriasC** [comment]
We don't have it now but isn't difficult to implement. I already had a look at Reactor API and seems doable.

**Comment by pakoito** [comment]
Reactor copies RxJava's API and we already have those, so it shouldn't take long.

I'll make this into a feature ticket and either I'll do it when I have some time, or ask anyone interested in doing it themselves.

**Comment by MarioAriasC** [comment]
@pakoito depending on time, I can help

**Comment by pakoito** [comment]
Go for it. It needs instances up to Effect, and I believe it has Traversable too.

**Comment by Cotel** [comment]
I'm taking this ✋

**Comment by pakoito** [comment]
PR in #706

**Comment by pakoito** [comment]
Aaaaaand merged! Thanks @Cotel, I am very excited to support the Spring ecosystem better.
