### ISSUE TITLE
Replace all optics annotation with one annotation.

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow#605]
One annotation `@optics` with a parameter for granular control. Similar to `@deriving`, by default it will generate all optics applicable to the structure.

While doing so we should deprecate the existing annotations.

**Comment by jereksel** [comment]
@nomisRev My idea for api: https://gist.github.com/jereksel/f302bc67e11072b5fe2fbab77c244e49

**Comment by nomisRev** [comment]
@jereksel properties are allowed for kotlin annotations like so

```kotlin
annotation class optics(val targets: Array<OpticTarget> = [OpticTarget.ISO, OpticTarget.LENS, OpticTarget.PRISM, OpticTarget.OPTIONAL])

enum class OpticTarget {
    ISO, LENS, PRISM, OPTIONAL
}
```

API question would be for the API @raulraja @pakoito @jereksel thoughts?

If you annotate a `sealed class` with `@optics` does it also generate `LENS`, `ISO` and `OPTIONAL`, `PRISM` for its nested types.

```kotlin
@optics sealed class Json {
     data class JsString(val str: String): Json()

     sealed class JsNumber : JsNumber() {
          data class JsInt(val int: Int): JsNumber()
          data class JsLong(val long: Long): JsNumber()
     }

}
```

Would we generate 4 prisms: `Prism<Json, JsString>`, `Prism<Json, JsNumber>`, `Prism<JsNumber, JsInt>`, `Prism<JsNumber, JsLong>`.
And 3 lenses: `Lens<JsString, String>`, `Lens<JsInt, Int>`, `Lens<JsLong, Long>`
etc.

Or does an annotation only generate optics for its immediate targets. i.e. `JsString` and `JsNumber` in this case so 2 Prisms `Prism<Json, JsString>`, `Prism<Json, JsNumber>`.

**Comment by jereksel** [comment]
API: targets in optics must be empty by default - and we should treat empty array as "everything that can be generated".

I think generating for every subclass makes more sense than generating only for direct subclass
