### ISSUE TITLE
Ordering type

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow#674]
Needs more research, but basically something like this:

https://try.kotlinlang.org/#/UserProjects/67t0neksq2nuu9riqd1cchm6ds/hmji7priqofkibqoaeqosau4j0

For any `Foldable` or `Traversable` containing `Order` instances. This would add a property `ordering` of a type like:
```
enum Ordering {
  Empty, Single, Unsorted, Ascending, Descending
}
```

**Comment by nomisRev** [comment]
This has been added and is now deprecated :trollface:
