### ISSUE TITLE
Hash typeclass

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#687]
We have equals in `Eq`, toString in `Show`. Let's do hashCode in `Hash`!

https://github.com/typelevel/cats/blob/master/kernel/src/main/scala/cats/kernel/Hash.scala

**Comment by pt2121** [comment]
i'd like to take a stab at this

**Comment by 1Jajen1** [comment]
As per #795 I think I'll attempt this. Is the old branch still worth using, or should I start fresh. On that note: Are there some guides to contributing? Or is it best to just start and go along with it in a pr? :)

**Comment by pakoito** [comment]
The contributing guide is...incomplete at best. You need:

* The typeclass
* An instance for at least a couple of datatypes, specially wrappers like Id, ListK, SetK, MapK, SequenceK...
* A set of Laws/Tests
* Apply the laws to the instances

And lastly, the docs. Ping me when you're ready for this
* An entry on the docs menu
* Its own doc

**Comment by pakoito** [comment]
Closed by #1138
