### ISSUE TITLE
Selectively catching exceptions with Try

### ISSUE THREAD

**Issue by vibinr** [arrow-kt/arrow#709]
Hi, I tried converting my below imperative try-catch code to use Arrow's Try.

Before:

```kotlin
    return try {
        val contentProvResult = ctx.contentResolver.applyBatch(AUTHORITY, contentProvOps)
        Timber.d("Wrote a new contact with result %s", contentProvResult)
        true
    } catch (e: RemoteException) {
        Timber.e(e)
        false
    } catch (e: OperationApplicationException) {
        Timber.e(e)
        false
    }
```

After:

```kotlin
return Try { ctx.contentResolver.applyBatch(AUTHORITY, contentProvOps) }
    .fold({
        Timber.e(it)
        false
    }, {
        Timber.d("Wrote a new contact with result %s", it)
        true
    })
```

But these two don't exactly behave the same way, as the latter one catches Throwable itself.

(sorry if this question is too rudimentary! I read Try's API and docs, but they didn't help)

**Comment by pakoito** [comment]
Try this:

```
return Try { ctx.contentResolver.applyBatch(AUTHORITY, contentProvOps) }
    .fold({
        when (it) {
          is RemoteException -> ...
          is OperationApplicationException -> ...
          else ->
        }
    }, {
        Timber.d("Wrote a new contact with result %s", it)
        true
    })
```

You're not supposed to let exceptions propagate anymore else it defeats the point of using `Try` in the first place, so the else case inside that `when` has to do something about them.

**Comment by vibinr** [comment]
Makes sense, thank you!

**Comment by pakoito** [comment]
Cheers! We do have a gitter channel if you'd like to ask more questions: https://gitter.im/arrow-kt/Lobby
