### ISSUE TITLE
Try class

### ISSUE THREAD

**Issue by neilcronin** [arrow-kt/arrow#719]
Hi,

I am attempting to use the Try class with a maven project.

This is the class: 

https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-core/src/main/kotlin/arrow/core/Try.kt

There are basically no docs for using this library with maven.

I added this to my pom.xml:

        <dependency>
            <groupId>io.arrow-kt</groupId>
            <artifactId>arrow-core</artifactId>
            <version>0.6.1</version>
        </dependency>

I got arrow.core.*

The .jar file I ended up with does not have Try class.  

How do I add a maven dependency so I can import arrow.core.Try ?

Thanks!
-neil

**Comment by pakoito** [comment]
In 0.6.1 `Try` is inside arrow-data. We just recently moved it to arrow-core because it's quite liked, but for some people bringing arrow-data was a bit too much.

**Comment by pakoito** [comment]
@neilcronin did my answer solve your issue?

**Comment by pakoito** [comment]
Closing for now. 0.7 will sync the docs too.
