### ISSUE TITLE
Free Foldable and Traverse Instances

### ISSUE THREAD

**Issue by aedans** [arrow-kt/arrow#720]
Just as it sounds, Free doesn't have Foldable and Traverse instances when it should. 

[Cats Implementation](https://github.com/typelevel/cats/blob/5861210bec55b000d1e4962f4002edfdea627c0b/free/src/main/scala/cats/free/Free.scala#L286`)

I'm not really sure how to approach this, as I'm not too familiar with the free monad. I'll take it if I manage to figure it out though.

**Comment by i-walker** [comment]
closed with #1522
