### ISSUE TITLE
Split instance module to avoid transitive `arrow-data` dependency.

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow#724]
Add a `*-instances` module for each logical module:
```
arrow-core
arrow-core-instances
arrow-data
arrow-data-instances
arrow-free
arrow-free-instances
```
This will allow us to activate comprehensions and other interesting syntax without depending transitively in `arrow-data` through `arrow-instances` since the latter currently includes all instances including those for `arrow-data`

**Comment by pakoito** [comment]
Done in #758
