### ISSUE TITLE
`As` typeclass

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#725]
https://www.reddit.com/r/ProgrammingLanguages/comments/823y9e/implementing_rusts_stdconvertinto_in_scala_in/

We could provide default implementations for Option <--> Either <--> Try

It needs laws & documentations.

**Comment by raulraja** [comment]
For those kinds this type class already exist as `FunctionK` and works out of the box both in Dagger and Runtime lookups: For non kinded values this would be `Function1#map` where an Implicit value of `Function1<A, B>` exist in scope. The missing piece is the implicits which Keep-87 or our new type-class encoding can take care off automatically.

**Comment by pakoito** [comment]
I'd suggest just making it available for non-kinded types.

**Comment by nomisRev** [comment]
Closing ticket due to Kinds getting deprecated.
