### ISSUE TITLE
Code in documentation for the State datatype

### ISSUE THREAD

**Issue by evantill** [arrow-kt/arrow#728]
Hi,

I am trying to reproduce the for comprehension in the documentation http://arrow-kt.io/docs/datatypes/state/

```kotlin
import arrow.typeclasses.*
import arrow.instances.*

fun stackOperations() = State().monad<Stack>().binding {
    val a = push("a").bind()
    val b = pop().bind()
    val c = pop().bind()

    c
}.fix()
```

But I can not find the `fix()` method.

Is there some special import or something else ?

Thank you.

**Comment by evantill** [comment]
here the gist

https://gist.github.com/evantill/a547e96cfd599f6cf296883afd4999f0

**Comment by pakoito** [comment]
The docs are for `master`, which has a rename of several methods: https://github.com/arrow-kt/arrow/pull/671

If you're using 0.6.1, the method is called `ev()`.

**Comment by evantill** [comment]
This is it. I am using 0.6.1.

Thank you very much
