### ISSUE TITLE
NonEmptyList :: foldLeft slide from Youtube video series has typos

### ISSUE THREAD

**Issue by Guardiola31337** [arrow-kt/arrow#730]
- NonEmptyList :: foldLeft slide (5) from [Youtube video](https://www.youtube.com/watch?v=TC6IzE61OyE#t=1m7s) series has typos 👀

![nonemptylist_foldleft_slide5](https://user-images.githubusercontent.com/1668582/37242262-aff58682-2466-11e8-94e4-c985614f2df6.png)

Wondering if we could fix them and render the video again.

cc @raulraja @israelperezglez

**Comment by raulraja** [comment]
@Guardiola31337 https://github.com/47deg/fp-with-arrow-videos/blob/master/NonEmptyList.md if you submit a PR there with the changes we can re-render the slides and video /cc @benjymontoya

**Comment by Guardiola31337** [comment]
Sure thing! Didn't know about that repo 😅

**Comment by Guardiola31337** [comment]
@raulraja 
> if you submit a PR there with the changes we can re-render the slides and video

There you go https://github.com/47deg/fp-with-arrow-videos/pull/18 😉

**Comment by raulraja** [comment]
Closing this old issue, thanks @Guardiola31337. Not sure if it ever got fixed but probably too late to rearrange old, outdated videos.
