### ISSUE TITLE
Generate classes on target class packages

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#765]
Processors should ideally generate classes on target class package, being target the annotated class. This should be updated for all of them. Explanations here.

https://github.com/arrow-kt/arrow/pull/747#discussion_r179699753

**Comment by AdrianRaFo** [comment]
Hi, @JorgeCastilloPrz  I'm going to work on this issue, so, Can you please assign it to me?

**Comment by JorgeCastilloPrz** [comment]
All yours! :) welcome to the maintainers team 🎉 Thanks for taking this!

**Comment by raulraja** [comment]
Closing old issues related to old kapt processors. thanks, @JorgeCastilloPrz @AdrianRaFo
