### ISSUE TITLE
Do not throw on processors

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#766]
Some processors are throwing errors instead of using the messager for that. Ideallly they should use the messager which we're already using on different parts. Explanations [here](https://github.com/arrow-kt/arrow/pull/747#discussion_r179699753)

**Comment by nomisRev** [comment]
Actually, in [AbstractProcessor](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-annotations-processor/src/main/java/arrow/common/utils/AbstractProcessor.kt) we catch `KnownException` and use the messager.

Still not ideal but better than not using it I guess. I was looking into how we could offer better error messages but this requires quite some changes.

i.e. `@autofold` for an untyped `Maybe`

```kotlin
sealed class Maybe
data class Just<B>(val b: B): Maybe()
object Nothing: Maybe()
```

You would want an error message like.

```
@autofold cannot create a fold method for sealed class Maybe
sealed class Maybe
                                 ^ contains less generic information than a variant 

is Just<A> -> just(this)
              ^  Cannot check for an instance of an erased type: Just<A>
```

I've accomplished above error message for autofold on a local branch but it relies on `knownError` and the implementation is still quite dirty.

Some bigger changes are required in our meta code for testing, maintainability and error messages IMHO. I see it growing/evolving at a increasing speed with `optics`, typeclasses and `generic`.

**Comment by raulraja** [comment]
Closing old issues related to old kapt processors. thanks @JorgeCastilloPrz @nomisRev
