### ISSUE TITLE
Refactor instances

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#767]
Based on [this](https://github.com/arrow-kt/arrow/pull/747#discussion_r179702780) discussion and given that there's no more runtime lookup, we'd probably want to discuss whether we wanna keep or remove the `**Instance` suffix from instances that we added just by convention in the beginning.

Initial proposal to start discussion:
<img width="637" alt="captura de pantalla 2018-04-06 a las 14 52 50" src="https://user-images.githubusercontent.com/6547526/38422232-3c7c2c34-39aa-11e8-898d-d50e67d8dc6e.png">

**Comment by pakoito** [comment]
Ooooold
