### ISSUE TITLE
ManagedT datatype

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#795]
https://www.iravid.com/posts/resource-management.html

https://github.com/iravid/managedt/blob/master/core/src/main/scala/com/iravid/managedt/ManagedT.scala

**Comment by 1Jajen1** [comment]
Is this still relevant? If so I could attempt this. I was looking for something to get familiar with arrow (and contributing to it) and this seems doable. If there is something else more recent (and easy to get started with) then please point me to that as well :) 
As for ManagedT implementing this with using bracket should not be too hard or am I missing something here?

**Comment by pakoito** [comment]
`ManagedT` sounded like a fun datatype to add. It isn't a must, but rather a nice to have if you'll have fun writing it!

If you'd like some easier tickets that touch several parts of the codebase, there is:

Hash typeclass: https://github.com/arrow-kt/arrow/issues/687
MonadSuspendLaws: https://github.com/arrow-kt/arrow/issues/590, https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-test/src/main/kotlin/arrow/test/laws/MonadDeferLaws.kt#L23

**Comment by 1Jajen1** [comment]
I think I'll take a look at hash first and after that either #590 or this one. Thanks for the quick answer :)

**Comment by pakoito** [comment]
Neat! Up next, some effects for you: #590

This one should be quicker than Hash, and at the same time allow you to experiment a bit with `arrow-effects`.

**Comment by 1Jajen1** [comment]
Ok so now with MonadDefer done, what would be something good to have next? This, an attempt at the Deferred issue or is there something else?

**Comment by pakoito** [comment]
@1Jajen1 If you're not interested in Deferred, you can define the typeclass for destructuring: https://github.com/arrow-kt/arrow/issues/284

**Comment by 1Jajen1** [comment]
Closed by #1376
