### ISSUE TITLE
Searchbar for docs

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#808]
Whenever I get into http://arrow-kt.io/docs/ I miss having a search bar for "fast search" with autocomplete, so whenever I start typing right after loading the page It searches for typeclasses, data types, patterns or any other concrete section in the docs.

This would mimic the search on github (clicking `T`) and start typing. In our case we don't have any need to type on the docs page as a user, so that could just trigger search without the explicit need to click on the search icon (which should also be possible, for UX).

Opinions?

**Comment by calvellido** [comment]
Much needed IMO. I guess offering results from the docs themselves won't be hard at all to add. If we want to also show code results a la API search, I'm not sure the best way to approach that.

**Comment by JorgeCastilloPrz** [comment]
Yeah that would be even cooler but we probably don't need to go that far for an initial release of the feature. I'd probably leave that for further iterations :)

**Comment by calvellido** [comment]
There are some 3rd party options out there, the most widely used seems to be Algolia. They ask to include its name on the search bar to use it for free. You can see an example here:

https://material-ui-next.com/

An _inhouse_ solution is not that hard, but we would have to restrict _searchable_ elements to title, tags, category, and things like that, but not the full page content, if we want to be showing results quickly.

Whatever option people see better, I'd like to work on it if everybody agrees 🙂   Just in the middle of a delivery deadline, but can start having a look next week.  Probably asking @israelperezglez help with styles and such.

**Comment by JorgeCastilloPrz** [comment]
I don't have a good scope on the frontend libs ecosystem, but the Algolia one looks quite good to me and it uses material guidelines so how could I not like it? 🥒 

Putting effort on an in-house approach is probably not gonna provide much value compared to using an already created one that actually looks that good, and we probably want to put those efforts in other stuff. If we can fit one of those good looking react components the website will get all the people searching for docs needs from it. just IMO

And I'll be happy if you take it!

**Comment by calvellido** [comment]
This is coming along nicely, it will be probably ready on Monday or Tuesday   :slightly_smiling_face: 

![captura de pantalla de 2018-06-15 18-10-01](https://user-images.githubusercontent.com/7753447/41478315-850ed812-70c7-11e8-8a80-45723ffa58a7.png)
