### ISSUE TITLE
Partial function application with multiple arguments?

### ISSUE THREAD

**Issue by johanhaleby** [arrow-kt/arrow#814]
I cannot seem to find a way to provide multiple arguments when creating a partial function.

Consider this example:

```kotlin
fun tryingPartialApplication() {
     // This is the only way I've found if I'm not using curring
     val partiallyApplied = ::theFn.partially1("Hello").partially1("World")
}


fun theFn(string1: String, string2: String, string3 : String) = string1 + string2 + string3
```

which I believe is quite verbose. An alternative is to use currying:

```kotlin
val curried = ::theFn.curried()("Hello")("World")
```

I'd like just do something like this:

```kotlin
val partiallyApplied : (string3: String) → String = ::theFn.partial("Hello", "World")
```

Is something like this already possible?

**Comment by pakoito** [comment]
Yes, it's in the module `arrow-syntax`. Check this file: https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-syntax/src/main/kotlin/arrow/syntax/function/partials.kt

**Comment by pakoito** [comment]
cc #802

**Comment by johanhaleby** [comment]
@pakoito Thanks but I already managed to find that file. Unfortunately I cannot seem to figure out how it's done regardless of the `partials.kt` file. Are you referring to the `invoke` operator?

**Comment by pakoito** [comment]
Hmmm you're right. I'll defer to @MarioArias for this one.

**Comment by MarioAriasC** [comment]
You can use 
```kotlin
import arrow.syntax.function.invoke

theFn("Hello")("World")
//Or if you need to specify the parameter order
theFn(p2 = "World")(p1 = "Hello")
```

The current implementation of partially applied functions doesn't allow multiple parameters.

The reason is simple, Space. Partially applied functions are generated with a script from `Function2` to `Function22` and currently is the biggest file in the project.

Creating all possible combinations of multiple parameters will be impossible to write and compile.

Alternatively, we can have multiple parameters for `Function3` to `Function5` that are the most used ones

I'm thinking about having compile-time generated approach similar to the one that we have with optics. Something like:

```kotlin
@partially fun theFn(string1: String, string2: String, string3: String)

theFn("Hello", "World")
```
Let me know your thoughts

**Comment by johanhaleby** [comment]
@MarioAriasC Thanks for you help and suggestions!

I'm probably a bit biased since I'm used to Clojure where you typically do:

```clojure
(defn theFn [string1 string2 string] ,,,)

(partial theFn "Hello" "World") ; Generates a partial function from String -> String
```

This is why I'd appreciate something similar in arrow.  

> @partially fun theFn(string1: String, string2: String, string3: String)

This would probably work although I personally I would prefer not to have to add `@partially`. Perhaps it would be possible to support multiple parameters for the most used combinations that you imply and for the others introduce `@partially`? But perhaps this mixed approach would be more confusing?

**Comment by pedromss** [comment]
Hey. Not sure if still useful but I had to do this slightly different

```kotlin
package arrow.kt.tests

import arrow.syntax.function.invoke

fun m1(a: Int, b: Int): String = "$a + $b = ${a + b}"

fun m2() = (::m1)(1)

fun main(args: Array<String>) {
    println(m2()(3))
}
```

So the `::m1(1)` syntax generated the following error: 
> This syntax is reserved for future use; to call a reference, enclose it in parentheses: (foo::bar)(args)

Probably something that was updated in the Kotlin lang since Apr 2018.

**Comment by raulraja** [comment]
Thanks to everyone that participated here. I'm Closing this outdated issue as we prepare for 1.0. The state of partials has not changed and still needs docs if someone is interested in contributing them :). Cheers!
