### ISSUE TITLE
Annotation processor doesn't work with maven

### ISSUE THREAD

**Issue by routis** [arrow-kt/arrow#840]
It seems that the annotation processor doesn't work in maven. 

In particular, attempting to use the annotation processor, compilation fails with a null pointer exception thrown by  **arrow.instances.InstanceProcessor.onProcess(InstanceProcessor.kt:38)**, while trying to access the property **generatedDir** defined in its ancestor class **me.eugeniomarletti.kotlin.processing.KotlinAbstractProcessor**
[error.txt](https://github.com/arrow-kt/arrow/files/1983433/error.txt)
(See the details on the attached file)

I have created a simple [project](https://github.com/routis/kaptdemo) to demonstrate the problem.

I am not sure whether this is an actual bug or whether am I missing something in the maven configuration. 
In any case probably it would be a good idea to add a section to the documentation of arrow detailing how to use annotation processing with maven

**Comment by Eternity-Yarr** [comment]
It appears that this was fixed in next releases of kotlin plugin. I've created a pull request with changes to your repository which compiles successfully,

**Comment by Eternity-Yarr** [comment]
https://github.com/routis/kaptdemo/pull/1

**Comment by routis** [comment]
Indeed, problem does not appear when using  korlin plugin 1.2.41 and by adding the companion object.
@Eternity-Yarr Thanks for the solution

Perhaps, it would be nice to have in the "Quick Start" page of the Arrow documentation a section for maven.

**Comment by routis** [comment]
Updated the https://github.com/routis/kaptdemo that should reproduce this issue

**Comment by pakoito** [comment]
We changed the repositories needed for the project to include JitPack. Have you added it too?

**Comment by routis** [comment]
@pakoito Thanks

```
<repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>jitpack</id>
            <url>https://jitpack.io</url>
        </repository>
```

**Comment by pakoito** [comment]
@routis could you please PR it against the README?

**Comment by pakoito** [comment]
@routis close the ticket for now?  :D

**Comment by TAGC** [comment]
I'm having this problem too, using Gradle rather than Maven and having followed the Gradle-specific instructions (there's no mention of JitPack in them).

**Comment by pakoito** [comment]
@TAGC is it fixed then?

**Comment by TAGC** [comment]
Yeah.

**Comment by Octogonapus** [comment]
@pakoito Should this be closed? They figured out the problem.

**Comment by pakoito** [comment]
Closing!
