### ISSUE TITLE
Add remaining Monoid and Semigroup instances

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#841]
At the moment several instances from Scala are not available in Arrow, like the one for `Try`. The task is to do a pass on the codebase and write them.

**Comment by bassjacob** [comment]
I'd be happy to help with this

**Comment by pakoito** [comment]
Neat, we got `Try` and `Either` now :D

What's left?

**Comment by bassjacob** [comment]
Still to come:

* [ ] function0/ function1 -https://github.com/scalaz/scalaz/blob/series/7.3.x/core/src/main/scala/scalaz/std/Function.scala
* [ ] char
* [ ] id
* [ ] boolean
* [ ] const which can reuse some functions from the typeclasses file
* [ ] eval - I'm not sure what the semantics to choose for eval would be

I'll get started on id next

**Comment by bassjacob** [comment]
Do you want arrow-data-instances as part of this issue or a separate one?

**Comment by pakoito** [comment]
>Do you want arrow-data-instances as part of this issue or a separate one?

I'm not sure I follow.

**Comment by pakoito** [comment]
>I'm not sure what the semantics to choose for eval would be

Let's do a live session when you reach it, I have an idea but would need to be in front of the code.

**Comment by bassjacob** [comment]
The data types I listed above are from arrow-instances-core. There's also a few missing I think from arrow-instances-data that we might want to add?

**Comment by nomisRev** [comment]
I'm closing this due to all the instances discussed here are available in Arrow Core. Re-open a new ticket if Monoid or Semigroup instances found missing please 👍 Thanks all for th work!
