### ISSUE TITLE
Upgrade Dagger to 2.5

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#871]
We are using a quite old version (`2.15`) and they've changed a couple of things lately that are causing some trouble when trying to compile client projects using both Arrow 0.7.2 and Dagger 2.5

**Comment by jereksel** [comment]
Wait, but dagger 2.15 is never than 2.5

**Comment by LordRaydenMK** [comment]
Hey @JorgeCastilloPrz 

as @jereksel mentions Dagger 2.15 is newer than 2.5
The latest Dagger release is 2.18 released 9 days ago: https://github.com/google/dagger/releases

Dagger 2.15 was released on Mar 7 and Dagger 2.5 was released on Jun 15, 2016.

There is a [PR](https://github.com/JorgeCastilloPrz/ArrowAndroidSamples/pull/23/files) on your Android sample project where you mention a Dagger downgrade but it was actually an upgrade.

Is this issue still relevant?
