### ISSUE TITLE
Provide a self-explanatory example by re-writing Kotlin-Fullstack app

### ISSUE THREAD

**Issue by soberich** [arrow-kt/arrow#879]
Hi, 
(Former) Kategory could be a technology of the choice for teams like our if such popular and well known example as [Kotlin-Fullstack](https://github.com/Kotlin/kotlin-fullstack-sample) could demonstrate it's top abilities (particularly coroutines usage) in comparison to the original one sample mentioned. 
This would've fill the empty space in your "samples" stack where there is nothing for backend / fullstack but just Android one's.
Please, provide a self-explanatory technology overview in such a sample.
#### Edit
Using [Create-React-Kotlin-App](https://github.com/JetBrains/create-react-kotlin-app) as a an edge accompanying technology would be an edge sample in whole industry. Maybe even JetBrains will be interested in cooperation to prepare it.

**Comment by pakoito** [comment]
Github is a snitch.

I don't have the background to help with this one, as backend work is something I've never engaged with. Maybe another maintainer will be more helpful here.

**Comment by soberich** [comment]
Great, there is a Spring 5 backend example listed in [examples tab](https://arrow-kt.io/docs/quickstart/projects/) now https://github.com/istonikula/realworld-api now

**Comment by pakoito** [comment]
Right, I forgot to ping you :D

**Comment by pakoito** [comment]
Is is worth keeping this issue around, or can I close it?

**Comment by soberich** [comment]
Yes, full stack I believe will appear as well.

**Comment by serras** [comment]
I think our current _Example projects_ page fits the bill quite well https://arrow-kt.io/learn/design/projects/
