### ISSUE TITLE
Add Semigroup Instance for Either

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#881]
Create a `Semigroup` Instance for `Either` with the following behaviour: 
* SG from Left & Right = Right, just the combination of Left & Left would be = Left

**Comment by pakoito** [comment]
@bassjacob is taking a look at this ticket already!

**Comment by bassjacob** [comment]
Yep, I've got it. Will update with a PR here for Either and Try

**Comment by 1Jajen1** [comment]
Closed in https://github.com/arrow-kt/arrow/pull/942
