### ISSUE TITLE
Use awaitAll for DeferredK

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#884]
Apply `awaitAll` to the implementation of DeferredK where it applies https://github.com/Kotlin/kotlinx.coroutines/pull/323/files

**Comment by richard-gibson** [comment]
Hey, I can take this one

**Comment by pakoito** [comment]
I believe @sanogueralorenzo is already looking into it. I really don't know where it could benefit us, maybe just for `ap`, but if it's better than what's there I won't say no :D

**Comment by richard-gibson** [comment]
no problem, 
looks like awaitAll() could br implemented for any Traverse<DeferredK<A>> by  just using sequence followed by await on the result 
(as you said whether its worth having)

**Comment by pakoito** [comment]
If you have a PR then first come first serve! :D

**Comment by pakoito** [comment]
Completed and done, thanks @richard-gibson !!!
