### ISSUE TITLE
Renzu iteration 2: Pull it out from standard builds

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#890]
Renzu is an annotation processor included in the processors artifact. It requires running for any modules providing `@instance`so it can crawl upwards starting on those. 

But still there's not a strong need by the user to run it, and for the end user this is just a side effect. So it would be nice to find the way to run it manually by us and move it out from the standard builds.

Ideas so far:
* Create a new module that depends on all the resting ones and the renzu processor, plus remove renzu from the processors artifact. This would be ideal but I fear it wouldn't work. Renzu would just run taking the sources from the newly created module as input, and not the ones from the proper modules.
* Create a gradle task or a console command to run a given processor using `kapt` and passing in all the sources from an N amount of given modules as input. This would be perfect, but I don't know whether it's even possible.
* Reencode Renzu in a way that it doesn't need to be an AP anymore and can still crawl the class hierarchy detecting what's a typeclass and what's an instance. It couldn't be a compiler plugin either, since we don't want to run it on each compilation. This one is probably too optimistic and I didn't go for that in the beginning bc it's completely out of my control, since it would require to parse and analyze each source file passed in as input using some reflection apis or something similar.
* Add command line arguments to tell renzu to run, so it doesn't run for all the cases but just when we actually tell it to run on the build command. Something similar to: `./gradlew build -PrunRenzu`, `./gradlew build -PrunRenzu=core,effects,data...`. This could be the easiest one and the first one I'd try, given that it's already encoded as an AP.

**Comment by pakoito** [comment]
It should go there instead:

https://github.com/arrow-kt/arrow/blob/master/.travis.yml#L10

**Comment by JorgeCastilloPrz** [comment]
I'm closing this. The overall goal was to optimize how renzu works and it has already been done. Renzu was refactored so it renders diagrams inside autogenerated docs by @raulraja so that's where the value is. If at some point we believe we're on the need for something bigger, we can reopen it or create a different ticket.
