### ISSUE TITLE
Can't find arrow-recursion dependency

### ISSUE THREAD

**Issue by maxcruz** [arrow-kt/arrow#891]
I get an error when trying to synchronize the project with the package arrow-recursion

Failed to resolve: io.arrow-kt:arrow-recursion:0.7.2

Android Studio: 3.2 Canary
Gradle: 4.6-all

**Comment by pakoito** [comment]
This is my fault. The artifact wasn't included in the release, it'll be available for 0.7.3 alongside docs.

**Comment by maxcruz** [comment]
Thanks @pakoito

**Comment by pakoito** [comment]
We should be releasing soon, we're blocked on an Android only issue :) Try a snapshot meanwhile!

```
maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local' }
```

**Comment by pakoito** [comment]
Fixed!
