### ISSUE TITLE
Sort classes in Renzu infographic

### ISSUE THREAD

**Issue by jereksel** [arrow-kt/arrow#892]
[There are a lot of changes to Renzu](https://github.com/arrow-kt/arrow/commits/master/infographic/arrow-infographic.txt), but most of them are just copying caused by non-deterministic class traversal.

**Comment by pakoito** [comment]
I did an attempt on https://github.com/arrow-kt/arrow/pull/896. It didn't quite fix it but at least PRs are shorter now :)
