### ISSUE TITLE
Lens Laws link Broken

### ISSUE THREAD

**Issue by JLLeitschuh** [arrow-kt/arrow#893]
The link at the bottom of this page to LensLaws is broken.
https://arrow-kt.io/docs/optics/lens/

**Comment by JLLeitschuh** [comment]
Same for Prisim

**Comment by nomisRev** [comment]
Thanks a lot for letting us know! Will be fixed in #895

**Comment by pakoito** [comment]
@JLLeitschuh Thank you for reporting!

**Comment by JLLeitschuh** [comment]
Wow. Awesome turnaround on this, thanks all!
