### ISSUE TITLE
How can I create a Writer?

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [arrow-kt/arrow#904]
Hello, folks.

I'm trying to create a Writer, so I can log my computation without side effects. I was looking for something like:
```
scala> 3.set("Some log!") // Result: scalaz.Writer[String,Int] 
```
But I don't see this behaviour. There's still no documentation for the MonadWriter =/. I am studying the code to get how it works, but it would be great if there was an extension function that just creates the Writer.

**Comment by pakoito** [comment]
Hi Leandro! I believe you'll need WriterT for this, which is sadly undocumented and I'm not too familiar with. Can you please ping @raulraja in one of our channels, like [gitter](http://gitter.im/arrow-kt) or #arrow in Kotlinglang slack?

**Comment by leandroBorgesFerreira** [comment]
Thanks Pakoito! I will do that.

**Comment by pakoito** [comment]
@leandroBorgesFerreira Worth closing this ticket?
