### ISSUE TITLE
Deploy ends with failure

### ISSUE THREAD

**Issue by jereksel** [arrow-kt/arrow#927]
And what's worse travis shows build as successfull:
https://travis-ci.org/arrow-kt/arrow/builds/400204130#L7844

**Comment by pakoito** [comment]
Did we figure out why?

**Comment by jereksel** [comment]
I don't think so. It just started to work properly: https://travis-ci.org/arrow-kt/arrow/builds/402291277#L8084. But I think we should add `set -e` to deploy scripts just in case.
