### ISSUE TITLE
Change A -> B -> C functions in Optics to (A, B) -> C

### ISSUE THREAD

**Issue by jereksel** [arrow-kt/arrow#940]
Breaking change so former must be deprecated (Fortunatelly there won't be any issues with generic erasure)

**Comment by jereksel** [comment]
I think we don't have to remove old ones: https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html#handling-signature-clashes-with-jvmname

**Comment by pakoito** [comment]
cc @nomisRev !!

**Comment by nomisRev** [comment]
Closed by #1061
