### ISSUE TITLE
Add Vector construct

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#97]
https://github.com/FineCinnamon/Katz/blob/master/katz/src/main/kotlin/katz/data/NonEmptyList.kt
https://github.com/FineCinnamon/Katz/blob/master/katz/src/main/kotlin/katz/instances/NonEmptyListBimonad.kt
https://github.com/FineCinnamon/Katz/blob/master/katz/src/main/kotlin/katz/instances/NonEmptyListMonad.kt
https://github.com/FineCinnamon/Katz/blob/master/katz/src/main/kotlin/katz/instances/NonEmptyListComonad.kt
https://github.com/FineCinnamon/Katz/blob/master/katz/src/main/kotlin/katz/instances/NonEmptyListSemigroup.kt

It'll also require a Monoid instance, rather than a semigroup. You have to figure out why and how ;)

**Comment by pakoito** [comment]
The implementation for Array<A> is simply not possible due to some limitations with non-reified generics. Let's consider porting a persistent vector from Scala, Clojure, or any external library instead.

**Comment by pakoito** [comment]
Some persistent Vector implementations:

Scala:
https://github.com/djspiewak/scala-collections/blob/master/src/main/scala/com/codecommit/collection/Vector.scala

Clojure: https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/PersistentVector.java

Kotlin based off PCollections: https://github.com/Kotlin/kotlinx.collections.immutable

Paguro: https://github.com/GlenKPeterson/Paguro/blob/master/src/main/java/org/organicdesign/fp/collections/PersistentVector.java

**Comment by raulraja** [comment]
@pakoito, thanks for bringing this up, looks like we decided in a different direction just supporting the std lib types. Closing this outdated issue. Thanks!
