### ISSUE TITLE
Migrate to non-".experimantal.." coroutine package. Conflict with new 1.3-M1 and 0.24.0-eap13. "Can't use .experimental package"

### ISSUE THREAD

**Issue by soberich** [arrow-kt/arrow#973]
I guess it's already on the list. Can't use it now with arrow relevant module.
When should this be migrated?

**Comment by pakoito** [comment]
Should we wait out for the release? I don't think we're ready to support the pre-release as it is, it'll take some months for them to stabilize it.

**Comment by soberich** [comment]
Thank you. This is, of course, reasonable.

**Comment by pakoito** [comment]
Let's keep this open as a reminder.

**Comment by pakoito** [comment]
Working on 1.3 on this PR https://github.com/arrow-kt/arrow/pull/1005

It all works now, we just need to wait for the final release.

**Comment by soberich** [comment]
@pakoito feel free to close.
