### ISSUE TITLE
Update Jacoco to 0.8.2

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#982]
https://twitter.com/AlanMenant/status/1027076597147422721

**Comment by jtuchek** [comment]
It looks like this already up to date at `0.8.2` https://github.com/arrow-kt/arrow/blob/0d50bad0edfac220fb2785ed2ede0240b3ce19b7/build.gradle

Could we call this completed?

**Comment by pakoito** [comment]
Oh, nice catch. Thanks!
