### ISSUE TITLE
Compose a list of function.

### ISSUE THREAD

**Issue by adithep** [arrow-kt/arrow#996]
Currently one can compose 2 functions together by

`val func3 = func1 compose func2`

I am suppose to be able to compose list of function by

`val func4 = listOf(func1, func2, func3).reduce {a, b -> a compose b}`

but currently this is impossible due to various type error.

Am I missing something? Is there a way to somehow achieve this. Or is there a way for me to write my own compose that accept list?

**Comment by pakoito** [comment]
It sounds like something that should be possible. Can you please re-do the example, this time with type annotations for each function and the whole list?

**Comment by adithep** [comment]
```
val add5 = { i: Int -> Option(i + 5) }
val multiplyBy2 = { i: Int -> i * 2 }
fun isOdd(x: Option<Int>) = x.map { y -> y % 2 != 0 }

val composed = listOf(::isOdd, add5, multiplyBy2).reduce { a, b -> a compose b  }
```

Error:

> Type inference failed: Cannot infer type parameter IP in inline infix fun <IP, R, P1> ((IP) -> R).compose(crossinline f: (P1) -> IP): (P1) -> R
> None of the following substitutions
> receiver: (Any) -> Any  arguments: ((Nothing) -> Any)
> receiver: (Nothing) -> Any  arguments: ((Nothing) -> Nothing)
> can be applied to
> receiver: Function1<*, Any>  arguments: (Function1<*, Any>)

So I try:

`val composed = listOf<(Any) -> Any>(::isOdd, add5, multiplyBy2).reduce { x, y -> x compose y }`

Error:

> Type mismatch: inferred type is KFunction1<@ParameterName Option<Int>, Option<Boolean>> but (Any) -> Any was expected
> Type mismatch: inferred type is (Int) -> Option<Int> but (Any) -> Any was expected
> Type mismatch: inferred type is (Int) -> Int but (Any) -> Any was expected

**Comment by pakoito** [comment]
This is hard to explain but it's just not possible to do `List<(Any) -> Any>` and compose any two functions together. I'm just glad it's a compile time error rather than a runtime ClassCastException.

Try using TupleN or HList instead, although I'm not sure those are reducible :/

**Comment by Octogonapus** [comment]
@pakoito Should this be closed? It seems like their feature request can't be fulfilled.

**Comment by pakoito** [comment]
Agreed!
